import { defineConfig } from '@hey-api/openapi-ts';

export default defineConfig({
  input: './swagger.json',
  output: {
    format: 'prettier',
    lint: 'eslint',
    path: './src/api',
  },
  hooks: {
    afterGenerate: async () => {
      // Ensure pagination exports are available in src/api/index.ts
      const fs = await import('fs');
      const path = await import('path');

      const indexPath = path.resolve('./src/api/index.ts');
      const indexContent = fs.readFileSync(indexPath, 'utf-8');

      if (!indexContent.includes('../lib/pagination')) {
        const newContent = `// This file is auto-generated by @hey-api/openapi-ts
// Pagination module is manually maintained in src/lib/pagination and re-exported here

export * from './types.gen';
export * from './sdk.gen';
export * from '../lib/pagination';
`;

        fs.writeFileSync(indexPath, newContent, 'utf-8');
        console.log('✓ Added pagination exports to src/api/index.ts');
      }
    },
  },
  plugins: [
    {
      name: '@hey-api/client-axios',
    },
    '@hey-api/schemas',
    {
      name: '@hey-api/transformers',
      // Treat OpenAPI format "date" as strings so we can send YYYY-MM-DD
      // and avoid timezone shifts breaking .NET DateOnly parsing.
      dates: false,
    },
    {
      enums: 'javascript',
      name: '@hey-api/typescript',
    },
    {
      name: '@hey-api/sdk',
      transformer: true,
    },
  ],
});
