// This file is auto-generated by @hey-api/openapi-ts

export const CreateOrUpdateDepartmentModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateItemAssignmentHistoryModelSchema = {
  required: ["assignedFrom", "itemId", "personId"],
  type: "object",
  properties: {
    itemId: {
      type: "string",
      format: "uuid",
    },
    personId: {
      type: "string",
      format: "uuid",
    },
    assignedFrom: {
      type: "string",
      format: "date-time",
    },
    assignedUntil: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    assignedById: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateItemModelSchema = {
  required: ["condition", "purchaseDate", "variantId"],
  type: "object",
  properties: {
    variantId: {
      type: "string",
      format: "uuid",
    },
    identifier: {
      maxLength: 255,
      type: "string",
      nullable: true,
    },
    storageLocationId: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    condition: {
      enum: ["New", "Used", "Damaged", "Destroyed", "Lost"],
      type: "string",
    },
    purchaseDate: {
      type: "string",
      format: "date-time",
    },
    retirementDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateMaintenanceModelSchema = {
  required: ["itemId", "performedAt", "typeId"],
  type: "object",
  properties: {
    itemId: {
      type: "string",
      format: "uuid",
    },
    performedAt: {
      type: "string",
      format: "date-time",
    },
    typeId: {
      type: "string",
      format: "uuid",
    },
    remarks: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    performedById: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateMaintenanceTypeModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateOrderItemModelSchema = {
  required: ["orderId", "quantity", "variantId"],
  type: "object",
  properties: {
    orderId: {
      type: "string",
      format: "uuid",
    },
    variantId: {
      type: "string",
      format: "uuid",
    },
    quantity: {
      type: "integer",
      format: "int32",
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateOrderModelSchema = {
  required: ["items", "orderDate", "status"],
  type: "object",
  properties: {
    orderIdentifier: {
      maxLength: 255,
      type: "string",
      nullable: true,
    },
    orderDate: {
      type: "string",
      format: "date-time",
    },
    status: {
      enum: ["Draft", "Submitted", "Delivered", "Completed"],
      type: "string",
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/CreateOrUpdateOrderItemModel",
      },
    },
    deliveryDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdatePersonModelSchema = {
  required: ["firstName", "lastName"],
  type: "object",
  properties: {
    firstName: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    lastName: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    remarks: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    contactInfo: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    externalId: {
      maxLength: 255,
      type: "string",
      nullable: true,
    },
    departmentIds: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateProductModelSchema = {
  required: ["manufacturer", "name", "typeId"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    manufacturer: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    typeId: {
      type: "string",
      format: "uuid",
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateProductTypeModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateStorageLocationModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    remarks: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const CreateOrUpdateVariantModelSchema = {
  required: ["name", "productId"],
  type: "object",
  properties: {
    productId: {
      type: "string",
      format: "uuid",
    },
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    additionalSpecs: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const DepartmentModelSchema = {
  required: ["id", "name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
  },
  additionalProperties: false,
} as const;

export const ItemAssignmentHistoryModelSchema = {
  required: ["assignedFrom", "id", "itemId", "person", "personId"],
  type: "object",
  properties: {
    itemId: {
      type: "string",
      format: "uuid",
    },
    personId: {
      type: "string",
      format: "uuid",
    },
    assignedFrom: {
      type: "string",
      format: "date-time",
    },
    assignedUntil: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    assignedById: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
    person: {
      $ref: "#/components/schemas/PersonModel",
    },
    assignedBy: {
      $ref: "#/components/schemas/UserModel",
    },
  },
  additionalProperties: false,
} as const;

export const ItemModelSchema = {
  required: ["condition", "id", "purchaseDate", "variant", "variantId"],
  type: "object",
  properties: {
    variantId: {
      type: "string",
      format: "uuid",
    },
    identifier: {
      maxLength: 255,
      type: "string",
      nullable: true,
    },
    storageLocationId: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    condition: {
      enum: ["New", "Used", "Damaged", "Destroyed", "Lost"],
      type: "string",
    },
    purchaseDate: {
      type: "string",
      format: "date-time",
    },
    retirementDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
    variant: {
      $ref: "#/components/schemas/VariantModel",
    },
  },
  additionalProperties: false,
} as const;

export const MaintenanceModelSchema = {
  required: ["id", "itemId", "performedAt", "type", "typeId"],
  type: "object",
  properties: {
    itemId: {
      type: "string",
      format: "uuid",
    },
    performedAt: {
      type: "string",
      format: "date-time",
    },
    typeId: {
      type: "string",
      format: "uuid",
    },
    remarks: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    performedById: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
    performedBy: {
      $ref: "#/components/schemas/UserModel",
    },
    type: {
      $ref: "#/components/schemas/MaintenanceTypeModel",
    },
  },
  additionalProperties: false,
} as const;

export const MaintenanceTypeModelSchema = {
  required: ["id", "name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
  },
  additionalProperties: false,
} as const;

export const OrderItemModelSchema = {
  required: ["id", "orderId", "quantity", "variant", "variantId"],
  type: "object",
  properties: {
    orderId: {
      type: "string",
      format: "uuid",
    },
    variantId: {
      type: "string",
      format: "uuid",
    },
    quantity: {
      type: "integer",
      format: "int32",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    variant: {
      $ref: "#/components/schemas/VariantModel",
    },
  },
  additionalProperties: false,
} as const;

export const OrderModelSchema = {
  required: ["id", "items", "orderDate", "status"],
  type: "object",
  properties: {
    orderIdentifier: {
      maxLength: 255,
      type: "string",
      nullable: true,
    },
    orderDate: {
      type: "string",
      format: "date-time",
    },
    status: {
      enum: ["Draft", "Submitted", "Delivered", "Completed"],
      type: "string",
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/OrderItemModel",
      },
    },
    deliveryDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
  },
  additionalProperties: false,
} as const;

export const PersonModelSchema = {
  required: ["departments", "firstName", "id", "lastName"],
  type: "object",
  properties: {
    firstName: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    lastName: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    remarks: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    contactInfo: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    externalId: {
      maxLength: 255,
      type: "string",
      nullable: true,
    },
    departmentIds: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
    departments: {
      type: "array",
      items: {
        $ref: "#/components/schemas/DepartmentModel",
      },
    },
  },
  additionalProperties: false,
} as const;

export const ProductModelSchema = {
  required: ["id", "manufacturer", "name", "type", "typeId"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    manufacturer: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    typeId: {
      type: "string",
      format: "uuid",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    type: {
      $ref: "#/components/schemas/ProductTypeModel",
    },
  },
  additionalProperties: false,
} as const;

export const ProductTypeModelSchema = {
  required: ["id", "name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
  },
  additionalProperties: false,
} as const;

export const StorageLocationModelSchema = {
  required: ["id", "name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    remarks: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
  },
  additionalProperties: false,
} as const;

export const UserModelSchema = {
  required: ["eMail", "id"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    eMail: {
      minLength: 1,
      type: "string",
    },
    firstName: {
      type: "string",
      nullable: true,
    },
    lastName: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const VariantModelSchema = {
  required: ["id", "name", "product", "productId"],
  type: "object",
  properties: {
    productId: {
      type: "string",
      format: "uuid",
    },
    name: {
      maxLength: 255,
      minLength: 1,
      type: "string",
    },
    additionalSpecs: {
      maxLength: 2000,
      type: "string",
      nullable: true,
    },
    id: {
      type: "string",
      format: "uuid",
    },
    product: {
      $ref: "#/components/schemas/ProductModel",
    },
  },
  additionalProperties: false,
} as const;
