// This file is auto-generated by @hey-api/openapi-ts

export const ApiIntegrationCredentialsModelSchema = {
  required: ["id", "clientId", "clientSecret", "name"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    clientId: {
      type: "string",
    },
    clientSecret: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const ApiIntegrationModelSchema = {
  required: ["id", "clientId", "name"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    clientId: {
      maxLength: 255,
      type: "string",
    },
    enabled: {
      type: "boolean",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 255,
      type: ["null", "string"],
    },
  },
} as const;

export const AppointmentModelSchema = {
  required: ["scheduledAt"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    scheduledAt: {
      type: "string",
      format: "date-time",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateApiIntegrationModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 255,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateOrUpdateAppointmentModelSchema = {
  required: ["scheduledAt"],
  type: "object",
  properties: {
    scheduledAt: {
      type: "string",
      format: "date-time",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateOrUpdateDepartmentModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateOrUpdateItemAssignmentHistoryModelSchema = {
  required: ["itemId", "assignedById", "assignedFrom"],
  type: "object",
  properties: {
    itemId: {
      type: "string",
      format: "uuid",
    },
    personId: {
      type: ["null", "string"],
      description:
        "Items can be assigned to either a person or a storage location. Only one of these must be set.",
      format: "uuid",
    },
    storageLocationId: {
      type: ["null", "string"],
      description:
        "Items can be assigned to either a person or a storage location. Only one of these must be set.",
      format: "uuid",
    },
    assignedById: {
      type: "string",
      format: "uuid",
    },
    assignedFrom: {
      type: "string",
      format: "date",
    },
    assignedUntil: {
      type: ["null", "string"],
      format: "date",
    },
  },
} as const;

export const CreateOrUpdateItemModelSchema = {
  required: ["variantId", "condition", "purchaseDate", "isDemoItem"],
  type: "object",
  properties: {
    variantId: {
      type: "string",
      format: "uuid",
    },
    identifier: {
      maxLength: 255,
      type: ["null", "string"],
    },
    condition: {
      $ref: "#/components/schemas/ItemCondition",
    },
    purchaseDate: {
      type: "string",
      format: "date",
    },
    isDemoItem: {
      type: "boolean",
    },
    retirementDate: {
      type: ["null", "string"],
      format: "date",
    },
  },
} as const;

export const CreateOrUpdateMaintenanceModelSchema = {
  required: ["itemId", "performedAt", "typeId", "performedById"],
  type: "object",
  properties: {
    itemId: {
      type: "string",
      format: "uuid",
    },
    performedAt: {
      type: "string",
      format: "date-time",
    },
    typeId: {
      type: "string",
      format: "uuid",
    },
    remarks: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    performedById: {
      type: "string",
      format: "uuid",
    },
  },
} as const;

export const CreateOrUpdateMaintenanceTypeModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateOrUpdateManufacturerModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    street: {
      maxLength: 255,
      type: ["null", "string"],
    },
    city: {
      maxLength: 255,
      type: ["null", "string"],
    },
    postalCode: {
      maxLength: 255,
      type: ["null", "string"],
    },
    houseNumber: {
      maxLength: 255,
      type: ["null", "string"],
    },
    country: {
      maxLength: 255,
      type: ["null", "string"],
    },
    website: {
      maxLength: 255,
      type: ["null", "string"],
    },
    phoneNumber: {
      maxLength: 255,
      type: ["null", "string"],
    },
    email: {
      maxLength: 255,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateOrUpdateOrderItemModelSchema = {
  required: ["orderId", "variantId", "quantity"],
  type: "object",
  properties: {
    orderId: {
      type: "string",
      format: "uuid",
    },
    variantId: {
      type: "string",
      format: "uuid",
    },
    personId: {
      type: ["null", "string"],
      format: "uuid",
    },
    quantity: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
  },
} as const;

export const CreateOrUpdateOrderModelSchema = {
  required: ["orderDate", "status"],
  type: "object",
  properties: {
    orderIdentifier: {
      maxLength: 255,
      type: ["null", "string"],
    },
    orderDate: {
      type: "string",
      format: "date",
    },
    status: {
      $ref: "#/components/schemas/OrderStatus",
    },
    deliveryDate: {
      type: ["null", "string"],
      format: "date",
    },
  },
} as const;

export const CreateOrUpdatePersonModelSchema = {
  required: ["firstName", "lastName"],
  type: "object",
  properties: {
    firstName: {
      maxLength: 255,
      type: "string",
    },
    lastName: {
      maxLength: 255,
      type: "string",
    },
    remarks: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    eMail: {
      maxLength: 255,
      type: ["null", "string"],
    },
    externalId: {
      maxLength: 255,
      type: ["null", "string"],
    },
    departmentIds: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
  },
} as const;

export const CreateOrUpdateProductModelSchema = {
  required: ["name", "manufacturerId", "typeId"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      type: "string",
    },
    manufacturerId: {
      type: "string",
      format: "uuid",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    externalIdentifier: {
      maxLength: 255,
      type: ["null", "string"],
    },
    typeId: {
      type: "string",
      format: "uuid",
    },
  },
} as const;

export const CreateOrUpdateProductTypeModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateOrUpdateStorageLocationModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      type: "string",
    },
    remarks: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateOrUpdateTenantModelSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 255,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateOrUpdateVariantModelSchema = {
  required: ["productId", "name"],
  type: "object",
  properties: {
    productId: {
      type: "string",
      format: "uuid",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    additionalSpecs: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    externalIdentifier: {
      maxLength: 255,
      type: ["null", "string"],
    },
  },
} as const;

export const CreateOrUpdateVisitItemModelSchema = {
  required: ["visitId", "productId", "quantity"],
  type: "object",
  properties: {
    visitId: {
      type: "string",
      format: "uuid",
    },
    productId: {
      type: "string",
      format: "uuid",
    },
    quantity: {
      maximum: 2147483647,
      minimum: 1,
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
  },
} as const;

export const CreateOrUpdateVisitModelSchema = {
  required: ["appointmentId", "personId"],
  type: "object",
  properties: {
    appointmentId: {
      type: "string",
      format: "uuid",
    },
    personId: {
      type: "string",
      format: "uuid",
    },
  },
} as const;

export const DepartmentModelSchema = {
  required: ["id", "createdAt", "createdById", "name"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const ItemAssignmentHistoryModelSchema = {
  required: [
    "id",
    "item",
    "createdAt",
    "createdById",
    "itemId",
    "assignedById",
    "assignedFrom",
  ],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    person: {
      oneOf: [
        {
          type: "null",
        },
        {
          description:
            "Items can be assigned to either a person or a storage location. Only one of these must be set.",
          $ref: "#/components/schemas/PersonModel",
        },
      ],
    },
    storageLocation: {
      oneOf: [
        {
          type: "null",
        },
        {
          description:
            "Items can be assigned to either a person or a storage location. Only one of these must be set.",
          $ref: "#/components/schemas/StorageLocationModel",
        },
      ],
    },
    item: {
      $ref: "#/components/schemas/ItemModel",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    itemId: {
      type: "string",
      format: "uuid",
    },
    personId: {
      type: ["null", "string"],
      description:
        "Items can be assigned to either a person or a storage location. Only one of these must be set.",
      format: "uuid",
    },
    storageLocationId: {
      type: ["null", "string"],
      description:
        "Items can be assigned to either a person or a storage location. Only one of these must be set.",
      format: "uuid",
    },
    assignedById: {
      type: "string",
      format: "uuid",
    },
    assignedFrom: {
      type: "string",
      format: "date",
    },
    assignedUntil: {
      type: ["null", "string"],
      format: "date",
    },
  },
} as const;

export const ItemConditionSchema = {
  enum: ["New", "Used", "Damaged", "Destroyed", "Lost"],
} as const;

export const ItemModelSchema = {
  required: [
    "id",
    "variant",
    "createdAt",
    "createdById",
    "variantId",
    "condition",
    "purchaseDate",
    "isDemoItem",
  ],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    variant: {
      $ref: "#/components/schemas/VariantModel",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    variantId: {
      type: "string",
      format: "uuid",
    },
    identifier: {
      maxLength: 255,
      type: ["null", "string"],
    },
    condition: {
      $ref: "#/components/schemas/ItemCondition",
    },
    purchaseDate: {
      type: "string",
      format: "date",
    },
    isDemoItem: {
      type: "boolean",
    },
    retirementDate: {
      type: ["null", "string"],
      format: "date",
    },
  },
} as const;

export const MaintenanceModelSchema = {
  required: [
    "id",
    "type",
    "createdAt",
    "createdById",
    "itemId",
    "performedAt",
    "typeId",
    "performedById",
  ],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    performedBy: {
      oneOf: [
        {
          type: "null",
        },
        {
          $ref: "#/components/schemas/UserModel",
        },
      ],
    },
    type: {
      $ref: "#/components/schemas/MaintenanceTypeModel",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    itemId: {
      type: "string",
      format: "uuid",
    },
    performedAt: {
      type: "string",
      format: "date-time",
    },
    typeId: {
      type: "string",
      format: "uuid",
    },
    remarks: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    performedById: {
      type: "string",
      format: "uuid",
    },
  },
} as const;

export const MaintenanceTypeModelSchema = {
  required: ["id", "createdAt", "createdById", "name"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const ManufacturerModelSchema = {
  required: ["id", "createdAt", "createdById", "name"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    street: {
      maxLength: 255,
      type: ["null", "string"],
    },
    city: {
      maxLength: 255,
      type: ["null", "string"],
    },
    postalCode: {
      maxLength: 255,
      type: ["null", "string"],
    },
    houseNumber: {
      maxLength: 255,
      type: ["null", "string"],
    },
    country: {
      maxLength: 255,
      type: ["null", "string"],
    },
    website: {
      maxLength: 255,
      type: ["null", "string"],
    },
    phoneNumber: {
      maxLength: 255,
      type: ["null", "string"],
    },
    email: {
      maxLength: 255,
      type: ["null", "string"],
    },
  },
} as const;

export const OrderItemModelSchema = {
  required: [
    "id",
    "variant",
    "createdAt",
    "createdById",
    "orderId",
    "variantId",
    "quantity",
  ],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    variant: {
      $ref: "#/components/schemas/VariantModel",
    },
    person: {
      oneOf: [
        {
          type: "null",
        },
        {
          $ref: "#/components/schemas/PersonModel",
        },
      ],
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    orderId: {
      type: "string",
      format: "uuid",
    },
    variantId: {
      type: "string",
      format: "uuid",
    },
    personId: {
      type: ["null", "string"],
      format: "uuid",
    },
    quantity: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
  },
} as const;

export const OrderModelSchema = {
  required: ["id", "createdAt", "createdById", "orderDate", "status"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    orderIdentifier: {
      maxLength: 255,
      type: ["null", "string"],
    },
    orderDate: {
      type: "string",
      format: "date",
    },
    status: {
      $ref: "#/components/schemas/OrderStatus",
    },
    deliveryDate: {
      type: ["null", "string"],
      format: "date",
    },
  },
} as const;

export const OrderStatusSchema = {
  enum: ["Draft", "Submitted", "Delivered", "Completed"],
} as const;

export const PersonModelSchema = {
  required: [
    "id",
    "departments",
    "createdAt",
    "createdById",
    "firstName",
    "lastName",
  ],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    departments: {
      type: "array",
      items: {
        $ref: "#/components/schemas/DepartmentModel",
      },
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    firstName: {
      maxLength: 255,
      type: "string",
    },
    lastName: {
      maxLength: 255,
      type: "string",
    },
    remarks: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    eMail: {
      maxLength: 255,
      type: ["null", "string"],
    },
    externalId: {
      maxLength: 255,
      type: ["null", "string"],
    },
    departmentIds: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
  },
} as const;

export const ProblemDetailsSchema = {
  type: "object",
  properties: {
    type: {
      type: ["null", "string"],
    },
    title: {
      type: ["null", "string"],
    },
    status: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["null", "integer", "string"],
      format: "int32",
    },
    detail: {
      type: ["null", "string"],
    },
    instance: {
      type: ["null", "string"],
    },
  },
} as const;

export const ProductModelSchema = {
  required: [
    "id",
    "type",
    "manufacturer",
    "createdAt",
    "createdById",
    "name",
    "manufacturerId",
    "typeId",
  ],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    type: {
      $ref: "#/components/schemas/ProductTypeModel",
    },
    manufacturer: {
      $ref: "#/components/schemas/ManufacturerModel",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    manufacturerId: {
      type: "string",
      format: "uuid",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    externalIdentifier: {
      maxLength: 255,
      type: ["null", "string"],
    },
    typeId: {
      type: "string",
      format: "uuid",
    },
  },
} as const;

export const ProductTypeModelSchema = {
  required: ["id", "createdAt", "createdById", "name"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const StorageLocationModelSchema = {
  required: ["id", "createdAt", "createdById", "name"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    remarks: {
      maxLength: 2000,
      type: ["null", "string"],
    },
  },
} as const;

export const TenantModelSchema = {
  required: ["id", "createdAt", "createdById", "name"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    description: {
      maxLength: 255,
      type: ["null", "string"],
    },
  },
} as const;

export const UserModelSchema = {
  required: ["id", "eMail"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    eMail: {
      type: "string",
    },
    firstName: {
      type: ["null", "string"],
    },
    lastName: {
      type: ["null", "string"],
    },
  },
} as const;

export const VariantModelSchema = {
  required: ["id", "product", "createdAt", "createdById", "productId", "name"],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    product: {
      $ref: "#/components/schemas/ProductModel",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    productId: {
      type: "string",
      format: "uuid",
    },
    name: {
      maxLength: 255,
      type: "string",
    },
    additionalSpecs: {
      maxLength: 2000,
      type: ["null", "string"],
    },
    externalIdentifier: {
      maxLength: 255,
      type: ["null", "string"],
    },
  },
} as const;

export const VisitItemModelSchema = {
  required: [
    "id",
    "product",
    "createdAt",
    "createdById",
    "visitId",
    "productId",
    "quantity",
  ],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    product: {
      $ref: "#/components/schemas/ProductModel",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    visitId: {
      type: "string",
      format: "uuid",
    },
    productId: {
      type: "string",
      format: "uuid",
    },
    quantity: {
      maximum: 2147483647,
      minimum: 1,
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
  },
} as const;

export const VisitModelSchema = {
  required: [
    "id",
    "appointment",
    "person",
    "createdAt",
    "createdById",
    "appointmentId",
    "personId",
  ],
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    appointment: {
      $ref: "#/components/schemas/AppointmentModel",
    },
    person: {
      $ref: "#/components/schemas/PersonModel",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    createdById: {
      type: "string",
      format: "uuid",
    },
    modifiedAt: {
      type: ["null", "string"],
      format: "date-time",
    },
    modifiedById: {
      type: ["null", "string"],
      format: "uuid",
    },
    appointmentId: {
      type: "string",
      format: "uuid",
    },
    personId: {
      type: "string",
      format: "uuid",
    },
  },
} as const;
