// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import {
  getAssignmentsByIdResponseTransformer,
  getAssignmentsResponseTransformer,
  getItemsByIdAssignmentsResponseTransformer,
  getItemsByIdMaintenanceResponseTransformer,
  getItemsByIdResponseTransformer,
  getItemsResponseTransformer,
  getMaintenancesByIdResponseTransformer,
  getMaintenancesResponseTransformer,
  getOrdersByIdResponseTransformer,
  getOrdersResponseTransformer,
  getStorageLocationsByIdItemsResponseTransformer,
  getVariantsByIdItemsResponseTransformer,
  postAssignmentsResponseTransformer,
  postItemsResponseTransformer,
  postMaintenancesResponseTransformer,
  postOrdersResponseTransformer,
} from "./transformers.gen";
import type {
  DeleteAssignmentsByIdData,
  DeleteAssignmentsByIdErrors,
  DeleteAssignmentsByIdResponses,
  DeleteDepartmentsByIdData,
  DeleteDepartmentsByIdErrors,
  DeleteDepartmentsByIdResponses,
  DeleteItemsByIdData,
  DeleteItemsByIdErrors,
  DeleteItemsByIdResponses,
  DeleteMaintenancesByIdData,
  DeleteMaintenancesByIdErrors,
  DeleteMaintenancesByIdResponses,
  DeleteMaintenanceTypesByIdData,
  DeleteMaintenanceTypesByIdErrors,
  DeleteMaintenanceTypesByIdResponses,
  DeleteOrdersByIdData,
  DeleteOrdersByIdErrors,
  DeleteOrdersByIdResponses,
  DeletePersonsByIdData,
  DeletePersonsByIdErrors,
  DeletePersonsByIdResponses,
  DeleteProductsByIdData,
  DeleteProductsByIdErrors,
  DeleteProductsByIdResponses,
  DeleteProductTypesByIdData,
  DeleteProductTypesByIdErrors,
  DeleteProductTypesByIdResponses,
  DeleteStorageLocationsByIdData,
  DeleteStorageLocationsByIdErrors,
  DeleteStorageLocationsByIdResponses,
  DeleteVariantsByIdData,
  DeleteVariantsByIdErrors,
  DeleteVariantsByIdResponses,
  GetAssignmentsByIdData,
  GetAssignmentsByIdErrors,
  GetAssignmentsByIdResponses,
  GetAssignmentsData,
  GetAssignmentsErrors,
  GetAssignmentsResponses,
  GetDepartmentsByIdData,
  GetDepartmentsByIdErrors,
  GetDepartmentsByIdPersonsData,
  GetDepartmentsByIdPersonsErrors,
  GetDepartmentsByIdPersonsResponses,
  GetDepartmentsByIdResponses,
  GetDepartmentsData,
  GetDepartmentsErrors,
  GetDepartmentsResponses,
  GetItemsByIdAssignmentsData,
  GetItemsByIdAssignmentsErrors,
  GetItemsByIdAssignmentsResponses,
  GetItemsByIdData,
  GetItemsByIdErrors,
  GetItemsByIdMaintenanceData,
  GetItemsByIdMaintenanceErrors,
  GetItemsByIdMaintenanceResponses,
  GetItemsByIdResponses,
  GetItemsData,
  GetItemsErrors,
  GetItemsResponses,
  GetMaintenancesByIdData,
  GetMaintenancesByIdErrors,
  GetMaintenancesByIdResponses,
  GetMaintenancesData,
  GetMaintenancesErrors,
  GetMaintenancesResponses,
  GetMaintenanceTypesByIdData,
  GetMaintenanceTypesByIdErrors,
  GetMaintenanceTypesByIdResponses,
  GetMaintenanceTypesData,
  GetMaintenanceTypesErrors,
  GetMaintenanceTypesResponses,
  GetOrdersByIdData,
  GetOrdersByIdErrors,
  GetOrdersByIdResponses,
  GetOrdersData,
  GetOrdersErrors,
  GetOrdersResponses,
  GetPersonsByIdData,
  GetPersonsByIdErrors,
  GetPersonsByIdResponses,
  GetPersonsData,
  GetPersonsErrors,
  GetPersonsResponses,
  GetProductsByIdData,
  GetProductsByIdErrors,
  GetProductsByIdResponses,
  GetProductsData,
  GetProductsErrors,
  GetProductsResponses,
  GetProductTypesByIdData,
  GetProductTypesByIdErrors,
  GetProductTypesByIdResponses,
  GetProductTypesData,
  GetProductTypesErrors,
  GetProductTypesResponses,
  GetStorageLocationsByIdData,
  GetStorageLocationsByIdErrors,
  GetStorageLocationsByIdItemsData,
  GetStorageLocationsByIdItemsErrors,
  GetStorageLocationsByIdItemsResponses,
  GetStorageLocationsByIdResponses,
  GetStorageLocationsData,
  GetStorageLocationsErrors,
  GetStorageLocationsResponses,
  GetUsersByIdData,
  GetUsersByIdErrors,
  GetUsersByIdResponses,
  GetUsersData,
  GetUsersErrors,
  GetUsersResponses,
  GetVariantsByIdData,
  GetVariantsByIdErrors,
  GetVariantsByIdItemsData,
  GetVariantsByIdItemsErrors,
  GetVariantsByIdItemsResponses,
  GetVariantsByIdResponses,
  GetVariantsData,
  GetVariantsErrors,
  GetVariantsResponses,
  PostAssignmentsData,
  PostAssignmentsErrors,
  PostAssignmentsResponses,
  PostDepartmentsData,
  PostDepartmentsErrors,
  PostDepartmentsResponses,
  PostItemsData,
  PostItemsErrors,
  PostItemsResponses,
  PostMaintenancesData,
  PostMaintenancesErrors,
  PostMaintenancesResponses,
  PostMaintenanceTypesData,
  PostMaintenanceTypesErrors,
  PostMaintenanceTypesResponses,
  PostOrdersData,
  PostOrdersErrors,
  PostOrdersResponses,
  PostPersonsData,
  PostPersonsErrors,
  PostPersonsResponses,
  PostProductsData,
  PostProductsErrors,
  PostProductsResponses,
  PostProductTypesData,
  PostProductTypesErrors,
  PostProductTypesResponses,
  PostStorageLocationsData,
  PostStorageLocationsErrors,
  PostStorageLocationsResponses,
  PostVariantsData,
  PostVariantsErrors,
  PostVariantsResponses,
  PutAssignmentsByIdData,
  PutAssignmentsByIdErrors,
  PutAssignmentsByIdResponses,
  PutDepartmentsByIdData,
  PutDepartmentsByIdErrors,
  PutDepartmentsByIdResponses,
  PutItemsByIdData,
  PutItemsByIdErrors,
  PutItemsByIdResponses,
  PutMaintenancesByIdData,
  PutMaintenancesByIdErrors,
  PutMaintenancesByIdResponses,
  PutMaintenanceTypesByIdData,
  PutMaintenanceTypesByIdErrors,
  PutMaintenanceTypesByIdResponses,
  PutOrdersByIdData,
  PutOrdersByIdErrors,
  PutOrdersByIdResponses,
  PutPersonsByIdData,
  PutPersonsByIdErrors,
  PutPersonsByIdResponses,
  PutProductsByIdData,
  PutProductsByIdErrors,
  PutProductsByIdResponses,
  PutProductTypesByIdData,
  PutProductTypesByIdErrors,
  PutProductTypesByIdResponses,
  PutStorageLocationsByIdData,
  PutStorageLocationsByIdErrors,
  PutStorageLocationsByIdResponses,
  PutVariantsByIdData,
  PutVariantsByIdErrors,
  PutVariantsByIdResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List all departments
 *
 * Returns a list of all departments.
 */
export const getDepartments = <ThrowOnError extends boolean = false>(
  options?: Options<GetDepartmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetDepartmentsResponses,
    GetDepartmentsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments",
    ...options,
  });
};

/**
 * Create a new department
 *
 * Creates a new department.
 */
export const postDepartments = <ThrowOnError extends boolean = false>(
  options?: Options<PostDepartmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostDepartmentsResponses,
    PostDepartmentsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a department
 *
 * Deletes a department by its unique ID.
 */
export const deleteDepartmentsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDepartmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDepartmentsByIdResponses,
    DeleteDepartmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments/{id}",
    ...options,
  });
};

/**
 * Get department by ID
 *
 * Returns a department by its unique ID.
 */
export const getDepartmentsById = <ThrowOnError extends boolean = false>(
  options: Options<GetDepartmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetDepartmentsByIdResponses,
    GetDepartmentsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments/{id}",
    ...options,
  });
};

/**
 * Update a department
 *
 * Updates an existing department.
 */
export const putDepartmentsById = <ThrowOnError extends boolean = false>(
  options: Options<PutDepartmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutDepartmentsByIdResponses,
    PutDepartmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all persons in a department
 *
 * Returns all persons that are members of the given department.
 */
export const getDepartmentsByIdPersons = <ThrowOnError extends boolean = false>(
  options: Options<GetDepartmentsByIdPersonsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetDepartmentsByIdPersonsResponses,
    GetDepartmentsByIdPersonsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments/{id}/persons",
    ...options,
  });
};

/**
 * List all item assignments
 *
 * Returns a list of all item assignment histories.
 */
export const getAssignments = <ThrowOnError extends boolean = false>(
  options?: Options<GetAssignmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAssignmentsResponses,
    GetAssignmentsErrors,
    ThrowOnError
  >({
    responseTransformer: getAssignmentsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments",
    ...options,
  });
};

/**
 * Create a new assignment
 *
 * Creates a new item assignment history.
 */
export const postAssignments = <ThrowOnError extends boolean = false>(
  options?: Options<PostAssignmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostAssignmentsResponses,
    PostAssignmentsErrors,
    ThrowOnError
  >({
    responseTransformer: postAssignmentsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete an assignment
 *
 * Deletes a item assignment history by its unique ID.
 */
export const deleteAssignmentsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAssignmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteAssignmentsByIdResponses,
    DeleteAssignmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments/{id}",
    ...options,
  });
};

/**
 * Get assignment by ID
 *
 * Returns a item assignment history by its unique ID.
 */
export const getAssignmentsById = <ThrowOnError extends boolean = false>(
  options: Options<GetAssignmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAssignmentsByIdResponses,
    GetAssignmentsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getAssignmentsByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments/{id}",
    ...options,
  });
};

/**
 * Update an assignment
 *
 * Updates an existing item assignment history.
 */
export const putAssignmentsById = <ThrowOnError extends boolean = false>(
  options: Options<PutAssignmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutAssignmentsByIdResponses,
    PutAssignmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all items
 *
 * Returns a list of all items.
 */
export const getItems = <ThrowOnError extends boolean = false>(
  options?: Options<GetItemsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsResponses,
    GetItemsErrors,
    ThrowOnError
  >({
    responseTransformer: getItemsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items",
    ...options,
  });
};

/**
 * Create a new item
 *
 * Creates a new item.
 */
export const postItems = <ThrowOnError extends boolean = false>(
  options?: Options<PostItemsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostItemsResponses,
    PostItemsErrors,
    ThrowOnError
  >({
    responseTransformer: postItemsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a item
 *
 * Deletes a item by its unique ID.
 */
export const deleteItemsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemsByIdResponses,
    DeleteItemsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}",
    ...options,
  });
};

/**
 * Get item by ID
 *
 * Returns a item by its unique ID.
 */
export const getItemsById = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemsByIdResponses,
    GetItemsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getItemsByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}",
    ...options,
  });
};

/**
 * Update a item
 *
 * Updates an existing item.
 */
export const putItemsById = <ThrowOnError extends boolean = false>(
  options: Options<PutItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemsByIdResponses,
    PutItemsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all assignments for a item
 *
 * Returns all assignment histories for a specific item.
 */
export const getItemsByIdAssignments = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsByIdAssignmentsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemsByIdAssignmentsResponses,
    GetItemsByIdAssignmentsErrors,
    ThrowOnError
  >({
    responseTransformer: getItemsByIdAssignmentsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}/assignments",
    ...options,
  });
};

/**
 * List all maintenances for a item
 *
 * Returns all maintenance records for a specific item.
 */
export const getItemsByIdMaintenance = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsByIdMaintenanceData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemsByIdMaintenanceResponses,
    GetItemsByIdMaintenanceErrors,
    ThrowOnError
  >({
    responseTransformer: getItemsByIdMaintenanceResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}/maintenance",
    ...options,
  });
};

/**
 * List all maintenances
 *
 * Returns a list of all maintenance records.
 */
export const getMaintenances = <ThrowOnError extends boolean = false>(
  options?: Options<GetMaintenancesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetMaintenancesResponses,
    GetMaintenancesErrors,
    ThrowOnError
  >({
    responseTransformer: getMaintenancesResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances",
    ...options,
  });
};

/**
 * Create a new maintenance
 *
 * Creates a new maintenance record.
 */
export const postMaintenances = <ThrowOnError extends boolean = false>(
  options?: Options<PostMaintenancesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostMaintenancesResponses,
    PostMaintenancesErrors,
    ThrowOnError
  >({
    responseTransformer: postMaintenancesResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a maintenance
 *
 * Deletes a maintenance record by its unique ID.
 */
export const deleteMaintenancesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteMaintenancesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteMaintenancesByIdResponses,
    DeleteMaintenancesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances/{id}",
    ...options,
  });
};

/**
 * Get maintenance by ID
 *
 * Returns a maintenance record by its unique ID.
 */
export const getMaintenancesById = <ThrowOnError extends boolean = false>(
  options: Options<GetMaintenancesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetMaintenancesByIdResponses,
    GetMaintenancesByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getMaintenancesByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances/{id}",
    ...options,
  });
};

/**
 * Update a maintenance
 *
 * Updates an existing maintenance record.
 */
export const putMaintenancesById = <ThrowOnError extends boolean = false>(
  options: Options<PutMaintenancesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutMaintenancesByIdResponses,
    PutMaintenancesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all maintenanceTypes
 *
 * Returns a list of all maintenanceTypes.
 */
export const getMaintenanceTypes = <ThrowOnError extends boolean = false>(
  options?: Options<GetMaintenanceTypesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetMaintenanceTypesResponses,
    GetMaintenanceTypesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenanceTypes",
    ...options,
  });
};

/**
 * Create a new maintenanceType
 *
 * Creates a new maintenanceType.
 */
export const postMaintenanceTypes = <ThrowOnError extends boolean = false>(
  options?: Options<PostMaintenanceTypesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostMaintenanceTypesResponses,
    PostMaintenanceTypesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenanceTypes",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a maintenanceType
 *
 * Deletes a maintenanceType by its unique ID.
 */
export const deleteMaintenanceTypesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteMaintenanceTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteMaintenanceTypesByIdResponses,
    DeleteMaintenanceTypesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenanceTypes/{id}",
    ...options,
  });
};

/**
 * Get maintenanceType by ID
 *
 * Returns a maintenanceType by its unique ID.
 */
export const getMaintenanceTypesById = <ThrowOnError extends boolean = false>(
  options: Options<GetMaintenanceTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetMaintenanceTypesByIdResponses,
    GetMaintenanceTypesByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenanceTypes/{id}",
    ...options,
  });
};

/**
 * Update a maintenanceType
 *
 * Updates an existing maintenanceType.
 */
export const putMaintenanceTypesById = <ThrowOnError extends boolean = false>(
  options: Options<PutMaintenanceTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutMaintenanceTypesByIdResponses,
    PutMaintenanceTypesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenanceTypes/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all orders
 *
 * Returns a list of all orders.
 */
export const getOrders = <ThrowOnError extends boolean = false>(
  options?: Options<GetOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetOrdersResponses,
    GetOrdersErrors,
    ThrowOnError
  >({
    responseTransformer: getOrdersResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders",
    ...options,
  });
};

/**
 * Create a new order
 *
 * Creates a new order.
 */
export const postOrders = <ThrowOnError extends boolean = false>(
  options?: Options<PostOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostOrdersResponses,
    PostOrdersErrors,
    ThrowOnError
  >({
    responseTransformer: postOrdersResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete an order
 *
 * Deletes an order by its unique ID.
 */
export const deleteOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOrdersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteOrdersByIdResponses,
    DeleteOrdersByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{id}",
    ...options,
  });
};

/**
 * Get order by ID
 *
 * Returns an order by its unique ID.
 */
export const getOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<GetOrdersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetOrdersByIdResponses,
    GetOrdersByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getOrdersByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{id}",
    ...options,
  });
};

/**
 * Update an order
 *
 * Updates an existing order.
 */
export const putOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<PutOrdersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutOrdersByIdResponses,
    PutOrdersByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all persons
 *
 * Returns a list of all persons.
 */
export const getPersons = <ThrowOnError extends boolean = false>(
  options?: Options<GetPersonsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPersonsResponses,
    GetPersonsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons",
    ...options,
  });
};

/**
 * Create a new person
 *
 * Creates a new person entry.
 */
export const postPersons = <ThrowOnError extends boolean = false>(
  options?: Options<PostPersonsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostPersonsResponses,
    PostPersonsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a person
 *
 * Deletes a person by ID.
 */
export const deletePersonsById = <ThrowOnError extends boolean = false>(
  options: Options<DeletePersonsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeletePersonsByIdResponses,
    DeletePersonsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons/{id}",
    ...options,
  });
};

/**
 * Get person by ID
 *
 * Returns a single person by their unique ID.
 */
export const getPersonsById = <ThrowOnError extends boolean = false>(
  options: Options<GetPersonsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPersonsByIdResponses,
    GetPersonsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons/{id}",
    ...options,
  });
};

/**
 * Update a person
 *
 * Updates an existing person.
 */
export const putPersonsById = <ThrowOnError extends boolean = false>(
  options: Options<PutPersonsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutPersonsByIdResponses,
    PutPersonsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all products
 *
 * Returns a list of all products.
 */
export const getProducts = <ThrowOnError extends boolean = false>(
  options?: Options<GetProductsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetProductsResponses,
    GetProductsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products",
    ...options,
  });
};

/**
 * Create a new product
 *
 * Creates a new product.
 */
export const postProducts = <ThrowOnError extends boolean = false>(
  options?: Options<PostProductsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostProductsResponses,
    PostProductsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a product
 *
 * Deletes a product by its unique ID.
 */
export const deleteProductsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProductsByIdResponses,
    DeleteProductsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{id}",
    ...options,
  });
};

/**
 * Get product by ID
 *
 * Returns a product by its unique ID.
 */
export const getProductsById = <ThrowOnError extends boolean = false>(
  options: Options<GetProductsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProductsByIdResponses,
    GetProductsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{id}",
    ...options,
  });
};

/**
 * Update a product
 *
 * Updates an existing product.
 */
export const putProductsById = <ThrowOnError extends boolean = false>(
  options: Options<PutProductsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutProductsByIdResponses,
    PutProductsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all productTypes
 *
 * Returns a list of all productTypes.
 */
export const getProductTypes = <ThrowOnError extends boolean = false>(
  options?: Options<GetProductTypesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetProductTypesResponses,
    GetProductTypesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/productTypes",
    ...options,
  });
};

/**
 * Create a new productType
 *
 * Creates a new productType.
 */
export const postProductTypes = <ThrowOnError extends boolean = false>(
  options?: Options<PostProductTypesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostProductTypesResponses,
    PostProductTypesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/productTypes",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a productType
 *
 * Deletes a productType by its unique ID.
 */
export const deleteProductTypesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProductTypesByIdResponses,
    DeleteProductTypesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/productTypes/{id}",
    ...options,
  });
};

/**
 * Get productType by ID
 *
 * Returns a productType by its unique ID.
 */
export const getProductTypesById = <ThrowOnError extends boolean = false>(
  options: Options<GetProductTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProductTypesByIdResponses,
    GetProductTypesByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/productTypes/{id}",
    ...options,
  });
};

/**
 * Update a productType
 *
 * Updates an existing productType.
 */
export const putProductTypesById = <ThrowOnError extends boolean = false>(
  options: Options<PutProductTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutProductTypesByIdResponses,
    PutProductTypesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/productTypes/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all storage locations
 *
 * Returns a list of all storage locations.
 */
export const getStorageLocations = <ThrowOnError extends boolean = false>(
  options?: Options<GetStorageLocationsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetStorageLocationsResponses,
    GetStorageLocationsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storageLocations",
    ...options,
  });
};

/**
 * Create a new storage location
 *
 * Creates a new storage location.
 */
export const postStorageLocations = <ThrowOnError extends boolean = false>(
  options?: Options<PostStorageLocationsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostStorageLocationsResponses,
    PostStorageLocationsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storageLocations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a storage location
 *
 * Deletes a storage location by its unique ID.
 */
export const deleteStorageLocationsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteStorageLocationsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteStorageLocationsByIdResponses,
    DeleteStorageLocationsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storageLocations/{id}",
    ...options,
  });
};

/**
 * Get storage location by ID
 *
 * Returns a storage location by its unique ID.
 */
export const getStorageLocationsById = <ThrowOnError extends boolean = false>(
  options: Options<GetStorageLocationsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetStorageLocationsByIdResponses,
    GetStorageLocationsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storageLocations/{id}",
    ...options,
  });
};

/**
 * Update a storage location
 *
 * Updates an existing storage location.
 */
export const putStorageLocationsById = <ThrowOnError extends boolean = false>(
  options: Options<PutStorageLocationsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutStorageLocationsByIdResponses,
    PutStorageLocationsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storageLocations/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all items for a storage location
 *
 * Returns all items assigned to a storage location.
 */
export const getStorageLocationsByIdItems = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetStorageLocationsByIdItemsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetStorageLocationsByIdItemsResponses,
    GetStorageLocationsByIdItemsErrors,
    ThrowOnError
  >({
    responseTransformer: getStorageLocationsByIdItemsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storageLocations/{id}/items",
    ...options,
  });
};

export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUsersResponses,
    GetUsersErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users",
    ...options,
  });
};

/**
 * Get user by ID
 *
 * Returns a user by its unique ID.
 */
export const getUsersById = <ThrowOnError extends boolean = false>(
  options: Options<GetUsersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetUsersByIdResponses,
    GetUsersByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * List all variants
 *
 * Returns a list of all variants.
 */
export const getVariants = <ThrowOnError extends boolean = false>(
  options?: Options<GetVariantsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetVariantsResponses,
    GetVariantsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants",
    ...options,
  });
};

/**
 * Create a new variant
 *
 * Creates a new variant.
 */
export const postVariants = <ThrowOnError extends boolean = false>(
  options?: Options<PostVariantsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostVariantsResponses,
    PostVariantsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a variant
 *
 * Deletes a variant by its unique ID.
 */
export const deleteVariantsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVariantsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteVariantsByIdResponses,
    DeleteVariantsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants/{id}",
    ...options,
  });
};

/**
 * Get variant by ID
 *
 * Returns a variant by its unique ID.
 */
export const getVariantsById = <ThrowOnError extends boolean = false>(
  options: Options<GetVariantsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetVariantsByIdResponses,
    GetVariantsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants/{id}",
    ...options,
  });
};

/**
 * Update a variant
 *
 * Updates an existing variant.
 */
export const putVariantsById = <ThrowOnError extends boolean = false>(
  options: Options<PutVariantsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutVariantsByIdResponses,
    PutVariantsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all items for a variant
 *
 * Returns all items for a specific variant.
 */
export const getVariantsByIdItems = <ThrowOnError extends boolean = false>(
  options: Options<GetVariantsByIdItemsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetVariantsByIdItemsResponses,
    GetVariantsByIdItemsErrors,
    ThrowOnError
  >({
    responseTransformer: getVariantsByIdItemsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants/{id}/items",
    ...options,
  });
};
