// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import {
  getAppointmentsByIdResponseTransformer,
  getAppointmentsByIdVisitsResponseTransformer,
  getAppointmentsResponseTransformer,
  getAssignmentsByIdResponseTransformer,
  getAssignmentsResponseTransformer,
  getItemsByIdAssignmentsResponseTransformer,
  getItemsByIdMaintenanceResponseTransformer,
  getItemsByIdResponseTransformer,
  getItemsResponseTransformer,
  getMaintenancesByIdResponseTransformer,
  getMaintenancesResponseTransformer,
  getOrdersByIdResponseTransformer,
  getOrdersResponseTransformer,
  getPersonsByIdItemsResponseTransformer,
  getStorageLocationsByIdItemsResponseTransformer,
  getTenantsByIdResponseTransformer,
  getTenantsResponseTransformer,
  getVariantsByIdItemsResponseTransformer,
  getVisitsByIdResponseTransformer,
  getVisitsResponseTransformer,
  postAppointmentsResponseTransformer,
  postAssignmentsResponseTransformer,
  postItemsResponseTransformer,
  postMaintenancesResponseTransformer,
  postOrdersResponseTransformer,
  postTenantsResponseTransformer,
  postVisitsResponseTransformer,
} from "./transformers.gen";
import type {
  DeleteApiIntegrationsByClientIdData,
  DeleteApiIntegrationsByClientIdErrors,
  DeleteApiIntegrationsByClientIdResponses,
  DeleteAppointmentsByIdData,
  DeleteAppointmentsByIdErrors,
  DeleteAppointmentsByIdResponses,
  DeleteAssignmentsByIdData,
  DeleteAssignmentsByIdErrors,
  DeleteAssignmentsByIdResponses,
  DeleteDepartmentsByIdData,
  DeleteDepartmentsByIdErrors,
  DeleteDepartmentsByIdResponses,
  DeleteItemsByIdData,
  DeleteItemsByIdErrors,
  DeleteItemsByIdResponses,
  DeleteMaintenancesByIdData,
  DeleteMaintenancesByIdErrors,
  DeleteMaintenancesByIdResponses,
  DeleteMaintenanceTypesByIdData,
  DeleteMaintenanceTypesByIdErrors,
  DeleteMaintenanceTypesByIdResponses,
  DeleteManufacturersByIdData,
  DeleteManufacturersByIdErrors,
  DeleteManufacturersByIdResponses,
  DeleteOrderItemsByIdData,
  DeleteOrderItemsByIdErrors,
  DeleteOrderItemsByIdResponses,
  DeleteOrdersByIdData,
  DeleteOrdersByIdErrors,
  DeleteOrdersByIdResponses,
  DeletePersonsByIdData,
  DeletePersonsByIdErrors,
  DeletePersonsByIdResponses,
  DeleteProductsByIdData,
  DeleteProductsByIdErrors,
  DeleteProductsByIdResponses,
  DeleteProductTypesByIdData,
  DeleteProductTypesByIdErrors,
  DeleteProductTypesByIdResponses,
  DeleteStorageLocationsByIdData,
  DeleteStorageLocationsByIdErrors,
  DeleteStorageLocationsByIdResponses,
  DeleteTenantsByIdData,
  DeleteTenantsByIdErrors,
  DeleteTenantsByIdResponses,
  DeleteVariantsByIdData,
  DeleteVariantsByIdErrors,
  DeleteVariantsByIdResponses,
  DeleteVisitItemsByIdData,
  DeleteVisitItemsByIdErrors,
  DeleteVisitItemsByIdResponses,
  DeleteVisitsByIdData,
  DeleteVisitsByIdErrors,
  DeleteVisitsByIdResponses,
  GetApiIntegrationsData,
  GetApiIntegrationsResponses,
  GetAppointmentsByIdData,
  GetAppointmentsByIdErrors,
  GetAppointmentsByIdResponses,
  GetAppointmentsByIdVisitsData,
  GetAppointmentsByIdVisitsErrors,
  GetAppointmentsByIdVisitsResponses,
  GetAppointmentsData,
  GetAppointmentsResponses,
  GetAssignmentsByIdData,
  GetAssignmentsByIdErrors,
  GetAssignmentsByIdResponses,
  GetAssignmentsData,
  GetAssignmentsResponses,
  GetDepartmentsByIdData,
  GetDepartmentsByIdErrors,
  GetDepartmentsByIdPersonsData,
  GetDepartmentsByIdPersonsErrors,
  GetDepartmentsByIdPersonsResponses,
  GetDepartmentsByIdResponses,
  GetDepartmentsData,
  GetDepartmentsResponses,
  GetItemsByIdAssignmentsData,
  GetItemsByIdAssignmentsErrors,
  GetItemsByIdAssignmentsResponses,
  GetItemsByIdData,
  GetItemsByIdErrors,
  GetItemsByIdMaintenanceData,
  GetItemsByIdMaintenanceErrors,
  GetItemsByIdMaintenanceResponses,
  GetItemsByIdResponses,
  GetItemsData,
  GetItemsResponses,
  GetMaintenancesByIdData,
  GetMaintenancesByIdErrors,
  GetMaintenancesByIdResponses,
  GetMaintenancesData,
  GetMaintenancesResponses,
  GetMaintenanceTypesByIdData,
  GetMaintenanceTypesByIdErrors,
  GetMaintenanceTypesByIdResponses,
  GetMaintenanceTypesData,
  GetMaintenanceTypesResponses,
  GetManufacturersByIdData,
  GetManufacturersByIdErrors,
  GetManufacturersByIdProductsData,
  GetManufacturersByIdProductsErrors,
  GetManufacturersByIdProductsResponses,
  GetManufacturersByIdResponses,
  GetManufacturersData,
  GetManufacturersResponses,
  GetOrderItemsByIdData,
  GetOrderItemsByIdErrors,
  GetOrderItemsByIdResponses,
  GetOrderItemsByOrderByOrderIdData,
  GetOrderItemsByOrderByOrderIdResponses,
  GetOrderItemsData,
  GetOrderItemsResponses,
  GetOrdersByIdData,
  GetOrdersByIdErrors,
  GetOrdersByIdResponses,
  GetOrdersData,
  GetOrdersResponses,
  GetPersonsByIdData,
  GetPersonsByIdErrors,
  GetPersonsByIdItemsData,
  GetPersonsByIdItemsErrors,
  GetPersonsByIdItemsResponses,
  GetPersonsByIdResponses,
  GetPersonsData,
  GetPersonsResponses,
  GetProductsByIdData,
  GetProductsByIdErrors,
  GetProductsByIdResponses,
  GetProductsByIdVariantsData,
  GetProductsByIdVariantsErrors,
  GetProductsByIdVariantsResponses,
  GetProductsData,
  GetProductsResponses,
  GetProductTypesByIdData,
  GetProductTypesByIdErrors,
  GetProductTypesByIdResponses,
  GetProductTypesData,
  GetProductTypesResponses,
  GetStorageLocationsByIdData,
  GetStorageLocationsByIdErrors,
  GetStorageLocationsByIdItemsData,
  GetStorageLocationsByIdItemsErrors,
  GetStorageLocationsByIdItemsResponses,
  GetStorageLocationsByIdResponses,
  GetStorageLocationsData,
  GetStorageLocationsResponses,
  GetTenantsByIdData,
  GetTenantsByIdErrors,
  GetTenantsByIdResponses,
  GetTenantsData,
  GetTenantsResponses,
  GetUsersByIdData,
  GetUsersByIdErrors,
  GetUsersByIdResponses,
  GetUsersData,
  GetUsersResponses,
  GetVariantsByIdData,
  GetVariantsByIdErrors,
  GetVariantsByIdItemsData,
  GetVariantsByIdItemsErrors,
  GetVariantsByIdItemsResponses,
  GetVariantsByIdResponses,
  GetVariantsData,
  GetVariantsResponses,
  GetVisitItemsByIdData,
  GetVisitItemsByIdErrors,
  GetVisitItemsByIdResponses,
  GetVisitItemsByVisitByVisitIdData,
  GetVisitItemsByVisitByVisitIdResponses,
  GetVisitItemsData,
  GetVisitItemsResponses,
  GetVisitsByIdData,
  GetVisitsByIdErrors,
  GetVisitsByIdItemsData,
  GetVisitsByIdItemsErrors,
  GetVisitsByIdItemsResponses,
  GetVisitsByIdResponses,
  GetVisitsData,
  GetVisitsResponses,
  PostApiIntegrationsData,
  PostApiIntegrationsErrors,
  PostApiIntegrationsResponses,
  PostAppointmentsData,
  PostAppointmentsResponses,
  PostAssignmentsData,
  PostAssignmentsErrors,
  PostAssignmentsResponses,
  PostDepartmentsData,
  PostDepartmentsResponses,
  PostItemsData,
  PostItemsErrors,
  PostItemsResponses,
  PostMaintenancesData,
  PostMaintenancesErrors,
  PostMaintenancesResponses,
  PostMaintenanceTypesData,
  PostMaintenanceTypesResponses,
  PostManufacturersData,
  PostManufacturersResponses,
  PostOrderItemsData,
  PostOrderItemsResponses,
  PostOrdersData,
  PostOrdersResponses,
  PostPersonsData,
  PostPersonsErrors,
  PostPersonsResponses,
  PostProductsData,
  PostProductsErrors,
  PostProductsResponses,
  PostProductTypesData,
  PostProductTypesResponses,
  PostStorageLocationsData,
  PostStorageLocationsErrors,
  PostStorageLocationsResponses,
  PostTenantsData,
  PostTenantsErrors,
  PostTenantsResponses,
  PostVariantsData,
  PostVariantsErrors,
  PostVariantsResponses,
  PostVisitItemsData,
  PostVisitItemsResponses,
  PostVisitsData,
  PostVisitsErrors,
  PostVisitsResponses,
  PutAppointmentsByIdData,
  PutAppointmentsByIdErrors,
  PutAppointmentsByIdResponses,
  PutAssignmentsByIdData,
  PutAssignmentsByIdErrors,
  PutAssignmentsByIdResponses,
  PutDepartmentsByIdData,
  PutDepartmentsByIdErrors,
  PutDepartmentsByIdResponses,
  PutItemsByIdData,
  PutItemsByIdErrors,
  PutItemsByIdResponses,
  PutMaintenancesByIdData,
  PutMaintenancesByIdErrors,
  PutMaintenancesByIdResponses,
  PutMaintenanceTypesByIdData,
  PutMaintenanceTypesByIdErrors,
  PutMaintenanceTypesByIdResponses,
  PutManufacturersByIdData,
  PutManufacturersByIdErrors,
  PutManufacturersByIdResponses,
  PutOrderItemsByIdData,
  PutOrderItemsByIdErrors,
  PutOrderItemsByIdResponses,
  PutOrdersByIdData,
  PutOrdersByIdErrors,
  PutOrdersByIdResponses,
  PutPersonsByIdData,
  PutPersonsByIdErrors,
  PutPersonsByIdResponses,
  PutProductsByIdData,
  PutProductsByIdErrors,
  PutProductsByIdResponses,
  PutProductTypesByIdData,
  PutProductTypesByIdErrors,
  PutProductTypesByIdResponses,
  PutStorageLocationsByIdData,
  PutStorageLocationsByIdErrors,
  PutStorageLocationsByIdResponses,
  PutTenantsByIdData,
  PutTenantsByIdErrors,
  PutTenantsByIdResponses,
  PutVariantsByIdData,
  PutVariantsByIdErrors,
  PutVariantsByIdResponses,
  PutVisitItemsByIdData,
  PutVisitItemsByIdErrors,
  PutVisitItemsByIdResponses,
  PutVisitsByIdData,
  PutVisitsByIdErrors,
  PutVisitsByIdResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List API integrations
 *
 * Returns a list of all API integrations. Client secrets are not included.
 */
export const getApiIntegrations = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiIntegrationsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiIntegrationsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api-integrations",
    ...options,
  });
};

/**
 * Create API integration
 *
 * Creates a new API integration with confidential client credentials. The credentials are shown only once.
 */
export const postApiIntegrations = <ThrowOnError extends boolean = false>(
  options: Options<PostApiIntegrationsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostApiIntegrationsResponses,
    PostApiIntegrationsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api-integrations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete API integration
 *
 * Deletes an API integration and revokes all access. This action cannot be undone.
 */
export const deleteApiIntegrationsByClientId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiIntegrationsByClientIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteApiIntegrationsByClientIdResponses,
    DeleteApiIntegrationsByClientIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api-integrations/{clientId}",
    ...options,
  });
};

/**
 * List all appointments
 *
 * Returns a list of all appointments.
 */
export const getAppointments = <ThrowOnError extends boolean = false>(
  options?: Options<GetAppointmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAppointmentsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getAppointmentsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/appointments",
    ...options,
  });
};

/**
 * Create a new appointment
 *
 * Creates a new appointment.
 */
export const postAppointments = <ThrowOnError extends boolean = false>(
  options: Options<PostAppointmentsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostAppointmentsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: postAppointmentsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/appointments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete an appointment
 *
 * Deletes an appointment by its unique ID. This will also delete all associated visits and visit items.
 */
export const deleteAppointmentsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAppointmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteAppointmentsByIdResponses,
    DeleteAppointmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/appointments/{id}",
    ...options,
  });
};

/**
 * Get appointment by ID
 *
 * Returns an appointment by its unique ID.
 */
export const getAppointmentsById = <ThrowOnError extends boolean = false>(
  options: Options<GetAppointmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAppointmentsByIdResponses,
    GetAppointmentsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getAppointmentsByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/appointments/{id}",
    ...options,
  });
};

/**
 * Update an appointment
 *
 * Updates an existing appointment.
 */
export const putAppointmentsById = <ThrowOnError extends boolean = false>(
  options: Options<PutAppointmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutAppointmentsByIdResponses,
    PutAppointmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/appointments/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all visits for an appointment
 *
 * Returns all visits for a specific appointment.
 */
export const getAppointmentsByIdVisits = <ThrowOnError extends boolean = false>(
  options: Options<GetAppointmentsByIdVisitsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAppointmentsByIdVisitsResponses,
    GetAppointmentsByIdVisitsErrors,
    ThrowOnError
  >({
    responseTransformer: getAppointmentsByIdVisitsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/appointments/{id}/visits",
    ...options,
  });
};

/**
 * List all departments
 *
 * Returns a list of all departments.
 */
export const getDepartments = <ThrowOnError extends boolean = false>(
  options?: Options<GetDepartmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetDepartmentsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments",
    ...options,
  });
};

/**
 * Create a new department
 *
 * Creates a new department.
 */
export const postDepartments = <ThrowOnError extends boolean = false>(
  options: Options<PostDepartmentsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostDepartmentsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a department
 *
 * Deletes a department by its unique ID.
 */
export const deleteDepartmentsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDepartmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDepartmentsByIdResponses,
    DeleteDepartmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments/{id}",
    ...options,
  });
};

/**
 * Get department by ID
 *
 * Returns a department by its unique ID.
 */
export const getDepartmentsById = <ThrowOnError extends boolean = false>(
  options: Options<GetDepartmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetDepartmentsByIdResponses,
    GetDepartmentsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments/{id}",
    ...options,
  });
};

/**
 * Update a department
 *
 * Updates an existing department.
 */
export const putDepartmentsById = <ThrowOnError extends boolean = false>(
  options: Options<PutDepartmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutDepartmentsByIdResponses,
    PutDepartmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all persons in a department
 *
 * Returns all persons that are members of the given department.
 */
export const getDepartmentsByIdPersons = <ThrowOnError extends boolean = false>(
  options: Options<GetDepartmentsByIdPersonsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetDepartmentsByIdPersonsResponses,
    GetDepartmentsByIdPersonsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/departments/{id}/persons",
    ...options,
  });
};

/**
 * List all item assignments
 *
 * Returns a list of all item assignment histories.
 */
export const getAssignments = <ThrowOnError extends boolean = false>(
  options?: Options<GetAssignmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAssignmentsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getAssignmentsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments",
    ...options,
  });
};

/**
 * Create a new assignment
 *
 * Creates a new item assignment history.
 */
export const postAssignments = <ThrowOnError extends boolean = false>(
  options: Options<PostAssignmentsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostAssignmentsResponses,
    PostAssignmentsErrors,
    ThrowOnError
  >({
    responseTransformer: postAssignmentsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete an assignment
 *
 * Deletes a item assignment history by its unique ID.
 */
export const deleteAssignmentsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAssignmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteAssignmentsByIdResponses,
    DeleteAssignmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments/{id}",
    ...options,
  });
};

/**
 * Get assignment by ID
 *
 * Returns a item assignment history by its unique ID.
 */
export const getAssignmentsById = <ThrowOnError extends boolean = false>(
  options: Options<GetAssignmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAssignmentsByIdResponses,
    GetAssignmentsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getAssignmentsByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments/{id}",
    ...options,
  });
};

/**
 * Update an assignment
 *
 * Updates an existing item assignment history.
 */
export const putAssignmentsById = <ThrowOnError extends boolean = false>(
  options: Options<PutAssignmentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutAssignmentsByIdResponses,
    PutAssignmentsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/assignments/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all items
 *
 * Returns a list of all items.
 */
export const getItems = <ThrowOnError extends boolean = false>(
  options?: Options<GetItemsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getItemsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items",
    ...options,
  });
};

/**
 * Create a new item
 *
 * Creates a new item.
 */
export const postItems = <ThrowOnError extends boolean = false>(
  options: Options<PostItemsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostItemsResponses,
    PostItemsErrors,
    ThrowOnError
  >({
    responseTransformer: postItemsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a item
 *
 * Deletes a item by its unique ID.
 */
export const deleteItemsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemsByIdResponses,
    DeleteItemsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}",
    ...options,
  });
};

/**
 * Get item by ID
 *
 * Returns a item by its unique ID.
 */
export const getItemsById = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemsByIdResponses,
    GetItemsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getItemsByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}",
    ...options,
  });
};

/**
 * Update a item
 *
 * Updates an existing item.
 */
export const putItemsById = <ThrowOnError extends boolean = false>(
  options: Options<PutItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemsByIdResponses,
    PutItemsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all assignments for a item
 *
 * Returns all assignment histories for a specific item.
 */
export const getItemsByIdAssignments = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsByIdAssignmentsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemsByIdAssignmentsResponses,
    GetItemsByIdAssignmentsErrors,
    ThrowOnError
  >({
    responseTransformer: getItemsByIdAssignmentsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}/assignments",
    ...options,
  });
};

/**
 * List all maintenances for a item
 *
 * Returns all maintenance records for a specific item.
 */
export const getItemsByIdMaintenance = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsByIdMaintenanceData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemsByIdMaintenanceResponses,
    GetItemsByIdMaintenanceErrors,
    ThrowOnError
  >({
    responseTransformer: getItemsByIdMaintenanceResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{id}/maintenance",
    ...options,
  });
};

/**
 * List all maintenances
 *
 * Returns a list of all maintenance records.
 */
export const getMaintenances = <ThrowOnError extends boolean = false>(
  options?: Options<GetMaintenancesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetMaintenancesResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getMaintenancesResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances",
    ...options,
  });
};

/**
 * Create a new maintenance
 *
 * Creates a new maintenance record.
 */
export const postMaintenances = <ThrowOnError extends boolean = false>(
  options: Options<PostMaintenancesData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostMaintenancesResponses,
    PostMaintenancesErrors,
    ThrowOnError
  >({
    responseTransformer: postMaintenancesResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a maintenance
 *
 * Deletes a maintenance record by its unique ID.
 */
export const deleteMaintenancesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteMaintenancesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteMaintenancesByIdResponses,
    DeleteMaintenancesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances/{id}",
    ...options,
  });
};

/**
 * Get maintenance by ID
 *
 * Returns a maintenance record by its unique ID.
 */
export const getMaintenancesById = <ThrowOnError extends boolean = false>(
  options: Options<GetMaintenancesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetMaintenancesByIdResponses,
    GetMaintenancesByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getMaintenancesByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances/{id}",
    ...options,
  });
};

/**
 * Update a maintenance
 *
 * Updates an existing maintenance record.
 */
export const putMaintenancesById = <ThrowOnError extends boolean = false>(
  options: Options<PutMaintenancesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutMaintenancesByIdResponses,
    PutMaintenancesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenances/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all maintenanceTypes
 *
 * Returns a list of all maintenanceTypes.
 */
export const getMaintenanceTypes = <ThrowOnError extends boolean = false>(
  options?: Options<GetMaintenanceTypesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetMaintenanceTypesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenance-types",
    ...options,
  });
};

/**
 * Create a new maintenanceType
 *
 * Creates a new maintenanceType.
 */
export const postMaintenanceTypes = <ThrowOnError extends boolean = false>(
  options: Options<PostMaintenanceTypesData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostMaintenanceTypesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenance-types",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a maintenanceType
 *
 * Deletes a maintenanceType by its unique ID.
 */
export const deleteMaintenanceTypesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteMaintenanceTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteMaintenanceTypesByIdResponses,
    DeleteMaintenanceTypesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenance-types/{id}",
    ...options,
  });
};

/**
 * Get maintenanceType by ID
 *
 * Returns a maintenanceType by its unique ID.
 */
export const getMaintenanceTypesById = <ThrowOnError extends boolean = false>(
  options: Options<GetMaintenanceTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetMaintenanceTypesByIdResponses,
    GetMaintenanceTypesByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenance-types/{id}",
    ...options,
  });
};

/**
 * Update a maintenanceType
 *
 * Updates an existing maintenanceType.
 */
export const putMaintenanceTypesById = <ThrowOnError extends boolean = false>(
  options: Options<PutMaintenanceTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutMaintenanceTypesByIdResponses,
    PutMaintenanceTypesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/maintenance-types/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all manufacturers
 *
 * Returns a list of all manufacturers.
 */
export const getManufacturers = <ThrowOnError extends boolean = false>(
  options?: Options<GetManufacturersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetManufacturersResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/manufacturers",
    ...options,
  });
};

/**
 * Create a new manufacturer
 *
 * Creates a new manufacturer.
 */
export const postManufacturers = <ThrowOnError extends boolean = false>(
  options: Options<PostManufacturersData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostManufacturersResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/manufacturers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a manufacturer
 *
 * Deletes a manufacturer by its unique ID.
 */
export const deleteManufacturersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteManufacturersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteManufacturersByIdResponses,
    DeleteManufacturersByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/manufacturers/{id}",
    ...options,
  });
};

/**
 * Get manufacturer by ID
 *
 * Returns a manufacturer by its unique ID.
 */
export const getManufacturersById = <ThrowOnError extends boolean = false>(
  options: Options<GetManufacturersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetManufacturersByIdResponses,
    GetManufacturersByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/manufacturers/{id}",
    ...options,
  });
};

/**
 * Update a manufacturer
 *
 * Updates an existing manufacturer.
 */
export const putManufacturersById = <ThrowOnError extends boolean = false>(
  options: Options<PutManufacturersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutManufacturersByIdResponses,
    PutManufacturersByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/manufacturers/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all products for a manufacturer
 *
 * Returns all products for a specific manufacturer.
 */
export const getManufacturersByIdProducts = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetManufacturersByIdProductsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetManufacturersByIdProductsResponses,
    GetManufacturersByIdProductsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/manufacturers/{id}/products",
    ...options,
  });
};

/**
 * List all orders
 *
 * Returns a list of all orders.
 */
export const getOrders = <ThrowOnError extends boolean = false>(
  options?: Options<GetOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetOrdersResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getOrdersResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders",
    ...options,
  });
};

/**
 * Create a new order
 *
 * Creates a new order.
 */
export const postOrders = <ThrowOnError extends boolean = false>(
  options: Options<PostOrdersData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostOrdersResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: postOrdersResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete an order
 *
 * Deletes an order by its unique ID.
 */
export const deleteOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOrdersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteOrdersByIdResponses,
    DeleteOrdersByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{id}",
    ...options,
  });
};

/**
 * Get order by ID
 *
 * Returns an order by its unique ID.
 */
export const getOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<GetOrdersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetOrdersByIdResponses,
    GetOrdersByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getOrdersByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{id}",
    ...options,
  });
};

/**
 * Update an order
 *
 * Updates an existing order.
 */
export const putOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<PutOrdersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutOrdersByIdResponses,
    PutOrdersByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all order items
 *
 * Returns a list of all order items.
 */
export const getOrderItems = <ThrowOnError extends boolean = false>(
  options?: Options<GetOrderItemsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetOrderItemsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/order-items",
    ...options,
  });
};

/**
 * Create a new order item
 *
 * Creates a new order item.
 */
export const postOrderItems = <ThrowOnError extends boolean = false>(
  options: Options<PostOrderItemsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostOrderItemsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/order-items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List order items by order ID
 *
 * Returns a list of order items for a specific order.
 */
export const getOrderItemsByOrderByOrderId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetOrderItemsByOrderByOrderIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetOrderItemsByOrderByOrderIdResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/order-items/by-order/{orderId}",
    ...options,
  });
};

/**
 * Delete an order item
 *
 * Deletes an order item by its unique ID.
 */
export const deleteOrderItemsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOrderItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteOrderItemsByIdResponses,
    DeleteOrderItemsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/order-items/{id}",
    ...options,
  });
};

/**
 * Get order item by ID
 *
 * Returns an order item by its unique ID.
 */
export const getOrderItemsById = <ThrowOnError extends boolean = false>(
  options: Options<GetOrderItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetOrderItemsByIdResponses,
    GetOrderItemsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/order-items/{id}",
    ...options,
  });
};

/**
 * Update an order item
 *
 * Updates an existing order item.
 */
export const putOrderItemsById = <ThrowOnError extends boolean = false>(
  options: Options<PutOrderItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutOrderItemsByIdResponses,
    PutOrderItemsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/order-items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all persons
 *
 * Returns a list of all persons.
 */
export const getPersons = <ThrowOnError extends boolean = false>(
  options?: Options<GetPersonsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPersonsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons",
    ...options,
  });
};

/**
 * Create a new person
 *
 * Creates a new person entry.
 */
export const postPersons = <ThrowOnError extends boolean = false>(
  options: Options<PostPersonsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostPersonsResponses,
    PostPersonsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a person
 *
 * Deletes a person by ID.
 */
export const deletePersonsById = <ThrowOnError extends boolean = false>(
  options: Options<DeletePersonsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeletePersonsByIdResponses,
    DeletePersonsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons/{id}",
    ...options,
  });
};

/**
 * Get person by ID
 *
 * Returns a single person by their unique ID.
 */
export const getPersonsById = <ThrowOnError extends boolean = false>(
  options: Options<GetPersonsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPersonsByIdResponses,
    GetPersonsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons/{id}",
    ...options,
  });
};

/**
 * Update a person
 *
 * Updates an existing person.
 */
export const putPersonsById = <ThrowOnError extends boolean = false>(
  options: Options<PutPersonsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutPersonsByIdResponses,
    PutPersonsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all items assigned to a person
 *
 * Returns all items assigned to a specific person.
 */
export const getPersonsByIdItems = <ThrowOnError extends boolean = false>(
  options: Options<GetPersonsByIdItemsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPersonsByIdItemsResponses,
    GetPersonsByIdItemsErrors,
    ThrowOnError
  >({
    responseTransformer: getPersonsByIdItemsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/persons/{id}/items",
    ...options,
  });
};

/**
 * List all products
 *
 * Returns a list of all products.
 */
export const getProducts = <ThrowOnError extends boolean = false>(
  options?: Options<GetProductsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetProductsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products",
    ...options,
  });
};

/**
 * Create a new product
 *
 * Creates a new product.
 */
export const postProducts = <ThrowOnError extends boolean = false>(
  options: Options<PostProductsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostProductsResponses,
    PostProductsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a product
 *
 * Deletes a product by its unique ID.
 */
export const deleteProductsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProductsByIdResponses,
    DeleteProductsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{id}",
    ...options,
  });
};

/**
 * Get product by ID
 *
 * Returns a product by its unique ID.
 */
export const getProductsById = <ThrowOnError extends boolean = false>(
  options: Options<GetProductsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProductsByIdResponses,
    GetProductsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{id}",
    ...options,
  });
};

/**
 * Update a product
 *
 * Updates an existing product.
 */
export const putProductsById = <ThrowOnError extends boolean = false>(
  options: Options<PutProductsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutProductsByIdResponses,
    PutProductsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all variants for a product
 *
 * Returns all variants for a specific product.
 */
export const getProductsByIdVariants = <ThrowOnError extends boolean = false>(
  options: Options<GetProductsByIdVariantsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProductsByIdVariantsResponses,
    GetProductsByIdVariantsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{id}/variants",
    ...options,
  });
};

/**
 * List all productTypes
 *
 * Returns a list of all productTypes.
 */
export const getProductTypes = <ThrowOnError extends boolean = false>(
  options?: Options<GetProductTypesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetProductTypesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-types",
    ...options,
  });
};

/**
 * Create a new productType
 *
 * Creates a new productType.
 */
export const postProductTypes = <ThrowOnError extends boolean = false>(
  options: Options<PostProductTypesData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostProductTypesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-types",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a productType
 *
 * Deletes a productType by its unique ID.
 */
export const deleteProductTypesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProductTypesByIdResponses,
    DeleteProductTypesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-types/{id}",
    ...options,
  });
};

/**
 * Get productType by ID
 *
 * Returns a productType by its unique ID.
 */
export const getProductTypesById = <ThrowOnError extends boolean = false>(
  options: Options<GetProductTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProductTypesByIdResponses,
    GetProductTypesByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-types/{id}",
    ...options,
  });
};

/**
 * Update a productType
 *
 * Updates an existing productType.
 */
export const putProductTypesById = <ThrowOnError extends boolean = false>(
  options: Options<PutProductTypesByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutProductTypesByIdResponses,
    PutProductTypesByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-types/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all storage locations
 *
 * Returns a list of all storage locations.
 */
export const getStorageLocations = <ThrowOnError extends boolean = false>(
  options?: Options<GetStorageLocationsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetStorageLocationsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storage-locations",
    ...options,
  });
};

/**
 * Create a new storage location
 *
 * Creates a new storage location.
 */
export const postStorageLocations = <ThrowOnError extends boolean = false>(
  options: Options<PostStorageLocationsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostStorageLocationsResponses,
    PostStorageLocationsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storage-locations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a storage location
 *
 * Deletes a storage location by its unique ID.
 */
export const deleteStorageLocationsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteStorageLocationsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteStorageLocationsByIdResponses,
    DeleteStorageLocationsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storage-locations/{id}",
    ...options,
  });
};

/**
 * Get storage location by ID
 *
 * Returns a storage location by its unique ID.
 */
export const getStorageLocationsById = <ThrowOnError extends boolean = false>(
  options: Options<GetStorageLocationsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetStorageLocationsByIdResponses,
    GetStorageLocationsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storage-locations/{id}",
    ...options,
  });
};

/**
 * Update a storage location
 *
 * Updates an existing storage location.
 */
export const putStorageLocationsById = <ThrowOnError extends boolean = false>(
  options: Options<PutStorageLocationsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutStorageLocationsByIdResponses,
    PutStorageLocationsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storage-locations/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all items for a storage location
 *
 * Returns all items assigned to a storage location.
 */
export const getStorageLocationsByIdItems = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetStorageLocationsByIdItemsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetStorageLocationsByIdItemsResponses,
    GetStorageLocationsByIdItemsErrors,
    ThrowOnError
  >({
    responseTransformer: getStorageLocationsByIdItemsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/storage-locations/{id}/items",
    ...options,
  });
};

/**
 * List all tenants (System Admin)
 *
 * Returns a list of all tenants in the system. Only accessible to system administrators.
 */
export const getTenants = <ThrowOnError extends boolean = false>(
  options?: Options<GetTenantsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetTenantsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getTenantsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/tenants",
    ...options,
  });
};

/**
 * Create a new tenant (System Admin)
 *
 * Creates a new tenant with a unique realm and name. Only accessible to system administrators.
 */
export const postTenants = <ThrowOnError extends boolean = false>(
  options: Options<PostTenantsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostTenantsResponses,
    PostTenantsErrors,
    ThrowOnError
  >({
    responseTransformer: postTenantsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/tenants",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a tenant (System Admin)
 *
 * Deletes a tenant by its unique ID. Only accessible to system administrators.
 */
export const deleteTenantsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTenantsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteTenantsByIdResponses,
    DeleteTenantsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/tenants/{id}",
    ...options,
  });
};

/**
 * Get tenant by ID (System Admin)
 *
 * Returns a tenant by its unique ID. Only accessible to system administrators.
 */
export const getTenantsById = <ThrowOnError extends boolean = false>(
  options: Options<GetTenantsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetTenantsByIdResponses,
    GetTenantsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getTenantsByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/tenants/{id}",
    ...options,
  });
};

/**
 * Update a tenant (System Admin)
 *
 * Updates an existing tenant. Only accessible to system administrators.
 */
export const putTenantsById = <ThrowOnError extends boolean = false>(
  options: Options<PutTenantsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutTenantsByIdResponses,
    PutTenantsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/tenants/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all users
 *
 * Returns a list of all users.
 */
export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUsersResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users",
    ...options,
  });
};

/**
 * Get user by ID
 *
 * Returns a user by its unique ID.
 */
export const getUsersById = <ThrowOnError extends boolean = false>(
  options: Options<GetUsersByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetUsersByIdResponses,
    GetUsersByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * List all variants
 *
 * Returns a list of all variants.
 */
export const getVariants = <ThrowOnError extends boolean = false>(
  options?: Options<GetVariantsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetVariantsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants",
    ...options,
  });
};

/**
 * Create a new variant
 *
 * Creates a new variant.
 */
export const postVariants = <ThrowOnError extends boolean = false>(
  options: Options<PostVariantsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostVariantsResponses,
    PostVariantsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a variant
 *
 * Deletes a variant by its unique ID.
 */
export const deleteVariantsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVariantsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteVariantsByIdResponses,
    DeleteVariantsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants/{id}",
    ...options,
  });
};

/**
 * Get variant by ID
 *
 * Returns a variant by its unique ID.
 */
export const getVariantsById = <ThrowOnError extends boolean = false>(
  options: Options<GetVariantsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetVariantsByIdResponses,
    GetVariantsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants/{id}",
    ...options,
  });
};

/**
 * Update a variant
 *
 * Updates an existing variant.
 */
export const putVariantsById = <ThrowOnError extends boolean = false>(
  options: Options<PutVariantsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutVariantsByIdResponses,
    PutVariantsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all items for a variant
 *
 * Returns all items for a specific variant.
 */
export const getVariantsByIdItems = <ThrowOnError extends boolean = false>(
  options: Options<GetVariantsByIdItemsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetVariantsByIdItemsResponses,
    GetVariantsByIdItemsErrors,
    ThrowOnError
  >({
    responseTransformer: getVariantsByIdItemsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/variants/{id}/items",
    ...options,
  });
};

/**
 * List all visit items
 *
 * Returns a list of all visit items.
 */
export const getVisitItems = <ThrowOnError extends boolean = false>(
  options?: Options<GetVisitItemsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetVisitItemsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visit-items",
    ...options,
  });
};

/**
 * Create a new visit item
 *
 * Creates a new visit item.
 */
export const postVisitItems = <ThrowOnError extends boolean = false>(
  options: Options<PostVisitItemsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostVisitItemsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visit-items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List visit items by visit ID
 *
 * Returns a list of visit items for a specific visit.
 */
export const getVisitItemsByVisitByVisitId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetVisitItemsByVisitByVisitIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetVisitItemsByVisitByVisitIdResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visit-items/by-visit/{visitId}",
    ...options,
  });
};

/**
 * Delete a visit item
 *
 * Deletes a visit item by its unique ID.
 */
export const deleteVisitItemsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVisitItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteVisitItemsByIdResponses,
    DeleteVisitItemsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visit-items/{id}",
    ...options,
  });
};

/**
 * Get visit item by ID
 *
 * Returns a visit item by its unique ID.
 */
export const getVisitItemsById = <ThrowOnError extends boolean = false>(
  options: Options<GetVisitItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetVisitItemsByIdResponses,
    GetVisitItemsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visit-items/{id}",
    ...options,
  });
};

/**
 * Update a visit item
 *
 * Updates an existing visit item.
 */
export const putVisitItemsById = <ThrowOnError extends boolean = false>(
  options: Options<PutVisitItemsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutVisitItemsByIdResponses,
    PutVisitItemsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visit-items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all visits
 *
 * Returns a list of all visits.
 */
export const getVisits = <ThrowOnError extends boolean = false>(
  options?: Options<GetVisitsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetVisitsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getVisitsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visits",
    ...options,
  });
};

/**
 * Create a new visit
 *
 * Creates a new visit. A person can only have one visit per appointment.
 */
export const postVisits = <ThrowOnError extends boolean = false>(
  options: Options<PostVisitsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostVisitsResponses,
    PostVisitsErrors,
    ThrowOnError
  >({
    responseTransformer: postVisitsResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visits",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a visit
 *
 * Deletes a visit by its unique ID. This will also delete all associated visit items.
 */
export const deleteVisitsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVisitsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteVisitsByIdResponses,
    DeleteVisitsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visits/{id}",
    ...options,
  });
};

/**
 * Get visit by ID
 *
 * Returns a visit by its unique ID.
 */
export const getVisitsById = <ThrowOnError extends boolean = false>(
  options: Options<GetVisitsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetVisitsByIdResponses,
    GetVisitsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getVisitsByIdResponseTransformer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visits/{id}",
    ...options,
  });
};

/**
 * Update a visit
 *
 * Updates an existing visit. The combination of appointment and person must remain unique.
 */
export const putVisitsById = <ThrowOnError extends boolean = false>(
  options: Options<PutVisitsByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutVisitsByIdResponses,
    PutVisitsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visits/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List all items for a visit
 *
 * Returns all items associated with a specific visit.
 */
export const getVisitsByIdItems = <ThrowOnError extends boolean = false>(
  options: Options<GetVisitsByIdItemsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetVisitsByIdItemsResponses,
    GetVisitsByIdItemsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/visits/{id}/items",
    ...options,
  });
};
