// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetAppointmentsByIdResponse,
  GetAppointmentsByIdVisitsResponse,
  GetAppointmentsResponse,
  GetAssignmentsByIdResponse,
  GetAssignmentsResponse,
  GetDepartmentsByIdPersonsResponse,
  GetDepartmentsByIdResponse,
  GetDepartmentsResponse,
  GetItemsByIdAssignmentsResponse,
  GetItemsByIdMaintenanceResponse,
  GetItemsByIdResponse,
  GetItemsResponse,
  GetMaintenancesByIdResponse,
  GetMaintenancesResponse,
  GetMaintenanceTypesByIdResponse,
  GetMaintenanceTypesResponse,
  GetManufacturersByIdProductsResponse,
  GetManufacturersByIdResponse,
  GetManufacturersResponse,
  GetOrderItemsByIdResponse,
  GetOrderItemsByOrderByOrderIdResponse,
  GetOrderItemsResponse,
  GetOrdersByIdResponse,
  GetOrdersResponse,
  GetPersonsByIdAssignmentsResponse,
  GetPersonsByIdResponse,
  GetPersonsResponse,
  GetProductsByIdResponse,
  GetProductsByIdVariantsResponse,
  GetProductsResponse,
  GetProductTypesByIdResponse,
  GetProductTypesResponse,
  GetStorageLocationsByIdAssignmentsResponse,
  GetStorageLocationsByIdResponse,
  GetStorageLocationsResponse,
  GetTenantsByIdResponse,
  GetTenantsResponse,
  GetVariantsByIdItemsResponse,
  GetVariantsByIdResponse,
  GetVariantsResponse,
  GetVisitItemsByIdResponse,
  GetVisitItemsByVisitByVisitIdResponse,
  GetVisitItemsResponse,
  GetVisitsByIdItemsResponse,
  GetVisitsByIdResponse,
  GetVisitsResponse,
  PostAppointmentsResponse,
  PostAssignmentsResponse,
  PostDepartmentsResponse,
  PostItemsResponse,
  PostMaintenancesResponse,
  PostMaintenanceTypesResponse,
  PostManufacturersResponse,
  PostOrderItemsResponse,
  PostOrdersResponse,
  PostPersonsResponse,
  PostProductsResponse,
  PostProductTypesResponse,
  PostStorageLocationsResponse,
  PostTenantsResponse,
  PostVariantsResponse,
  PostVisitItemsResponse,
  PostVisitsResponse,
} from "./types.gen";

const appointmentModelSchemaResponseTransformer = (data: any) => {
  data.scheduledAt = new Date(data.scheduledAt);
  return data;
};

export const getAppointmentsResponseTransformer = async (
  data: any,
): Promise<GetAppointmentsResponse> => {
  data = data.map((item: any) => {
    return appointmentModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postAppointmentsResponseTransformer = async (
  data: any,
): Promise<PostAppointmentsResponse> => {
  data = appointmentModelSchemaResponseTransformer(data);
  return data;
};

export const getAppointmentsByIdResponseTransformer = async (
  data: any,
): Promise<GetAppointmentsByIdResponse> => {
  data = appointmentModelSchemaResponseTransformer(data);
  return data;
};

const visitModelSchemaResponseTransformer = (data: any) => {
  data.appointment = appointmentModelSchemaResponseTransformer(
    data.appointment,
  );
  data.person = personModelSchemaResponseTransformer(data.person);
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

const personModelSchemaResponseTransformer = (data: any) => {
  data.departments = data.departments.map((item: any) => {
    return departmentModelSchemaResponseTransformer(item);
  });
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

const departmentModelSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

export const getAppointmentsByIdVisitsResponseTransformer = async (
  data: any,
): Promise<GetAppointmentsByIdVisitsResponse> => {
  data = data.map((item: any) => {
    return visitModelSchemaResponseTransformer(item);
  });
  return data;
};

export const getDepartmentsResponseTransformer = async (
  data: any,
): Promise<GetDepartmentsResponse> => {
  data = data.map((item: any) => {
    return departmentModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postDepartmentsResponseTransformer = async (
  data: any,
): Promise<PostDepartmentsResponse> => {
  data = departmentModelSchemaResponseTransformer(data);
  return data;
};

export const getDepartmentsByIdResponseTransformer = async (
  data: any,
): Promise<GetDepartmentsByIdResponse> => {
  data = departmentModelSchemaResponseTransformer(data);
  return data;
};

export const getDepartmentsByIdPersonsResponseTransformer = async (
  data: any,
): Promise<GetDepartmentsByIdPersonsResponse> => {
  data = data.map((item: any) => {
    return personModelSchemaResponseTransformer(item);
  });
  return data;
};

const itemAssignmentHistoryModelSchemaResponseTransformer = (data: any) => {
  if (data.person) {
    data.person = personModelSchemaResponseTransformer(data.person);
  }
  if (data.storageLocation) {
    data.storageLocation = storageLocationModelSchemaResponseTransformer(
      data.storageLocation,
    );
  }
  data.item = itemModelSchemaResponseTransformer(data.item);
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  data.assignedFrom = new Date(data.assignedFrom);
  if (data.assignedUntil) {
    data.assignedUntil = new Date(data.assignedUntil);
  }
  return data;
};

const storageLocationModelSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

const itemModelSchemaResponseTransformer = (data: any) => {
  data.variant = variantModelSchemaResponseTransformer(data.variant);
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  data.purchaseDate = new Date(data.purchaseDate);
  if (data.retirementDate) {
    data.retirementDate = new Date(data.retirementDate);
  }
  return data;
};

const variantModelSchemaResponseTransformer = (data: any) => {
  data.product = productModelSchemaResponseTransformer(data.product);
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

const productModelSchemaResponseTransformer = (data: any) => {
  data.type = productTypeModelSchemaResponseTransformer(data.type);
  data.manufacturer = manufacturerModelSchemaResponseTransformer(
    data.manufacturer,
  );
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

const productTypeModelSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

const manufacturerModelSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

export const getAssignmentsResponseTransformer = async (
  data: any,
): Promise<GetAssignmentsResponse> => {
  data = data.map((item: any) => {
    return itemAssignmentHistoryModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postAssignmentsResponseTransformer = async (
  data: any,
): Promise<PostAssignmentsResponse> => {
  data = itemAssignmentHistoryModelSchemaResponseTransformer(data);
  return data;
};

export const getAssignmentsByIdResponseTransformer = async (
  data: any,
): Promise<GetAssignmentsByIdResponse> => {
  data = itemAssignmentHistoryModelSchemaResponseTransformer(data);
  return data;
};

export const getItemsResponseTransformer = async (
  data: any,
): Promise<GetItemsResponse> => {
  data = data.map((item: any) => {
    return itemModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postItemsResponseTransformer = async (
  data: any,
): Promise<PostItemsResponse> => {
  data = itemModelSchemaResponseTransformer(data);
  return data;
};

export const getItemsByIdResponseTransformer = async (
  data: any,
): Promise<GetItemsByIdResponse> => {
  data = itemModelSchemaResponseTransformer(data);
  return data;
};

export const getItemsByIdAssignmentsResponseTransformer = async (
  data: any,
): Promise<GetItemsByIdAssignmentsResponse> => {
  data = data.map((item: any) => {
    return itemAssignmentHistoryModelSchemaResponseTransformer(item);
  });
  return data;
};

const maintenanceModelSchemaResponseTransformer = (data: any) => {
  data.type = maintenanceTypeModelSchemaResponseTransformer(data.type);
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  data.performedAt = new Date(data.performedAt);
  return data;
};

const maintenanceTypeModelSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

export const getItemsByIdMaintenanceResponseTransformer = async (
  data: any,
): Promise<GetItemsByIdMaintenanceResponse> => {
  data = data.map((item: any) => {
    return maintenanceModelSchemaResponseTransformer(item);
  });
  return data;
};

export const getMaintenancesResponseTransformer = async (
  data: any,
): Promise<GetMaintenancesResponse> => {
  data = data.map((item: any) => {
    return maintenanceModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postMaintenancesResponseTransformer = async (
  data: any,
): Promise<PostMaintenancesResponse> => {
  data = maintenanceModelSchemaResponseTransformer(data);
  return data;
};

export const getMaintenancesByIdResponseTransformer = async (
  data: any,
): Promise<GetMaintenancesByIdResponse> => {
  data = maintenanceModelSchemaResponseTransformer(data);
  return data;
};

export const getMaintenanceTypesResponseTransformer = async (
  data: any,
): Promise<GetMaintenanceTypesResponse> => {
  data = data.map((item: any) => {
    return maintenanceTypeModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postMaintenanceTypesResponseTransformer = async (
  data: any,
): Promise<PostMaintenanceTypesResponse> => {
  data = maintenanceTypeModelSchemaResponseTransformer(data);
  return data;
};

export const getMaintenanceTypesByIdResponseTransformer = async (
  data: any,
): Promise<GetMaintenanceTypesByIdResponse> => {
  data = maintenanceTypeModelSchemaResponseTransformer(data);
  return data;
};

export const getManufacturersResponseTransformer = async (
  data: any,
): Promise<GetManufacturersResponse> => {
  data = data.map((item: any) => {
    return manufacturerModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postManufacturersResponseTransformer = async (
  data: any,
): Promise<PostManufacturersResponse> => {
  data = manufacturerModelSchemaResponseTransformer(data);
  return data;
};

export const getManufacturersByIdResponseTransformer = async (
  data: any,
): Promise<GetManufacturersByIdResponse> => {
  data = manufacturerModelSchemaResponseTransformer(data);
  return data;
};

export const getManufacturersByIdProductsResponseTransformer = async (
  data: any,
): Promise<GetManufacturersByIdProductsResponse> => {
  data = data.map((item: any) => {
    return productModelSchemaResponseTransformer(item);
  });
  return data;
};

const orderModelSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  data.orderDate = new Date(data.orderDate);
  if (data.deliveryDate) {
    data.deliveryDate = new Date(data.deliveryDate);
  }
  return data;
};

export const getOrdersResponseTransformer = async (
  data: any,
): Promise<GetOrdersResponse> => {
  data = data.map((item: any) => {
    return orderModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postOrdersResponseTransformer = async (
  data: any,
): Promise<PostOrdersResponse> => {
  data = orderModelSchemaResponseTransformer(data);
  return data;
};

export const getOrdersByIdResponseTransformer = async (
  data: any,
): Promise<GetOrdersByIdResponse> => {
  data = orderModelSchemaResponseTransformer(data);
  return data;
};

const orderItemModelSchemaResponseTransformer = (data: any) => {
  data.variant = variantModelSchemaResponseTransformer(data.variant);
  if (data.person) {
    data.person = personModelSchemaResponseTransformer(data.person);
  }
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

export const getOrderItemsResponseTransformer = async (
  data: any,
): Promise<GetOrderItemsResponse> => {
  data = data.map((item: any) => {
    return orderItemModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postOrderItemsResponseTransformer = async (
  data: any,
): Promise<PostOrderItemsResponse> => {
  data = orderItemModelSchemaResponseTransformer(data);
  return data;
};

export const getOrderItemsByOrderByOrderIdResponseTransformer = async (
  data: any,
): Promise<GetOrderItemsByOrderByOrderIdResponse> => {
  data = data.map((item: any) => {
    return orderItemModelSchemaResponseTransformer(item);
  });
  return data;
};

export const getOrderItemsByIdResponseTransformer = async (
  data: any,
): Promise<GetOrderItemsByIdResponse> => {
  data = orderItemModelSchemaResponseTransformer(data);
  return data;
};

export const getPersonsResponseTransformer = async (
  data: any,
): Promise<GetPersonsResponse> => {
  data = data.map((item: any) => {
    return personModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postPersonsResponseTransformer = async (
  data: any,
): Promise<PostPersonsResponse> => {
  data = personModelSchemaResponseTransformer(data);
  return data;
};

export const getPersonsByIdResponseTransformer = async (
  data: any,
): Promise<GetPersonsByIdResponse> => {
  data = personModelSchemaResponseTransformer(data);
  return data;
};

export const getPersonsByIdAssignmentsResponseTransformer = async (
  data: any,
): Promise<GetPersonsByIdAssignmentsResponse> => {
  data = data.map((item: any) => {
    return itemAssignmentHistoryModelSchemaResponseTransformer(item);
  });
  return data;
};

export const getProductsResponseTransformer = async (
  data: any,
): Promise<GetProductsResponse> => {
  data = data.map((item: any) => {
    return productModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postProductsResponseTransformer = async (
  data: any,
): Promise<PostProductsResponse> => {
  data = productModelSchemaResponseTransformer(data);
  return data;
};

export const getProductsByIdResponseTransformer = async (
  data: any,
): Promise<GetProductsByIdResponse> => {
  data = productModelSchemaResponseTransformer(data);
  return data;
};

export const getProductsByIdVariantsResponseTransformer = async (
  data: any,
): Promise<GetProductsByIdVariantsResponse> => {
  data = data.map((item: any) => {
    return variantModelSchemaResponseTransformer(item);
  });
  return data;
};

export const getProductTypesResponseTransformer = async (
  data: any,
): Promise<GetProductTypesResponse> => {
  data = data.map((item: any) => {
    return productTypeModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postProductTypesResponseTransformer = async (
  data: any,
): Promise<PostProductTypesResponse> => {
  data = productTypeModelSchemaResponseTransformer(data);
  return data;
};

export const getProductTypesByIdResponseTransformer = async (
  data: any,
): Promise<GetProductTypesByIdResponse> => {
  data = productTypeModelSchemaResponseTransformer(data);
  return data;
};

export const getStorageLocationsResponseTransformer = async (
  data: any,
): Promise<GetStorageLocationsResponse> => {
  data = data.map((item: any) => {
    return storageLocationModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postStorageLocationsResponseTransformer = async (
  data: any,
): Promise<PostStorageLocationsResponse> => {
  data = storageLocationModelSchemaResponseTransformer(data);
  return data;
};

export const getStorageLocationsByIdResponseTransformer = async (
  data: any,
): Promise<GetStorageLocationsByIdResponse> => {
  data = storageLocationModelSchemaResponseTransformer(data);
  return data;
};

export const getStorageLocationsByIdAssignmentsResponseTransformer = async (
  data: any,
): Promise<GetStorageLocationsByIdAssignmentsResponse> => {
  data = data.map((item: any) => {
    return itemAssignmentHistoryModelSchemaResponseTransformer(item);
  });
  return data;
};

const tenantModelSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

export const getTenantsResponseTransformer = async (
  data: any,
): Promise<GetTenantsResponse> => {
  data = data.map((item: any) => {
    return tenantModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postTenantsResponseTransformer = async (
  data: any,
): Promise<PostTenantsResponse> => {
  data = tenantModelSchemaResponseTransformer(data);
  return data;
};

export const getTenantsByIdResponseTransformer = async (
  data: any,
): Promise<GetTenantsByIdResponse> => {
  data = tenantModelSchemaResponseTransformer(data);
  return data;
};

export const getVariantsResponseTransformer = async (
  data: any,
): Promise<GetVariantsResponse> => {
  data = data.map((item: any) => {
    return variantModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postVariantsResponseTransformer = async (
  data: any,
): Promise<PostVariantsResponse> => {
  data = variantModelSchemaResponseTransformer(data);
  return data;
};

export const getVariantsByIdResponseTransformer = async (
  data: any,
): Promise<GetVariantsByIdResponse> => {
  data = variantModelSchemaResponseTransformer(data);
  return data;
};

export const getVariantsByIdItemsResponseTransformer = async (
  data: any,
): Promise<GetVariantsByIdItemsResponse> => {
  data = data.map((item: any) => {
    return itemModelSchemaResponseTransformer(item);
  });
  return data;
};

const visitItemModelSchemaResponseTransformer = (data: any) => {
  data.product = productModelSchemaResponseTransformer(data.product);
  data.createdAt = new Date(data.createdAt);
  if (data.modifiedAt) {
    data.modifiedAt = new Date(data.modifiedAt);
  }
  return data;
};

export const getVisitItemsResponseTransformer = async (
  data: any,
): Promise<GetVisitItemsResponse> => {
  data = data.map((item: any) => {
    return visitItemModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postVisitItemsResponseTransformer = async (
  data: any,
): Promise<PostVisitItemsResponse> => {
  data = visitItemModelSchemaResponseTransformer(data);
  return data;
};

export const getVisitItemsByVisitByVisitIdResponseTransformer = async (
  data: any,
): Promise<GetVisitItemsByVisitByVisitIdResponse> => {
  data = data.map((item: any) => {
    return visitItemModelSchemaResponseTransformer(item);
  });
  return data;
};

export const getVisitItemsByIdResponseTransformer = async (
  data: any,
): Promise<GetVisitItemsByIdResponse> => {
  data = visitItemModelSchemaResponseTransformer(data);
  return data;
};

export const getVisitsResponseTransformer = async (
  data: any,
): Promise<GetVisitsResponse> => {
  data = data.map((item: any) => {
    return visitModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postVisitsResponseTransformer = async (
  data: any,
): Promise<PostVisitsResponse> => {
  data = visitModelSchemaResponseTransformer(data);
  return data;
};

export const getVisitsByIdResponseTransformer = async (
  data: any,
): Promise<GetVisitsByIdResponse> => {
  data = visitModelSchemaResponseTransformer(data);
  return data;
};

export const getVisitsByIdItemsResponseTransformer = async (
  data: any,
): Promise<GetVisitsByIdItemsResponse> => {
  data = data.map((item: any) => {
    return visitItemModelSchemaResponseTransformer(item);
  });
  return data;
};
