// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetAssignmentsByIdResponse,
  GetAssignmentsResponse,
  GetItemsByIdAssignmentsResponse,
  GetItemsByIdMaintenanceResponse,
  GetItemsByIdResponse,
  GetItemsResponse,
  GetMaintenancesByIdResponse,
  GetMaintenancesResponse,
  GetOrdersByIdResponse,
  GetOrdersResponse,
  GetPersonsByIdItemsResponse,
  GetStorageLocationsByIdItemsResponse,
  GetVariantsByIdItemsResponse,
  PostAssignmentsResponse,
  PostItemsResponse,
  PostMaintenancesResponse,
  PostOrdersResponse,
} from "./types.gen";

const itemAssignmentHistoryModelSchemaResponseTransformer = (data: any) => {
  data.assignedFrom = new Date(data.assignedFrom);
  if (data.assignedUntil) {
    data.assignedUntil = new Date(data.assignedUntil);
  }
  return data;
};

export const getAssignmentsResponseTransformer = async (
  data: any,
): Promise<GetAssignmentsResponse> => {
  data = data.map((item: any) => {
    return itemAssignmentHistoryModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postAssignmentsResponseTransformer = async (
  data: any,
): Promise<PostAssignmentsResponse> => {
  data = itemAssignmentHistoryModelSchemaResponseTransformer(data);
  return data;
};

export const getAssignmentsByIdResponseTransformer = async (
  data: any,
): Promise<GetAssignmentsByIdResponse> => {
  data = itemAssignmentHistoryModelSchemaResponseTransformer(data);
  return data;
};

const itemModelSchemaResponseTransformer = (data: any) => {
  data.purchaseDate = new Date(data.purchaseDate);
  if (data.retirementDate) {
    data.retirementDate = new Date(data.retirementDate);
  }
  return data;
};

export const getItemsResponseTransformer = async (
  data: any,
): Promise<GetItemsResponse> => {
  data = data.map((item: any) => {
    return itemModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postItemsResponseTransformer = async (
  data: any,
): Promise<PostItemsResponse> => {
  data = itemModelSchemaResponseTransformer(data);
  return data;
};

export const getItemsByIdResponseTransformer = async (
  data: any,
): Promise<GetItemsByIdResponse> => {
  data = itemModelSchemaResponseTransformer(data);
  return data;
};

export const getItemsByIdAssignmentsResponseTransformer = async (
  data: any,
): Promise<GetItemsByIdAssignmentsResponse> => {
  data = data.map((item: any) => {
    return itemAssignmentHistoryModelSchemaResponseTransformer(item);
  });
  return data;
};

const maintenanceModelSchemaResponseTransformer = (data: any) => {
  data.performedAt = new Date(data.performedAt);
  return data;
};

export const getItemsByIdMaintenanceResponseTransformer = async (
  data: any,
): Promise<GetItemsByIdMaintenanceResponse> => {
  data = data.map((item: any) => {
    return maintenanceModelSchemaResponseTransformer(item);
  });
  return data;
};

export const getMaintenancesResponseTransformer = async (
  data: any,
): Promise<GetMaintenancesResponse> => {
  data = data.map((item: any) => {
    return maintenanceModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postMaintenancesResponseTransformer = async (
  data: any,
): Promise<PostMaintenancesResponse> => {
  data = maintenanceModelSchemaResponseTransformer(data);
  return data;
};

export const getMaintenancesByIdResponseTransformer = async (
  data: any,
): Promise<GetMaintenancesByIdResponse> => {
  data = maintenanceModelSchemaResponseTransformer(data);
  return data;
};

const orderModelSchemaResponseTransformer = (data: any) => {
  data.orderDate = new Date(data.orderDate);
  if (data.deliveryDate) {
    data.deliveryDate = new Date(data.deliveryDate);
  }
  return data;
};

export const getOrdersResponseTransformer = async (
  data: any,
): Promise<GetOrdersResponse> => {
  data = data.map((item: any) => {
    return orderModelSchemaResponseTransformer(item);
  });
  return data;
};

export const postOrdersResponseTransformer = async (
  data: any,
): Promise<PostOrdersResponse> => {
  data = orderModelSchemaResponseTransformer(data);
  return data;
};

export const getOrdersByIdResponseTransformer = async (
  data: any,
): Promise<GetOrdersByIdResponse> => {
  data = orderModelSchemaResponseTransformer(data);
  return data;
};

export const getPersonsByIdItemsResponseTransformer = async (
  data: any,
): Promise<GetPersonsByIdItemsResponse> => {
  data = data.map((item: any) => {
    return itemModelSchemaResponseTransformer(item);
  });
  return data;
};

export const getStorageLocationsByIdItemsResponseTransformer = async (
  data: any,
): Promise<GetStorageLocationsByIdItemsResponse> => {
  data = data.map((item: any) => {
    return itemModelSchemaResponseTransformer(item);
  });
  return data;
};

export const getVariantsByIdItemsResponseTransformer = async (
  data: any,
): Promise<GetVariantsByIdItemsResponse> => {
  data = data.map((item: any) => {
    return itemModelSchemaResponseTransformer(item);
  });
  return data;
};
