// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "https://localhost:7197/" | (string & {});
};

export type ApiIntegrationCredentialsModel = {
  clientId: string;
  clientSecret: string;
  name: string;
};

export type ApiIntegrationModel = {
  clientId: string;
  name: string;
  description?: null | string;
  enabled?: boolean;
};

export type AppointmentModel = {
  id?: string;
  scheduledAt: Date;
  description?: null | string;
};

export type CreateApiIntegrationModel = {
  name: string;
  description?: null | string;
};

export type CreateOrUpdateAppointmentModel = {
  scheduledAt: Date;
  description?: null | string;
};

export type CreateOrUpdateDepartmentModel = {
  name: string;
  description?: null | string;
};

export type CreateOrUpdateItemAssignmentHistoryModel = {
  itemId: string;
  personId: string;
  assignedById: string;
  assignedFrom: Date;
  assignedUntil?: null | Date;
};

export type CreateOrUpdateItemModel = {
  variantId: string;
  identifier?: null | string;
  storageLocationId?: null | string;
  condition: ItemCondition;
  purchaseDate: Date;
  retirementDate?: null | Date;
};

export type CreateOrUpdateMaintenanceModel = {
  itemId: string;
  performedAt: Date;
  typeId: string;
  remarks?: null | string;
  performedById: string;
};

export type CreateOrUpdateMaintenanceTypeModel = {
  name: string;
  description?: null | string;
};

export type CreateOrUpdateManufacturerModel = {
  name: string;
  description?: null | string;
  street?: null | string;
  city?: null | string;
  postalCode?: null | string;
  houseNumber?: null | string;
  country?: null | string;
  website?: null | string;
  phoneNumber?: null | string;
  email?: null | string;
};

export type CreateOrUpdateOrderItemModel = {
  orderId: string;
  variantId: string;
  personId?: null | string;
  quantity: number | string;
};

export type CreateOrUpdateOrderModel = {
  orderIdentifier?: null | string;
  orderDate: Date;
  status: OrderStatus;
  deliveryDate?: null | Date;
};

export type CreateOrUpdatePersonModel = {
  firstName: string;
  lastName: string;
  remarks?: null | string;
  contactInfo?: null | string;
  externalId?: null | string;
  departmentIds?: Array<string>;
};

export type CreateOrUpdateProductModel = {
  name: string;
  manufacturerId: string;
  description?: null | string;
  externalIdentifier?: null | string;
  typeId: string;
};

export type CreateOrUpdateProductTypeModel = {
  name: string;
  description?: null | string;
};

export type CreateOrUpdateStorageLocationModel = {
  name: string;
  remarks?: null | string;
};

export type CreateOrUpdateTenantModel = {
  name: string;
  description?: null | string;
};

export type CreateOrUpdateVariantModel = {
  productId: string;
  name: string;
  additionalSpecs?: null | string;
  externalIdentifier?: null | string;
};

export type CreateOrUpdateVisitItemModel = {
  visitId: string;
  productId: string;
  quantity: number | string;
};

export type CreateOrUpdateVisitModel = {
  appointmentId: string;
  personId: string;
};

export type DepartmentModel = {
  id: string;
  name: string;
  description?: null | string;
};

export type ItemAssignmentHistoryModel = {
  id: string;
  person: PersonModel;
  item: ItemModel;
  itemId: string;
  personId: string;
  assignedById: string;
  assignedFrom: Date;
  assignedUntil?: null | Date;
};

export const ItemCondition = {
  NEW: "New",
  USED: "Used",
  DAMAGED: "Damaged",
  DESTROYED: "Destroyed",
  LOST: "Lost",
} as const;

export type ItemCondition = (typeof ItemCondition)[keyof typeof ItemCondition];

export type ItemModel = {
  id: string;
  variant: VariantModel;
  storageLocation?: null | StorageLocationModel;
  variantId: string;
  identifier?: null | string;
  storageLocationId?: null | string;
  condition: ItemCondition;
  purchaseDate: Date;
  retirementDate?: null | Date;
};

export type MaintenanceModel = {
  id: string;
  performedBy?: null | UserModel;
  type: MaintenanceTypeModel;
  itemId: string;
  performedAt: Date;
  typeId: string;
  remarks?: null | string;
  performedById: string;
};

export type MaintenanceTypeModel = {
  id: string;
  name: string;
  description?: null | string;
};

export type ManufacturerModel = {
  id: string;
  name: string;
  description?: null | string;
  street?: null | string;
  city?: null | string;
  postalCode?: null | string;
  houseNumber?: null | string;
  country?: null | string;
  website?: null | string;
  phoneNumber?: null | string;
  email?: null | string;
};

export type OrderItemModel = {
  id: string;
  variant: VariantModel;
  person?: null | PersonModel;
  orderId: string;
  variantId: string;
  personId?: null | string;
  quantity: number | string;
};

export type OrderModel = {
  id: string;
  orderIdentifier?: null | string;
  orderDate: Date;
  status: OrderStatus;
  deliveryDate?: null | Date;
};

export const OrderStatus = {
  DRAFT: "Draft",
  SUBMITTED: "Submitted",
  DELIVERED: "Delivered",
  COMPLETED: "Completed",
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export type PersonModel = {
  id: string;
  departments: Array<DepartmentModel>;
  firstName: string;
  lastName: string;
  remarks?: null | string;
  contactInfo?: null | string;
  externalId?: null | string;
  departmentIds?: Array<string>;
};

export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number | string;
  detail?: null | string;
  instance?: null | string;
};

export type ProductModel = {
  id: string;
  type: ProductTypeModel;
  manufacturer: ManufacturerModel;
  name: string;
  manufacturerId: string;
  description?: null | string;
  externalIdentifier?: null | string;
  typeId: string;
};

export type ProductTypeModel = {
  id: string;
  name: string;
  description?: null | string;
};

export type StorageLocationModel = {
  id: string;
  name: string;
  remarks?: null | string;
};

export type TenantModel = {
  id: string;
  createdAt: Date;
  name: string;
  description?: null | string;
};

export type UserModel = {
  id: string;
  eMail: string;
  firstName?: null | string;
  lastName?: null | string;
};

export type VariantModel = {
  id: string;
  product: ProductModel;
  productId: string;
  name: string;
  additionalSpecs?: null | string;
  externalIdentifier?: null | string;
};

export type VisitItemModel = {
  id: string;
  product: ProductModel;
  visitId: string;
  productId: string;
  quantity: number | string;
};

export type VisitModel = {
  id: string;
  appointment: AppointmentModel;
  person: PersonModel;
  appointmentId: string;
  personId: string;
};

export type GetApiIntegrationsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/api-integrations";
};

export type GetApiIntegrationsResponses = {
  /**
   * OK
   */
  200: Array<ApiIntegrationModel>;
};

export type GetApiIntegrationsResponse =
  GetApiIntegrationsResponses[keyof GetApiIntegrationsResponses];

export type PostApiIntegrationsData = {
  body: CreateApiIntegrationModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/api-integrations";
};

export type PostApiIntegrationsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostApiIntegrationsError =
  PostApiIntegrationsErrors[keyof PostApiIntegrationsErrors];

export type PostApiIntegrationsResponses = {
  /**
   * Created
   */
  201: ApiIntegrationCredentialsModel;
};

export type PostApiIntegrationsResponse =
  PostApiIntegrationsResponses[keyof PostApiIntegrationsResponses];

export type DeleteApiIntegrationsByClientIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    clientId: string;
  };
  query?: never;
  url: "/api-integrations/{clientId}";
};

export type DeleteApiIntegrationsByClientIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteApiIntegrationsByClientIdError =
  DeleteApiIntegrationsByClientIdErrors[keyof DeleteApiIntegrationsByClientIdErrors];

export type DeleteApiIntegrationsByClientIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiIntegrationsByClientIdResponse =
  DeleteApiIntegrationsByClientIdResponses[keyof DeleteApiIntegrationsByClientIdResponses];

export type GetAppointmentsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/appointments";
};

export type GetAppointmentsResponses = {
  /**
   * OK
   */
  200: Array<AppointmentModel>;
};

export type GetAppointmentsResponse =
  GetAppointmentsResponses[keyof GetAppointmentsResponses];

export type PostAppointmentsData = {
  body: CreateOrUpdateAppointmentModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/appointments";
};

export type PostAppointmentsResponses = {
  /**
   * Created
   */
  201: AppointmentModel;
};

export type PostAppointmentsResponse =
  PostAppointmentsResponses[keyof PostAppointmentsResponses];

export type DeleteAppointmentsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/appointments/{id}";
};

export type DeleteAppointmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteAppointmentsByIdError =
  DeleteAppointmentsByIdErrors[keyof DeleteAppointmentsByIdErrors];

export type DeleteAppointmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAppointmentsByIdResponse =
  DeleteAppointmentsByIdResponses[keyof DeleteAppointmentsByIdResponses];

export type GetAppointmentsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/appointments/{id}";
};

export type GetAppointmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetAppointmentsByIdError =
  GetAppointmentsByIdErrors[keyof GetAppointmentsByIdErrors];

export type GetAppointmentsByIdResponses = {
  /**
   * OK
   */
  200: AppointmentModel;
};

export type GetAppointmentsByIdResponse =
  GetAppointmentsByIdResponses[keyof GetAppointmentsByIdResponses];

export type PutAppointmentsByIdData = {
  body: CreateOrUpdateAppointmentModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/appointments/{id}";
};

export type PutAppointmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutAppointmentsByIdError =
  PutAppointmentsByIdErrors[keyof PutAppointmentsByIdErrors];

export type PutAppointmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutAppointmentsByIdResponse =
  PutAppointmentsByIdResponses[keyof PutAppointmentsByIdResponses];

export type GetAppointmentsByIdVisitsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/appointments/{id}/visits";
};

export type GetAppointmentsByIdVisitsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetAppointmentsByIdVisitsError =
  GetAppointmentsByIdVisitsErrors[keyof GetAppointmentsByIdVisitsErrors];

export type GetAppointmentsByIdVisitsResponses = {
  /**
   * OK
   */
  200: Array<VisitModel>;
};

export type GetAppointmentsByIdVisitsResponse =
  GetAppointmentsByIdVisitsResponses[keyof GetAppointmentsByIdVisitsResponses];

export type GetDepartmentsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/departments";
};

export type GetDepartmentsResponses = {
  /**
   * OK
   */
  200: Array<DepartmentModel>;
};

export type GetDepartmentsResponse =
  GetDepartmentsResponses[keyof GetDepartmentsResponses];

export type PostDepartmentsData = {
  body: CreateOrUpdateDepartmentModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/departments";
};

export type PostDepartmentsResponses = {
  /**
   * Created
   */
  201: DepartmentModel;
};

export type PostDepartmentsResponse =
  PostDepartmentsResponses[keyof PostDepartmentsResponses];

export type DeleteDepartmentsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type DeleteDepartmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteDepartmentsByIdError =
  DeleteDepartmentsByIdErrors[keyof DeleteDepartmentsByIdErrors];

export type DeleteDepartmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteDepartmentsByIdResponse =
  DeleteDepartmentsByIdResponses[keyof DeleteDepartmentsByIdResponses];

export type GetDepartmentsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type GetDepartmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetDepartmentsByIdError =
  GetDepartmentsByIdErrors[keyof GetDepartmentsByIdErrors];

export type GetDepartmentsByIdResponses = {
  /**
   * OK
   */
  200: DepartmentModel;
};

export type GetDepartmentsByIdResponse =
  GetDepartmentsByIdResponses[keyof GetDepartmentsByIdResponses];

export type PutDepartmentsByIdData = {
  body: CreateOrUpdateDepartmentModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type PutDepartmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutDepartmentsByIdError =
  PutDepartmentsByIdErrors[keyof PutDepartmentsByIdErrors];

export type PutDepartmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutDepartmentsByIdResponse =
  PutDepartmentsByIdResponses[keyof PutDepartmentsByIdResponses];

export type GetDepartmentsByIdPersonsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}/persons";
};

export type GetDepartmentsByIdPersonsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetDepartmentsByIdPersonsError =
  GetDepartmentsByIdPersonsErrors[keyof GetDepartmentsByIdPersonsErrors];

export type GetDepartmentsByIdPersonsResponses = {
  /**
   * OK
   */
  200: Array<PersonModel>;
};

export type GetDepartmentsByIdPersonsResponse =
  GetDepartmentsByIdPersonsResponses[keyof GetDepartmentsByIdPersonsResponses];

export type GetAssignmentsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/assignments";
};

export type GetAssignmentsResponses = {
  /**
   * OK
   */
  200: Array<ItemAssignmentHistoryModel>;
};

export type GetAssignmentsResponse =
  GetAssignmentsResponses[keyof GetAssignmentsResponses];

export type PostAssignmentsData = {
  body: CreateOrUpdateItemAssignmentHistoryModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/assignments";
};

export type PostAssignmentsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostAssignmentsError =
  PostAssignmentsErrors[keyof PostAssignmentsErrors];

export type PostAssignmentsResponses = {
  /**
   * Created
   */
  201: ItemAssignmentHistoryModel;
};

export type PostAssignmentsResponse =
  PostAssignmentsResponses[keyof PostAssignmentsResponses];

export type DeleteAssignmentsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/assignments/{id}";
};

export type DeleteAssignmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteAssignmentsByIdError =
  DeleteAssignmentsByIdErrors[keyof DeleteAssignmentsByIdErrors];

export type DeleteAssignmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAssignmentsByIdResponse =
  DeleteAssignmentsByIdResponses[keyof DeleteAssignmentsByIdResponses];

export type GetAssignmentsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/assignments/{id}";
};

export type GetAssignmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetAssignmentsByIdError =
  GetAssignmentsByIdErrors[keyof GetAssignmentsByIdErrors];

export type GetAssignmentsByIdResponses = {
  /**
   * OK
   */
  200: ItemAssignmentHistoryModel;
};

export type GetAssignmentsByIdResponse =
  GetAssignmentsByIdResponses[keyof GetAssignmentsByIdResponses];

export type PutAssignmentsByIdData = {
  body: CreateOrUpdateItemAssignmentHistoryModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/assignments/{id}";
};

export type PutAssignmentsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutAssignmentsByIdError =
  PutAssignmentsByIdErrors[keyof PutAssignmentsByIdErrors];

export type PutAssignmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutAssignmentsByIdResponse =
  PutAssignmentsByIdResponses[keyof PutAssignmentsByIdResponses];

export type GetItemsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/items";
};

export type GetItemsResponses = {
  /**
   * OK
   */
  200: Array<ItemModel>;
};

export type GetItemsResponse = GetItemsResponses[keyof GetItemsResponses];

export type PostItemsData = {
  body: CreateOrUpdateItemModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/items";
};

export type PostItemsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostItemsError = PostItemsErrors[keyof PostItemsErrors];

export type PostItemsResponses = {
  /**
   * Created
   */
  201: ItemModel;
};

export type PostItemsResponse = PostItemsResponses[keyof PostItemsResponses];

export type DeleteItemsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type DeleteItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteItemsByIdError =
  DeleteItemsByIdErrors[keyof DeleteItemsByIdErrors];

export type DeleteItemsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteItemsByIdResponse =
  DeleteItemsByIdResponses[keyof DeleteItemsByIdResponses];

export type GetItemsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type GetItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetItemsByIdError = GetItemsByIdErrors[keyof GetItemsByIdErrors];

export type GetItemsByIdResponses = {
  /**
   * OK
   */
  200: ItemModel;
};

export type GetItemsByIdResponse =
  GetItemsByIdResponses[keyof GetItemsByIdResponses];

export type PutItemsByIdData = {
  body: CreateOrUpdateItemModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type PutItemsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutItemsByIdError = PutItemsByIdErrors[keyof PutItemsByIdErrors];

export type PutItemsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutItemsByIdResponse =
  PutItemsByIdResponses[keyof PutItemsByIdResponses];

export type GetItemsByIdAssignmentsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}/assignments";
};

export type GetItemsByIdAssignmentsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetItemsByIdAssignmentsError =
  GetItemsByIdAssignmentsErrors[keyof GetItemsByIdAssignmentsErrors];

export type GetItemsByIdAssignmentsResponses = {
  /**
   * OK
   */
  200: Array<ItemAssignmentHistoryModel>;
};

export type GetItemsByIdAssignmentsResponse =
  GetItemsByIdAssignmentsResponses[keyof GetItemsByIdAssignmentsResponses];

export type GetItemsByIdMaintenanceData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}/maintenance";
};

export type GetItemsByIdMaintenanceErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetItemsByIdMaintenanceError =
  GetItemsByIdMaintenanceErrors[keyof GetItemsByIdMaintenanceErrors];

export type GetItemsByIdMaintenanceResponses = {
  /**
   * OK
   */
  200: Array<MaintenanceModel>;
};

export type GetItemsByIdMaintenanceResponse =
  GetItemsByIdMaintenanceResponses[keyof GetItemsByIdMaintenanceResponses];

export type GetMaintenancesData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/maintenances";
};

export type GetMaintenancesResponses = {
  /**
   * OK
   */
  200: Array<MaintenanceModel>;
};

export type GetMaintenancesResponse =
  GetMaintenancesResponses[keyof GetMaintenancesResponses];

export type PostMaintenancesData = {
  body: CreateOrUpdateMaintenanceModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/maintenances";
};

export type PostMaintenancesErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostMaintenancesError =
  PostMaintenancesErrors[keyof PostMaintenancesErrors];

export type PostMaintenancesResponses = {
  /**
   * Created
   */
  201: MaintenanceModel;
};

export type PostMaintenancesResponse =
  PostMaintenancesResponses[keyof PostMaintenancesResponses];

export type DeleteMaintenancesByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenances/{id}";
};

export type DeleteMaintenancesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteMaintenancesByIdError =
  DeleteMaintenancesByIdErrors[keyof DeleteMaintenancesByIdErrors];

export type DeleteMaintenancesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteMaintenancesByIdResponse =
  DeleteMaintenancesByIdResponses[keyof DeleteMaintenancesByIdResponses];

export type GetMaintenancesByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenances/{id}";
};

export type GetMaintenancesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetMaintenancesByIdError =
  GetMaintenancesByIdErrors[keyof GetMaintenancesByIdErrors];

export type GetMaintenancesByIdResponses = {
  /**
   * OK
   */
  200: MaintenanceModel;
};

export type GetMaintenancesByIdResponse =
  GetMaintenancesByIdResponses[keyof GetMaintenancesByIdResponses];

export type PutMaintenancesByIdData = {
  body: CreateOrUpdateMaintenanceModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenances/{id}";
};

export type PutMaintenancesByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutMaintenancesByIdError =
  PutMaintenancesByIdErrors[keyof PutMaintenancesByIdErrors];

export type PutMaintenancesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutMaintenancesByIdResponse =
  PutMaintenancesByIdResponses[keyof PutMaintenancesByIdResponses];

export type GetMaintenanceTypesData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/maintenance-types";
};

export type GetMaintenanceTypesResponses = {
  /**
   * OK
   */
  200: Array<MaintenanceTypeModel>;
};

export type GetMaintenanceTypesResponse =
  GetMaintenanceTypesResponses[keyof GetMaintenanceTypesResponses];

export type PostMaintenanceTypesData = {
  body: CreateOrUpdateMaintenanceTypeModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/maintenance-types";
};

export type PostMaintenanceTypesResponses = {
  /**
   * Created
   */
  201: MaintenanceTypeModel;
};

export type PostMaintenanceTypesResponse =
  PostMaintenanceTypesResponses[keyof PostMaintenanceTypesResponses];

export type DeleteMaintenanceTypesByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenance-types/{id}";
};

export type DeleteMaintenanceTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteMaintenanceTypesByIdError =
  DeleteMaintenanceTypesByIdErrors[keyof DeleteMaintenanceTypesByIdErrors];

export type DeleteMaintenanceTypesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteMaintenanceTypesByIdResponse =
  DeleteMaintenanceTypesByIdResponses[keyof DeleteMaintenanceTypesByIdResponses];

export type GetMaintenanceTypesByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenance-types/{id}";
};

export type GetMaintenanceTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetMaintenanceTypesByIdError =
  GetMaintenanceTypesByIdErrors[keyof GetMaintenanceTypesByIdErrors];

export type GetMaintenanceTypesByIdResponses = {
  /**
   * OK
   */
  200: MaintenanceTypeModel;
};

export type GetMaintenanceTypesByIdResponse =
  GetMaintenanceTypesByIdResponses[keyof GetMaintenanceTypesByIdResponses];

export type PutMaintenanceTypesByIdData = {
  body: CreateOrUpdateMaintenanceTypeModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenance-types/{id}";
};

export type PutMaintenanceTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutMaintenanceTypesByIdError =
  PutMaintenanceTypesByIdErrors[keyof PutMaintenanceTypesByIdErrors];

export type PutMaintenanceTypesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutMaintenanceTypesByIdResponse =
  PutMaintenanceTypesByIdResponses[keyof PutMaintenanceTypesByIdResponses];

export type GetManufacturersData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/manufacturers";
};

export type GetManufacturersResponses = {
  /**
   * OK
   */
  200: Array<ManufacturerModel>;
};

export type GetManufacturersResponse =
  GetManufacturersResponses[keyof GetManufacturersResponses];

export type PostManufacturersData = {
  body: CreateOrUpdateManufacturerModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/manufacturers";
};

export type PostManufacturersResponses = {
  /**
   * Created
   */
  201: ManufacturerModel;
};

export type PostManufacturersResponse =
  PostManufacturersResponses[keyof PostManufacturersResponses];

export type DeleteManufacturersByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/manufacturers/{id}";
};

export type DeleteManufacturersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteManufacturersByIdError =
  DeleteManufacturersByIdErrors[keyof DeleteManufacturersByIdErrors];

export type DeleteManufacturersByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteManufacturersByIdResponse =
  DeleteManufacturersByIdResponses[keyof DeleteManufacturersByIdResponses];

export type GetManufacturersByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/manufacturers/{id}";
};

export type GetManufacturersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetManufacturersByIdError =
  GetManufacturersByIdErrors[keyof GetManufacturersByIdErrors];

export type GetManufacturersByIdResponses = {
  /**
   * OK
   */
  200: ManufacturerModel;
};

export type GetManufacturersByIdResponse =
  GetManufacturersByIdResponses[keyof GetManufacturersByIdResponses];

export type PutManufacturersByIdData = {
  body: CreateOrUpdateManufacturerModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/manufacturers/{id}";
};

export type PutManufacturersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutManufacturersByIdError =
  PutManufacturersByIdErrors[keyof PutManufacturersByIdErrors];

export type PutManufacturersByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutManufacturersByIdResponse =
  PutManufacturersByIdResponses[keyof PutManufacturersByIdResponses];

export type GetManufacturersByIdProductsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/manufacturers/{id}/products";
};

export type GetManufacturersByIdProductsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetManufacturersByIdProductsError =
  GetManufacturersByIdProductsErrors[keyof GetManufacturersByIdProductsErrors];

export type GetManufacturersByIdProductsResponses = {
  /**
   * OK
   */
  200: Array<ProductModel>;
};

export type GetManufacturersByIdProductsResponse =
  GetManufacturersByIdProductsResponses[keyof GetManufacturersByIdProductsResponses];

export type GetOrdersData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/orders";
};

export type GetOrdersResponses = {
  /**
   * OK
   */
  200: Array<OrderModel>;
};

export type GetOrdersResponse = GetOrdersResponses[keyof GetOrdersResponses];

export type PostOrdersData = {
  body: CreateOrUpdateOrderModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/orders";
};

export type PostOrdersResponses = {
  /**
   * Created
   */
  201: OrderModel;
};

export type PostOrdersResponse = PostOrdersResponses[keyof PostOrdersResponses];

export type DeleteOrdersByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/orders/{id}";
};

export type DeleteOrdersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteOrdersByIdError =
  DeleteOrdersByIdErrors[keyof DeleteOrdersByIdErrors];

export type DeleteOrdersByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteOrdersByIdResponse =
  DeleteOrdersByIdResponses[keyof DeleteOrdersByIdResponses];

export type GetOrdersByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/orders/{id}";
};

export type GetOrdersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetOrdersByIdError = GetOrdersByIdErrors[keyof GetOrdersByIdErrors];

export type GetOrdersByIdResponses = {
  /**
   * OK
   */
  200: OrderModel;
};

export type GetOrdersByIdResponse =
  GetOrdersByIdResponses[keyof GetOrdersByIdResponses];

export type PutOrdersByIdData = {
  body: CreateOrUpdateOrderModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/orders/{id}";
};

export type PutOrdersByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutOrdersByIdError = PutOrdersByIdErrors[keyof PutOrdersByIdErrors];

export type PutOrdersByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutOrdersByIdResponse =
  PutOrdersByIdResponses[keyof PutOrdersByIdResponses];

export type GetOrderItemsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/order-items";
};

export type GetOrderItemsResponses = {
  /**
   * OK
   */
  200: Array<OrderItemModel>;
};

export type GetOrderItemsResponse =
  GetOrderItemsResponses[keyof GetOrderItemsResponses];

export type PostOrderItemsData = {
  body: CreateOrUpdateOrderItemModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/order-items";
};

export type PostOrderItemsResponses = {
  /**
   * Created
   */
  201: OrderItemModel;
};

export type PostOrderItemsResponse =
  PostOrderItemsResponses[keyof PostOrderItemsResponses];

export type GetOrderItemsByOrderByOrderIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    orderId: string;
  };
  query?: never;
  url: "/order-items/by-order/{orderId}";
};

export type GetOrderItemsByOrderByOrderIdResponses = {
  /**
   * OK
   */
  200: Array<OrderItemModel>;
};

export type GetOrderItemsByOrderByOrderIdResponse =
  GetOrderItemsByOrderByOrderIdResponses[keyof GetOrderItemsByOrderByOrderIdResponses];

export type DeleteOrderItemsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/order-items/{id}";
};

export type DeleteOrderItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteOrderItemsByIdError =
  DeleteOrderItemsByIdErrors[keyof DeleteOrderItemsByIdErrors];

export type DeleteOrderItemsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteOrderItemsByIdResponse =
  DeleteOrderItemsByIdResponses[keyof DeleteOrderItemsByIdResponses];

export type GetOrderItemsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/order-items/{id}";
};

export type GetOrderItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetOrderItemsByIdError =
  GetOrderItemsByIdErrors[keyof GetOrderItemsByIdErrors];

export type GetOrderItemsByIdResponses = {
  /**
   * OK
   */
  200: OrderItemModel;
};

export type GetOrderItemsByIdResponse =
  GetOrderItemsByIdResponses[keyof GetOrderItemsByIdResponses];

export type PutOrderItemsByIdData = {
  body: CreateOrUpdateOrderItemModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/order-items/{id}";
};

export type PutOrderItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutOrderItemsByIdError =
  PutOrderItemsByIdErrors[keyof PutOrderItemsByIdErrors];

export type PutOrderItemsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutOrderItemsByIdResponse =
  PutOrderItemsByIdResponses[keyof PutOrderItemsByIdResponses];

export type GetPersonsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/persons";
};

export type GetPersonsResponses = {
  /**
   * OK
   */
  200: Array<PersonModel>;
};

export type GetPersonsResponse = GetPersonsResponses[keyof GetPersonsResponses];

export type PostPersonsData = {
  body: CreateOrUpdatePersonModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/persons";
};

export type PostPersonsErrors = {
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostPersonsError = PostPersonsErrors[keyof PostPersonsErrors];

export type PostPersonsResponses = {
  /**
   * Created
   */
  201: PersonModel;
};

export type PostPersonsResponse =
  PostPersonsResponses[keyof PostPersonsResponses];

export type DeletePersonsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}";
};

export type DeletePersonsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeletePersonsByIdError =
  DeletePersonsByIdErrors[keyof DeletePersonsByIdErrors];

export type DeletePersonsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeletePersonsByIdResponse =
  DeletePersonsByIdResponses[keyof DeletePersonsByIdResponses];

export type GetPersonsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}";
};

export type GetPersonsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetPersonsByIdError =
  GetPersonsByIdErrors[keyof GetPersonsByIdErrors];

export type GetPersonsByIdResponses = {
  /**
   * OK
   */
  200: PersonModel;
};

export type GetPersonsByIdResponse =
  GetPersonsByIdResponses[keyof GetPersonsByIdResponses];

export type PutPersonsByIdData = {
  body: CreateOrUpdatePersonModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}";
};

export type PutPersonsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutPersonsByIdError =
  PutPersonsByIdErrors[keyof PutPersonsByIdErrors];

export type PutPersonsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutPersonsByIdResponse =
  PutPersonsByIdResponses[keyof PutPersonsByIdResponses];

export type GetPersonsByIdAssignmentsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}/assignments";
};

export type GetPersonsByIdAssignmentsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetPersonsByIdAssignmentsError =
  GetPersonsByIdAssignmentsErrors[keyof GetPersonsByIdAssignmentsErrors];

export type GetPersonsByIdAssignmentsResponses = {
  /**
   * OK
   */
  200: Array<ItemAssignmentHistoryModel>;
};

export type GetPersonsByIdAssignmentsResponse =
  GetPersonsByIdAssignmentsResponses[keyof GetPersonsByIdAssignmentsResponses];

export type GetProductsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/products";
};

export type GetProductsResponses = {
  /**
   * OK
   */
  200: Array<ProductModel>;
};

export type GetProductsResponse =
  GetProductsResponses[keyof GetProductsResponses];

export type PostProductsData = {
  body: CreateOrUpdateProductModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/products";
};

export type PostProductsErrors = {
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostProductsError = PostProductsErrors[keyof PostProductsErrors];

export type PostProductsResponses = {
  /**
   * Created
   */
  201: ProductModel;
};

export type PostProductsResponse =
  PostProductsResponses[keyof PostProductsResponses];

export type DeleteProductsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}";
};

export type DeleteProductsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteProductsByIdError =
  DeleteProductsByIdErrors[keyof DeleteProductsByIdErrors];

export type DeleteProductsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteProductsByIdResponse =
  DeleteProductsByIdResponses[keyof DeleteProductsByIdResponses];

export type GetProductsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}";
};

export type GetProductsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetProductsByIdError =
  GetProductsByIdErrors[keyof GetProductsByIdErrors];

export type GetProductsByIdResponses = {
  /**
   * OK
   */
  200: ProductModel;
};

export type GetProductsByIdResponse =
  GetProductsByIdResponses[keyof GetProductsByIdResponses];

export type PutProductsByIdData = {
  body: CreateOrUpdateProductModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}";
};

export type PutProductsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutProductsByIdError =
  PutProductsByIdErrors[keyof PutProductsByIdErrors];

export type PutProductsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutProductsByIdResponse =
  PutProductsByIdResponses[keyof PutProductsByIdResponses];

export type GetProductsByIdVariantsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}/variants";
};

export type GetProductsByIdVariantsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetProductsByIdVariantsError =
  GetProductsByIdVariantsErrors[keyof GetProductsByIdVariantsErrors];

export type GetProductsByIdVariantsResponses = {
  /**
   * OK
   */
  200: Array<VariantModel>;
};

export type GetProductsByIdVariantsResponse =
  GetProductsByIdVariantsResponses[keyof GetProductsByIdVariantsResponses];

export type GetProductTypesData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/product-types";
};

export type GetProductTypesResponses = {
  /**
   * OK
   */
  200: Array<ProductTypeModel>;
};

export type GetProductTypesResponse =
  GetProductTypesResponses[keyof GetProductTypesResponses];

export type PostProductTypesData = {
  body: CreateOrUpdateProductTypeModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/product-types";
};

export type PostProductTypesResponses = {
  /**
   * Created
   */
  201: ProductTypeModel;
};

export type PostProductTypesResponse =
  PostProductTypesResponses[keyof PostProductTypesResponses];

export type DeleteProductTypesByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/product-types/{id}";
};

export type DeleteProductTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteProductTypesByIdError =
  DeleteProductTypesByIdErrors[keyof DeleteProductTypesByIdErrors];

export type DeleteProductTypesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteProductTypesByIdResponse =
  DeleteProductTypesByIdResponses[keyof DeleteProductTypesByIdResponses];

export type GetProductTypesByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/product-types/{id}";
};

export type GetProductTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetProductTypesByIdError =
  GetProductTypesByIdErrors[keyof GetProductTypesByIdErrors];

export type GetProductTypesByIdResponses = {
  /**
   * OK
   */
  200: ProductTypeModel;
};

export type GetProductTypesByIdResponse =
  GetProductTypesByIdResponses[keyof GetProductTypesByIdResponses];

export type PutProductTypesByIdData = {
  body: CreateOrUpdateProductTypeModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/product-types/{id}";
};

export type PutProductTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutProductTypesByIdError =
  PutProductTypesByIdErrors[keyof PutProductTypesByIdErrors];

export type PutProductTypesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutProductTypesByIdResponse =
  PutProductTypesByIdResponses[keyof PutProductTypesByIdResponses];

export type GetStorageLocationsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/storage-locations";
};

export type GetStorageLocationsResponses = {
  /**
   * OK
   */
  200: Array<StorageLocationModel>;
};

export type GetStorageLocationsResponse =
  GetStorageLocationsResponses[keyof GetStorageLocationsResponses];

export type PostStorageLocationsData = {
  body: CreateOrUpdateStorageLocationModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/storage-locations";
};

export type PostStorageLocationsErrors = {
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostStorageLocationsError =
  PostStorageLocationsErrors[keyof PostStorageLocationsErrors];

export type PostStorageLocationsResponses = {
  /**
   * Created
   */
  201: StorageLocationModel;
};

export type PostStorageLocationsResponse =
  PostStorageLocationsResponses[keyof PostStorageLocationsResponses];

export type DeleteStorageLocationsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/storage-locations/{id}";
};

export type DeleteStorageLocationsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteStorageLocationsByIdError =
  DeleteStorageLocationsByIdErrors[keyof DeleteStorageLocationsByIdErrors];

export type DeleteStorageLocationsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteStorageLocationsByIdResponse =
  DeleteStorageLocationsByIdResponses[keyof DeleteStorageLocationsByIdResponses];

export type GetStorageLocationsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/storage-locations/{id}";
};

export type GetStorageLocationsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetStorageLocationsByIdError =
  GetStorageLocationsByIdErrors[keyof GetStorageLocationsByIdErrors];

export type GetStorageLocationsByIdResponses = {
  /**
   * OK
   */
  200: StorageLocationModel;
};

export type GetStorageLocationsByIdResponse =
  GetStorageLocationsByIdResponses[keyof GetStorageLocationsByIdResponses];

export type PutStorageLocationsByIdData = {
  body: CreateOrUpdateStorageLocationModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/storage-locations/{id}";
};

export type PutStorageLocationsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutStorageLocationsByIdError =
  PutStorageLocationsByIdErrors[keyof PutStorageLocationsByIdErrors];

export type PutStorageLocationsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutStorageLocationsByIdResponse =
  PutStorageLocationsByIdResponses[keyof PutStorageLocationsByIdResponses];

export type GetStorageLocationsByIdItemsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/storage-locations/{id}/items";
};

export type GetStorageLocationsByIdItemsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetStorageLocationsByIdItemsError =
  GetStorageLocationsByIdItemsErrors[keyof GetStorageLocationsByIdItemsErrors];

export type GetStorageLocationsByIdItemsResponses = {
  /**
   * OK
   */
  200: Array<ItemModel>;
};

export type GetStorageLocationsByIdItemsResponse =
  GetStorageLocationsByIdItemsResponses[keyof GetStorageLocationsByIdItemsResponses];

export type GetTenantsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/tenants";
};

export type GetTenantsResponses = {
  /**
   * OK
   */
  200: Array<TenantModel>;
};

export type GetTenantsResponse = GetTenantsResponses[keyof GetTenantsResponses];

export type PostTenantsData = {
  body: CreateOrUpdateTenantModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/tenants";
};

export type PostTenantsErrors = {
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostTenantsError = PostTenantsErrors[keyof PostTenantsErrors];

export type PostTenantsResponses = {
  /**
   * Created
   */
  201: TenantModel;
};

export type PostTenantsResponse =
  PostTenantsResponses[keyof PostTenantsResponses];

export type DeleteTenantsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/tenants/{id}";
};

export type DeleteTenantsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type DeleteTenantsByIdError =
  DeleteTenantsByIdErrors[keyof DeleteTenantsByIdErrors];

export type DeleteTenantsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteTenantsByIdResponse =
  DeleteTenantsByIdResponses[keyof DeleteTenantsByIdResponses];

export type GetTenantsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/tenants/{id}";
};

export type GetTenantsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetTenantsByIdError =
  GetTenantsByIdErrors[keyof GetTenantsByIdErrors];

export type GetTenantsByIdResponses = {
  /**
   * OK
   */
  200: TenantModel;
};

export type GetTenantsByIdResponse =
  GetTenantsByIdResponses[keyof GetTenantsByIdResponses];

export type PutTenantsByIdData = {
  body: CreateOrUpdateTenantModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/tenants/{id}";
};

export type PutTenantsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutTenantsByIdError =
  PutTenantsByIdErrors[keyof PutTenantsByIdErrors];

export type PutTenantsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutTenantsByIdResponse =
  PutTenantsByIdResponses[keyof PutTenantsByIdResponses];

export type GetUsersData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/users";
};

export type GetUsersResponses = {
  /**
   * OK
   */
  200: Array<UserModel>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUsersByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type GetUsersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
  /**
   * OK
   */
  200: UserModel;
};

export type GetUsersByIdResponse =
  GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type GetVariantsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/variants";
};

export type GetVariantsResponses = {
  /**
   * OK
   */
  200: Array<VariantModel>;
};

export type GetVariantsResponse =
  GetVariantsResponses[keyof GetVariantsResponses];

export type PostVariantsData = {
  body: CreateOrUpdateVariantModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/variants";
};

export type PostVariantsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostVariantsError = PostVariantsErrors[keyof PostVariantsErrors];

export type PostVariantsResponses = {
  /**
   * Created
   */
  201: VariantModel;
};

export type PostVariantsResponse =
  PostVariantsResponses[keyof PostVariantsResponses];

export type DeleteVariantsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}";
};

export type DeleteVariantsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteVariantsByIdError =
  DeleteVariantsByIdErrors[keyof DeleteVariantsByIdErrors];

export type DeleteVariantsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteVariantsByIdResponse =
  DeleteVariantsByIdResponses[keyof DeleteVariantsByIdResponses];

export type GetVariantsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}";
};

export type GetVariantsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetVariantsByIdError =
  GetVariantsByIdErrors[keyof GetVariantsByIdErrors];

export type GetVariantsByIdResponses = {
  /**
   * OK
   */
  200: VariantModel;
};

export type GetVariantsByIdResponse =
  GetVariantsByIdResponses[keyof GetVariantsByIdResponses];

export type PutVariantsByIdData = {
  body: CreateOrUpdateVariantModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}";
};

export type PutVariantsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutVariantsByIdError =
  PutVariantsByIdErrors[keyof PutVariantsByIdErrors];

export type PutVariantsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutVariantsByIdResponse =
  PutVariantsByIdResponses[keyof PutVariantsByIdResponses];

export type GetVariantsByIdItemsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}/items";
};

export type GetVariantsByIdItemsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetVariantsByIdItemsError =
  GetVariantsByIdItemsErrors[keyof GetVariantsByIdItemsErrors];

export type GetVariantsByIdItemsResponses = {
  /**
   * OK
   */
  200: Array<ItemModel>;
};

export type GetVariantsByIdItemsResponse =
  GetVariantsByIdItemsResponses[keyof GetVariantsByIdItemsResponses];

export type GetVisitItemsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/visit-items";
};

export type GetVisitItemsResponses = {
  /**
   * OK
   */
  200: Array<VisitItemModel>;
};

export type GetVisitItemsResponse =
  GetVisitItemsResponses[keyof GetVisitItemsResponses];

export type PostVisitItemsData = {
  body: CreateOrUpdateVisitItemModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/visit-items";
};

export type PostVisitItemsResponses = {
  /**
   * Created
   */
  201: VisitItemModel;
};

export type PostVisitItemsResponse =
  PostVisitItemsResponses[keyof PostVisitItemsResponses];

export type GetVisitItemsByVisitByVisitIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    visitId: string;
  };
  query?: never;
  url: "/visit-items/by-visit/{visitId}";
};

export type GetVisitItemsByVisitByVisitIdResponses = {
  /**
   * OK
   */
  200: Array<VisitItemModel>;
};

export type GetVisitItemsByVisitByVisitIdResponse =
  GetVisitItemsByVisitByVisitIdResponses[keyof GetVisitItemsByVisitByVisitIdResponses];

export type DeleteVisitItemsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/visit-items/{id}";
};

export type DeleteVisitItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteVisitItemsByIdError =
  DeleteVisitItemsByIdErrors[keyof DeleteVisitItemsByIdErrors];

export type DeleteVisitItemsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteVisitItemsByIdResponse =
  DeleteVisitItemsByIdResponses[keyof DeleteVisitItemsByIdResponses];

export type GetVisitItemsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/visit-items/{id}";
};

export type GetVisitItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetVisitItemsByIdError =
  GetVisitItemsByIdErrors[keyof GetVisitItemsByIdErrors];

export type GetVisitItemsByIdResponses = {
  /**
   * OK
   */
  200: VisitItemModel;
};

export type GetVisitItemsByIdResponse =
  GetVisitItemsByIdResponses[keyof GetVisitItemsByIdResponses];

export type PutVisitItemsByIdData = {
  body: CreateOrUpdateVisitItemModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/visit-items/{id}";
};

export type PutVisitItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutVisitItemsByIdError =
  PutVisitItemsByIdErrors[keyof PutVisitItemsByIdErrors];

export type PutVisitItemsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutVisitItemsByIdResponse =
  PutVisitItemsByIdResponses[keyof PutVisitItemsByIdResponses];

export type GetVisitsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/visits";
};

export type GetVisitsResponses = {
  /**
   * OK
   */
  200: Array<VisitModel>;
};

export type GetVisitsResponse = GetVisitsResponses[keyof GetVisitsResponses];

export type PostVisitsData = {
  body: CreateOrUpdateVisitModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path?: never;
  query?: never;
  url: "/visits";
};

export type PostVisitsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostVisitsError = PostVisitsErrors[keyof PostVisitsErrors];

export type PostVisitsResponses = {
  /**
   * Created
   */
  201: VisitModel;
};

export type PostVisitsResponse = PostVisitsResponses[keyof PostVisitsResponses];

export type DeleteVisitsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/visits/{id}";
};

export type DeleteVisitsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteVisitsByIdError =
  DeleteVisitsByIdErrors[keyof DeleteVisitsByIdErrors];

export type DeleteVisitsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteVisitsByIdResponse =
  DeleteVisitsByIdResponses[keyof DeleteVisitsByIdResponses];

export type GetVisitsByIdData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/visits/{id}";
};

export type GetVisitsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetVisitsByIdError = GetVisitsByIdErrors[keyof GetVisitsByIdErrors];

export type GetVisitsByIdResponses = {
  /**
   * OK
   */
  200: VisitModel;
};

export type GetVisitsByIdResponse =
  GetVisitsByIdResponses[keyof GetVisitsByIdResponses];

export type PutVisitsByIdData = {
  body: CreateOrUpdateVisitModel;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/visits/{id}";
};

export type PutVisitsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutVisitsByIdError = PutVisitsByIdErrors[keyof PutVisitsByIdErrors];

export type PutVisitsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutVisitsByIdResponse =
  PutVisitsByIdResponses[keyof PutVisitsByIdResponses];

export type GetVisitsByIdItemsData = {
  body?: never;
  headers?: {
    /**
     * Tenant-ID (Required if multiple organzations included in JWT). To be able to use Tenant-Admin-API set Guid.Empty as Tenant-ID.
     */
    "X-Tenant-ID"?: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/visits/{id}/items";
};

export type GetVisitsByIdItemsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetVisitsByIdItemsError =
  GetVisitsByIdItemsErrors[keyof GetVisitsByIdItemsErrors];

export type GetVisitsByIdItemsResponses = {
  /**
   * OK
   */
  200: Array<VisitItemModel>;
};

export type GetVisitsByIdItemsResponse =
  GetVisitsByIdItemsResponses[keyof GetVisitsByIdItemsResponses];
