// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

export type CreateDepartmentModel = {
  name: string;
  description?: string | null;
};

export type CreateItemAssignmentHistoryModel = {
  itemId: string;
  personId: string;
  assignedFrom: Date;
  assignedUntil?: Date | null;
  assignedById?: string | null;
};

export type CreateItemModel = {
  variantId: string;
  identifier?: string | null;
  storageLocationId?: string | null;
  condition: ItemCondition;
  purchaseDate: Date;
  retirementDate?: Date | null;
};

export type CreateMaintenanceModel = {
  itemId: string;
  performedAt: Date;
  typeId: string;
  remarks?: string | null;
  performedById?: string | null;
};

export type CreateMaintenanceTypeModel = {
  name: string;
  description?: string | null;
};

export type CreateOrderItemModel = {
  orderId: string;
  variantId: string;
  quantity: number;
};

export type CreateOrderModel = {
  orderIdentifier?: string | null;
  orderDate: Date;
  status: OrderStatus;
  items: Array<CreateOrderItemModel>;
  deliveryDate?: Date | null;
};

export type CreatePersonModel = {
  firstName: string;
  lastName: string;
  remarks?: string | null;
  contactInfo?: string | null;
  externalId?: string | null;
};

export type CreateProductModel = {
  name: string;
  manufacturer: string;
  description?: string | null;
  typeId: string;
};

export type CreateProductTypeModel = {
  name: string;
  description?: string | null;
};

export type CreateStorageLocationModel = {
  name: string;
  remarks?: string | null;
};

export type CreateVariantModel = {
  productId: string;
  name: string;
  additionalSpecs?: string | null;
};

export type DepartmentModel = {
  name: string;
  description?: string | null;
  id: string;
};

export type ItemAssignmentHistoryModel = {
  itemId: string;
  personId: string;
  assignedFrom: Date;
  assignedUntil?: Date | null;
  assignedById?: string | null;
  id: string;
  assignedBy?: UserModel;
};

export const ItemCondition = {
  0: 0,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
} as const;

export type ItemCondition = (typeof ItemCondition)[keyof typeof ItemCondition];

export type ItemModel = {
  variantId: string;
  identifier?: string | null;
  storageLocationId?: string | null;
  condition: ItemCondition;
  purchaseDate: Date;
  retirementDate?: Date | null;
  id: string;
};

export type MaintenanceModel = {
  itemId: string;
  performedAt: Date;
  typeId: string;
  remarks?: string | null;
  performedById?: string | null;
  id: string;
  performedBy?: UserModel;
  type?: MaintenanceTypeModel;
};

export type MaintenanceTypeModel = {
  name: string;
  description?: string | null;
  id: string;
};

export type OrderItemModel = {
  orderId: string;
  variantId: string;
  quantity: number;
  id: string;
  variant: VariantModel;
};

export type OrderModel = {
  orderIdentifier?: string | null;
  orderDate: Date;
  status: OrderStatus;
  items: Array<OrderItemModel>;
  deliveryDate?: Date | null;
  id: string;
};

export const OrderStatus = {
  0: 0,
  1: 1,
  2: 2,
  3: 3,
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export type PersonModel = {
  firstName: string;
  lastName: string;
  remarks?: string | null;
  contactInfo?: string | null;
  externalId?: string | null;
  id: string;
};

export type ProductModel = {
  name: string;
  manufacturer: string;
  description?: string | null;
  typeId: string;
  id: string;
  type: ProductTypeModel;
};

export type ProductTypeModel = {
  name: string;
  description?: string | null;
  id: string;
};

export type StorageLocationModel = {
  name: string;
  remarks?: string | null;
  id: string;
};

export type UserModel = {
  id: string;
  eMail: string;
  firstName: string;
  lastName: string;
};

export type VariantModel = {
  productId: string;
  name: string;
  additionalSpecs?: string | null;
  id: string;
};

export type GetDepartmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/departments";
};

export type GetDepartmentsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetDepartmentsResponses = {
  /**
   * List of departments
   */
  200: Array<DepartmentModel>;
};

export type GetDepartmentsResponse =
  GetDepartmentsResponses[keyof GetDepartmentsResponses];

export type PostDepartmentsData = {
  body?: CreateDepartmentModel;
  path?: never;
  query?: never;
  url: "/departments";
};

export type PostDepartmentsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type PostDepartmentsResponses = {
  /**
   * Department created
   */
  201: DepartmentModel;
};

export type PostDepartmentsResponse =
  PostDepartmentsResponses[keyof PostDepartmentsResponses];

export type DeleteDepartmentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type DeleteDepartmentsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Department not found
   */
  404: unknown;
};

export type DeleteDepartmentsByIdResponses = {
  /**
   * Department deleted
   */
  204: void;
};

export type DeleteDepartmentsByIdResponse =
  DeleteDepartmentsByIdResponses[keyof DeleteDepartmentsByIdResponses];

export type GetDepartmentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type GetDepartmentsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Department not found
   */
  404: unknown;
};

export type GetDepartmentsByIdResponses = {
  /**
   * Department found
   */
  200: DepartmentModel;
};

export type GetDepartmentsByIdResponse =
  GetDepartmentsByIdResponses[keyof GetDepartmentsByIdResponses];

export type PutDepartmentsByIdData = {
  body?: DepartmentModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type PutDepartmentsByIdErrors = {
  /**
   * ID mismatch
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Department not found
   */
  404: unknown;
};

export type PutDepartmentsByIdResponses = {
  /**
   * Department updated
   */
  204: void;
};

export type PutDepartmentsByIdResponse =
  PutDepartmentsByIdResponses[keyof PutDepartmentsByIdResponses];

export type GetDepartmentsByIdPersonsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}/persons";
};

export type GetDepartmentsByIdPersonsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Department not found
   */
  404: unknown;
};

export type GetDepartmentsByIdPersonsResponses = {
  /**
   * List of persons
   */
  200: Array<PersonModel>;
};

export type GetDepartmentsByIdPersonsResponse =
  GetDepartmentsByIdPersonsResponses[keyof GetDepartmentsByIdPersonsResponses];

export type GetAssignmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/assignments";
};

export type GetAssignmentsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetAssignmentsResponses = {
  /**
   * List of item assignment histories
   */
  200: Array<ItemAssignmentHistoryModel>;
};

export type GetAssignmentsResponse =
  GetAssignmentsResponses[keyof GetAssignmentsResponses];

export type PostAssignmentsData = {
  body?: CreateItemAssignmentHistoryModel;
  path?: never;
  query?: never;
  url: "/assignments";
};

export type PostAssignmentsErrors = {
  /**
   * Invalid input or referenced item/person does not exist
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * An overlapping assignment already exists for this item
   */
  409: unknown;
};

export type PostAssignmentsResponses = {
  /**
   * Assignment created
   */
  201: ItemAssignmentHistoryModel;
};

export type PostAssignmentsResponse =
  PostAssignmentsResponses[keyof PostAssignmentsResponses];

export type DeleteAssignmentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/assignments/{id}";
};

export type DeleteAssignmentsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Assignment not found
   */
  404: unknown;
};

export type DeleteAssignmentsByIdResponses = {
  /**
   * Assignment deleted
   */
  204: void;
};

export type DeleteAssignmentsByIdResponse =
  DeleteAssignmentsByIdResponses[keyof DeleteAssignmentsByIdResponses];

export type GetAssignmentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/assignments/{id}";
};

export type GetAssignmentsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Assignment not found
   */
  404: unknown;
};

export type GetAssignmentsByIdResponses = {
  /**
   * Assignment found
   */
  200: ItemAssignmentHistoryModel;
};

export type GetAssignmentsByIdResponse =
  GetAssignmentsByIdResponses[keyof GetAssignmentsByIdResponses];

export type PutAssignmentsByIdData = {
  body?: ItemAssignmentHistoryModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/assignments/{id}";
};

export type PutAssignmentsByIdErrors = {
  /**
   * ID mismatch or referenced item/person does not exist
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Assignment not found
   */
  404: unknown;
  /**
   * An overlapping assignment already exists for this item
   */
  409: unknown;
};

export type PutAssignmentsByIdResponses = {
  /**
   * Assignment updated
   */
  204: void;
};

export type PutAssignmentsByIdResponse =
  PutAssignmentsByIdResponses[keyof PutAssignmentsByIdResponses];

export type GetItemsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/items";
};

export type GetItemsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetItemsResponses = {
  /**
   * List of items
   */
  200: Array<ItemModel>;
};

export type GetItemsResponse = GetItemsResponses[keyof GetItemsResponses];

export type PostItemsData = {
  body?: CreateItemModel;
  path?: never;
  query?: never;
  url: "/items";
};

export type PostItemsErrors = {
  /**
   * Invalid input or referenced variant/location not found
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A item with the same identifier already exists
   */
  409: unknown;
};

export type PostItemsResponses = {
  /**
   * Item created
   */
  201: ItemModel;
};

export type PostItemsResponse = PostItemsResponses[keyof PostItemsResponses];

export type DeleteItemsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type DeleteItemsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Item not found
   */
  404: unknown;
};

export type DeleteItemsByIdResponses = {
  /**
   * Item deleted
   */
  204: void;
};

export type DeleteItemsByIdResponse =
  DeleteItemsByIdResponses[keyof DeleteItemsByIdResponses];

export type GetItemsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type GetItemsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Item not found
   */
  404: unknown;
};

export type GetItemsByIdResponses = {
  /**
   * Item found
   */
  200: ItemModel;
};

export type GetItemsByIdResponse =
  GetItemsByIdResponses[keyof GetItemsByIdResponses];

export type PutItemsByIdData = {
  body?: ItemModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type PutItemsByIdErrors = {
  /**
   * ID mismatch or referenced variant/location not found
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Item not found
   */
  404: unknown;
  /**
   * A item with the same identifier already exists
   */
  409: unknown;
};

export type PutItemsByIdResponses = {
  /**
   * Item updated
   */
  204: void;
};

export type PutItemsByIdResponse =
  PutItemsByIdResponses[keyof PutItemsByIdResponses];

export type GetItemsByIdAssignmentsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}/assignments";
};

export type GetItemsByIdAssignmentsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Item not found
   */
  404: unknown;
};

export type GetItemsByIdAssignmentsResponses = {
  /**
   * List of assignment histories
   */
  200: Array<ItemAssignmentHistoryModel>;
};

export type GetItemsByIdAssignmentsResponse =
  GetItemsByIdAssignmentsResponses[keyof GetItemsByIdAssignmentsResponses];

export type GetItemsByIdMaintenanceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}/maintenance";
};

export type GetItemsByIdMaintenanceErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Item not found
   */
  404: unknown;
};

export type GetItemsByIdMaintenanceResponses = {
  /**
   * List of maintenances
   */
  200: Array<MaintenanceModel>;
};

export type GetItemsByIdMaintenanceResponse =
  GetItemsByIdMaintenanceResponses[keyof GetItemsByIdMaintenanceResponses];

export type GetMaintenancesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/maintenances";
};

export type GetMaintenancesErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetMaintenancesResponses = {
  /**
   * List of maintenances
   */
  200: Array<MaintenanceModel>;
};

export type GetMaintenancesResponse =
  GetMaintenancesResponses[keyof GetMaintenancesResponses];

export type PostMaintenancesData = {
  body?: CreateMaintenanceModel;
  path?: never;
  query?: never;
  url: "/maintenances";
};

export type PostMaintenancesErrors = {
  /**
   * Invalid input or referenced item does not exist
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type PostMaintenancesResponses = {
  /**
   * Maintenance created
   */
  201: MaintenanceModel;
};

export type PostMaintenancesResponse =
  PostMaintenancesResponses[keyof PostMaintenancesResponses];

export type DeleteMaintenancesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenances/{id}";
};

export type DeleteMaintenancesByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Maintenance not found
   */
  404: unknown;
};

export type DeleteMaintenancesByIdResponses = {
  /**
   * Maintenance deleted
   */
  204: void;
};

export type DeleteMaintenancesByIdResponse =
  DeleteMaintenancesByIdResponses[keyof DeleteMaintenancesByIdResponses];

export type GetMaintenancesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenances/{id}";
};

export type GetMaintenancesByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Maintenance not found
   */
  404: unknown;
};

export type GetMaintenancesByIdResponses = {
  /**
   * Maintenance found
   */
  200: MaintenanceModel;
};

export type GetMaintenancesByIdResponse =
  GetMaintenancesByIdResponses[keyof GetMaintenancesByIdResponses];

export type PutMaintenancesByIdData = {
  body?: MaintenanceModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenances/{id}";
};

export type PutMaintenancesByIdErrors = {
  /**
   * ID mismatch or referenced item does not exist
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Maintenance not found
   */
  404: unknown;
};

export type PutMaintenancesByIdResponses = {
  /**
   * Maintenance updated
   */
  204: void;
};

export type PutMaintenancesByIdResponse =
  PutMaintenancesByIdResponses[keyof PutMaintenancesByIdResponses];

export type GetMaintenanceTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/maintenanceTypes";
};

export type GetMaintenanceTypesErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetMaintenanceTypesResponses = {
  /**
   * List of maintenanceTypes
   */
  200: Array<MaintenanceTypeModel>;
};

export type GetMaintenanceTypesResponse =
  GetMaintenanceTypesResponses[keyof GetMaintenanceTypesResponses];

export type PostMaintenanceTypesData = {
  body?: CreateMaintenanceTypeModel;
  path?: never;
  query?: never;
  url: "/maintenanceTypes";
};

export type PostMaintenanceTypesErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type PostMaintenanceTypesResponses = {
  /**
   * MaintenanceType created
   */
  201: MaintenanceTypeModel;
};

export type PostMaintenanceTypesResponse =
  PostMaintenanceTypesResponses[keyof PostMaintenanceTypesResponses];

export type DeleteMaintenanceTypesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenanceTypes/{id}";
};

export type DeleteMaintenanceTypesByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * MaintenanceType not found
   */
  404: unknown;
};

export type DeleteMaintenanceTypesByIdResponses = {
  /**
   * MaintenanceType deleted
   */
  204: void;
};

export type DeleteMaintenanceTypesByIdResponse =
  DeleteMaintenanceTypesByIdResponses[keyof DeleteMaintenanceTypesByIdResponses];

export type GetMaintenanceTypesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenanceTypes/{id}";
};

export type GetMaintenanceTypesByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * MaintenanceType not found
   */
  404: unknown;
};

export type GetMaintenanceTypesByIdResponses = {
  /**
   * MaintenanceType found
   */
  200: MaintenanceTypeModel;
};

export type GetMaintenanceTypesByIdResponse =
  GetMaintenanceTypesByIdResponses[keyof GetMaintenanceTypesByIdResponses];

export type PutMaintenanceTypesByIdData = {
  body?: MaintenanceTypeModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenanceTypes/{id}";
};

export type PutMaintenanceTypesByIdErrors = {
  /**
   * ID mismatch
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * MaintenanceType not found
   */
  404: unknown;
};

export type PutMaintenanceTypesByIdResponses = {
  /**
   * MaintenanceType updated
   */
  204: void;
};

export type PutMaintenanceTypesByIdResponse =
  PutMaintenanceTypesByIdResponses[keyof PutMaintenanceTypesByIdResponses];

export type GetOrdersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/orders";
};

export type GetOrdersErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetOrdersResponses = {
  /**
   * List of orders
   */
  200: Array<OrderModel>;
};

export type GetOrdersResponse = GetOrdersResponses[keyof GetOrdersResponses];

export type PostOrdersData = {
  body?: CreateOrderModel;
  path?: never;
  query?: never;
  url: "/orders";
};

export type PostOrdersErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type PostOrdersResponses = {
  /**
   * Order created
   */
  201: OrderModel;
};

export type PostOrdersResponse = PostOrdersResponses[keyof PostOrdersResponses];

export type DeleteOrdersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/orders/{id}";
};

export type DeleteOrdersByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Order not found.
   */
  404: unknown;
};

export type DeleteOrdersByIdResponses = {
  /**
   * Order deleted
   */
  204: void;
};

export type DeleteOrdersByIdResponse =
  DeleteOrdersByIdResponses[keyof DeleteOrdersByIdResponses];

export type GetOrdersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/orders/{id}";
};

export type GetOrdersByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Order not found
   */
  404: unknown;
};

export type GetOrdersByIdResponses = {
  /**
   * Order found
   */
  200: OrderModel;
};

export type GetOrdersByIdResponse =
  GetOrdersByIdResponses[keyof GetOrdersByIdResponses];

export type PutOrdersByIdData = {
  body?: OrderModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/orders/{id}";
};

export type PutOrdersByIdErrors = {
  /**
   * ID mismatch
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Order not found or cannot be updated
   */
  404: unknown;
};

export type PutOrdersByIdResponses = {
  /**
   * Order updated
   */
  204: void;
};

export type PutOrdersByIdResponse =
  PutOrdersByIdResponses[keyof PutOrdersByIdResponses];

export type GetPersonsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/persons";
};

export type GetPersonsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetPersonsResponses = {
  /**
   * List of persons
   */
  200: Array<PersonModel>;
};

export type GetPersonsResponse = GetPersonsResponses[keyof GetPersonsResponses];

export type PostPersonsData = {
  body?: CreatePersonModel;
  path?: never;
  query?: never;
  url: "/persons";
};

export type PostPersonsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Person with same name or external ID already exists
   */
  409: unknown;
};

export type PostPersonsResponses = {
  /**
   * Person created
   */
  201: PersonModel;
};

export type PostPersonsResponse =
  PostPersonsResponses[keyof PostPersonsResponses];

export type DeletePersonsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}";
};

export type DeletePersonsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Person not found
   */
  404: unknown;
};

export type DeletePersonsByIdResponses = {
  /**
   * Person deleted
   */
  204: void;
};

export type DeletePersonsByIdResponse =
  DeletePersonsByIdResponses[keyof DeletePersonsByIdResponses];

export type GetPersonsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}";
};

export type GetPersonsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Person not found
   */
  404: unknown;
};

export type GetPersonsByIdResponses = {
  /**
   * Person found
   */
  200: PersonModel;
};

export type GetPersonsByIdResponse =
  GetPersonsByIdResponses[keyof GetPersonsByIdResponses];

export type PutPersonsByIdData = {
  body?: PersonModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}";
};

export type PutPersonsByIdErrors = {
  /**
   * ID mismatch
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Person not found
   */
  404: unknown;
};

export type PutPersonsByIdResponses = {
  /**
   * Person updated
   */
  204: void;
};

export type PutPersonsByIdResponse =
  PutPersonsByIdResponses[keyof PutPersonsByIdResponses];

export type GetProductsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/products";
};

export type GetProductsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetProductsResponses = {
  /**
   * List of products
   */
  200: Array<ProductModel>;
};

export type GetProductsResponse =
  GetProductsResponses[keyof GetProductsResponses];

export type PostProductsData = {
  body?: CreateProductModel;
  path?: never;
  query?: never;
  url: "/products";
};

export type PostProductsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A product with the same name and manufacturer already exists
   */
  409: unknown;
};

export type PostProductsResponses = {
  /**
   * Product created
   */
  201: ProductModel;
};

export type PostProductsResponse =
  PostProductsResponses[keyof PostProductsResponses];

export type DeleteProductsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}";
};

export type DeleteProductsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Product not found
   */
  404: unknown;
};

export type DeleteProductsByIdResponses = {
  /**
   * Product deleted
   */
  204: void;
};

export type DeleteProductsByIdResponse =
  DeleteProductsByIdResponses[keyof DeleteProductsByIdResponses];

export type GetProductsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}";
};

export type GetProductsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Product not found
   */
  404: unknown;
};

export type GetProductsByIdResponses = {
  /**
   * Product found
   */
  200: ProductModel;
};

export type GetProductsByIdResponse =
  GetProductsByIdResponses[keyof GetProductsByIdResponses];

export type PutProductsByIdData = {
  body?: ProductModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}";
};

export type PutProductsByIdErrors = {
  /**
   * ID mismatch
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Product not found
   */
  404: unknown;
  /**
   * A product with the same name and manufacturer already exists
   */
  409: unknown;
};

export type PutProductsByIdResponses = {
  /**
   * Product updated
   */
  204: void;
};

export type PutProductsByIdResponse =
  PutProductsByIdResponses[keyof PutProductsByIdResponses];

export type GetProductTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/productTypes";
};

export type GetProductTypesErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetProductTypesResponses = {
  /**
   * List of productTypes
   */
  200: Array<ProductTypeModel>;
};

export type GetProductTypesResponse =
  GetProductTypesResponses[keyof GetProductTypesResponses];

export type PostProductTypesData = {
  body?: CreateProductTypeModel;
  path?: never;
  query?: never;
  url: "/productTypes";
};

export type PostProductTypesErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type PostProductTypesResponses = {
  /**
   * ProductType created
   */
  201: ProductTypeModel;
};

export type PostProductTypesResponse =
  PostProductTypesResponses[keyof PostProductTypesResponses];

export type DeleteProductTypesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/productTypes/{id}";
};

export type DeleteProductTypesByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * ProductType not found
   */
  404: unknown;
};

export type DeleteProductTypesByIdResponses = {
  /**
   * ProductType deleted
   */
  204: void;
};

export type DeleteProductTypesByIdResponse =
  DeleteProductTypesByIdResponses[keyof DeleteProductTypesByIdResponses];

export type GetProductTypesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/productTypes/{id}";
};

export type GetProductTypesByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * ProductType not found
   */
  404: unknown;
};

export type GetProductTypesByIdResponses = {
  /**
   * ProductType found
   */
  200: ProductTypeModel;
};

export type GetProductTypesByIdResponse =
  GetProductTypesByIdResponses[keyof GetProductTypesByIdResponses];

export type PutProductTypesByIdData = {
  body?: ProductTypeModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/productTypes/{id}";
};

export type PutProductTypesByIdErrors = {
  /**
   * ID mismatch
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * ProductType not found
   */
  404: unknown;
};

export type PutProductTypesByIdResponses = {
  /**
   * ProductType updated
   */
  204: void;
};

export type PutProductTypesByIdResponse =
  PutProductTypesByIdResponses[keyof PutProductTypesByIdResponses];

export type GetStorageLocationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/storageLocations";
};

export type GetStorageLocationsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetStorageLocationsResponses = {
  /**
   * List of storage locations
   */
  200: Array<StorageLocationModel>;
};

export type GetStorageLocationsResponse =
  GetStorageLocationsResponses[keyof GetStorageLocationsResponses];

export type PostStorageLocationsData = {
  body?: CreateStorageLocationModel;
  path?: never;
  query?: never;
  url: "/storageLocations";
};

export type PostStorageLocationsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A storage location with the same name already exists
   */
  409: unknown;
};

export type PostStorageLocationsResponses = {
  /**
   * Storage location created
   */
  201: StorageLocationModel;
};

export type PostStorageLocationsResponse =
  PostStorageLocationsResponses[keyof PostStorageLocationsResponses];

export type DeleteStorageLocationsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/storageLocations/{id}";
};

export type DeleteStorageLocationsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Storage location not found
   */
  404: unknown;
};

export type DeleteStorageLocationsByIdResponses = {
  /**
   * Storage location deleted
   */
  204: void;
};

export type DeleteStorageLocationsByIdResponse =
  DeleteStorageLocationsByIdResponses[keyof DeleteStorageLocationsByIdResponses];

export type GetStorageLocationsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/storageLocations/{id}";
};

export type GetStorageLocationsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Storage location not found
   */
  404: unknown;
};

export type GetStorageLocationsByIdResponses = {
  /**
   * Storage location found
   */
  200: StorageLocationModel;
};

export type GetStorageLocationsByIdResponse =
  GetStorageLocationsByIdResponses[keyof GetStorageLocationsByIdResponses];

export type PutStorageLocationsByIdData = {
  body?: StorageLocationModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/storageLocations/{id}";
};

export type PutStorageLocationsByIdErrors = {
  /**
   * ID mismatch
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Storage location not found
   */
  404: unknown;
  /**
   * A storage location with the same name already exists
   */
  409: unknown;
};

export type PutStorageLocationsByIdResponses = {
  /**
   * Storage location updated
   */
  204: void;
};

export type PutStorageLocationsByIdResponse =
  PutStorageLocationsByIdResponses[keyof PutStorageLocationsByIdResponses];

export type GetStorageLocationsByIdItemsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/storageLocations/{id}/items";
};

export type GetStorageLocationsByIdItemsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Storage location not found
   */
  404: unknown;
};

export type GetStorageLocationsByIdItemsResponses = {
  /**
   * List of items
   */
  200: Array<ItemModel>;
};

export type GetStorageLocationsByIdItemsResponse =
  GetStorageLocationsByIdItemsResponses[keyof GetStorageLocationsByIdItemsResponses];

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users";
};

export type GetUsersErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetUsersResponses = {
  /**
   * OK
   */
  200: Array<UserModel>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type GetUsersByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type GetUsersByIdResponses = {
  /**
   * User found
   */
  200: StorageLocationModel;
};

export type GetUsersByIdResponse =
  GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type GetVariantsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/variants";
};

export type GetVariantsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetVariantsResponses = {
  /**
   * List of variants
   */
  200: Array<VariantModel>;
};

export type GetVariantsResponse =
  GetVariantsResponses[keyof GetVariantsResponses];

export type PostVariantsData = {
  body?: CreateVariantModel;
  path?: never;
  query?: never;
  url: "/variants";
};

export type PostVariantsErrors = {
  /**
   * Referenced product does not exist
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A variant with the same name already exists for this product
   */
  409: unknown;
};

export type PostVariantsResponses = {
  /**
   * variant created
   */
  201: VariantModel;
};

export type PostVariantsResponse =
  PostVariantsResponses[keyof PostVariantsResponses];

export type DeleteVariantsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}";
};

export type DeleteVariantsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * variant not found
   */
  404: unknown;
};

export type DeleteVariantsByIdResponses = {
  /**
   * variant deleted
   */
  204: void;
};

export type DeleteVariantsByIdResponse =
  DeleteVariantsByIdResponses[keyof DeleteVariantsByIdResponses];

export type GetVariantsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}";
};

export type GetVariantsByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * variant not found
   */
  404: unknown;
};

export type GetVariantsByIdResponses = {
  /**
   * variant found
   */
  200: VariantModel;
};

export type GetVariantsByIdResponse =
  GetVariantsByIdResponses[keyof GetVariantsByIdResponses];

export type PutVariantsByIdData = {
  body?: VariantModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}";
};

export type PutVariantsByIdErrors = {
  /**
   * ID mismatch
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * variant not found
   */
  404: unknown;
  /**
   * Another variant with the same name already exists for this product
   */
  409: unknown;
};

export type PutVariantsByIdResponses = {
  /**
   * variant updated
   */
  204: void;
};

export type PutVariantsByIdResponse =
  PutVariantsByIdResponses[keyof PutVariantsByIdResponses];

export type GetVariantsByIdItemsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}/items";
};

export type GetVariantsByIdItemsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * variant not found
   */
  404: unknown;
};

export type GetVariantsByIdItemsResponses = {
  /**
   * List of items
   */
  200: Array<ItemModel>;
};

export type GetVariantsByIdItemsResponse =
  GetVariantsByIdItemsResponses[keyof GetVariantsByIdItemsResponses];
