// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "https://localhost:7197/" | (string & {});
};

export type CreateOrUpdateDepartmentModel = {
  name: string;
  description?: null | string;
};

export type CreateOrUpdateItemAssignmentHistoryModel = {
  itemId: string;
  personId: string;
  assignedFrom: Date;
  assignedUntil?: null | Date;
  assignedById?: null | string;
};

export type CreateOrUpdateItemModel = {
  variantId: string;
  identifier?: null | string;
  storageLocationId?: null | string;
  condition: ItemCondition;
  purchaseDate: Date;
  retirementDate?: null | Date;
};

export type CreateOrUpdateMaintenanceModel = {
  itemId: string;
  performedAt: Date;
  typeId: string;
  remarks?: null | string;
  performedById?: null | string;
};

export type CreateOrUpdateMaintenanceTypeModel = {
  name: string;
  description?: null | string;
};

export type CreateOrUpdateOrderItemModel = {
  orderId: string;
  variantId: string;
  quantity: number | string;
};

export type CreateOrUpdateOrderModel = {
  orderIdentifier?: null | string;
  orderDate: Date;
  status: OrderStatus;
  items: Array<CreateOrUpdateOrderItemModel>;
  deliveryDate?: null | Date;
};

export type CreateOrUpdatePersonModel = {
  firstName: string;
  lastName: string;
  remarks?: null | string;
  contactInfo?: null | string;
  externalId?: null | string;
  departmentIds?: Array<string>;
};

export type CreateOrUpdateProductModel = {
  name: string;
  manufacturer: string;
  description?: null | string;
  typeId: string;
};

export type CreateOrUpdateProductTypeModel = {
  name: string;
  description?: null | string;
};

export type CreateOrUpdateStorageLocationModel = {
  name: string;
  remarks?: null | string;
};

export type CreateOrUpdateVariantModel = {
  productId: string;
  name: string;
  additionalSpecs?: null | string;
};

export type DepartmentModel = {
  id: string;
  name: string;
  description?: null | string;
};

export type ItemAssignmentHistoryModel = {
  id: string;
  person: PersonModel;
  assignedBy?: null | UserModel;
  itemId: string;
  personId: string;
  assignedFrom: Date;
  assignedUntil?: null | Date;
  assignedById?: null | string;
};

export const ItemCondition = {
  NEW: "New",
  USED: "Used",
  DAMAGED: "Damaged",
  DESTROYED: "Destroyed",
  LOST: "Lost",
} as const;

export type ItemCondition = (typeof ItemCondition)[keyof typeof ItemCondition];

export type ItemModel = {
  id: string;
  variant: VariantModel;
  variantId: string;
  identifier?: null | string;
  storageLocationId?: null | string;
  condition: ItemCondition;
  purchaseDate: Date;
  retirementDate?: null | Date;
};

export type MaintenanceModel = {
  id: string;
  performedBy?: null | UserModel;
  type: MaintenanceTypeModel;
  itemId: string;
  performedAt: Date;
  typeId: string;
  remarks?: null | string;
  performedById?: null | string;
};

export type MaintenanceTypeModel = {
  id: string;
  name: string;
  description?: null | string;
};

export type OrderItemModel = {
  id: string;
  variant: VariantModel;
  orderId: string;
  variantId: string;
  quantity: number | string;
};

export type OrderModel = {
  id: string;
  items: Array<OrderItemModel>;
  orderIdentifier?: null | string;
  orderDate: Date;
  status: OrderStatus;
  deliveryDate?: null | Date;
};

export const OrderStatus = {
  DRAFT: "Draft",
  SUBMITTED: "Submitted",
  DELIVERED: "Delivered",
  COMPLETED: "Completed",
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export type PersonModel = {
  id: string;
  departments: Array<DepartmentModel>;
  firstName: string;
  lastName: string;
  remarks?: null | string;
  contactInfo?: null | string;
  externalId?: null | string;
  departmentIds?: Array<string>;
};

export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number | string;
  detail?: null | string;
  instance?: null | string;
};

export type ProductModel = {
  id: string;
  type: ProductTypeModel;
  name: string;
  manufacturer: string;
  description?: null | string;
  typeId: string;
};

export type ProductTypeModel = {
  id: string;
  name: string;
  description?: null | string;
};

export type StorageLocationModel = {
  id: string;
  name: string;
  remarks?: null | string;
};

export type UserModel = {
  id: string;
  eMail: string;
  firstName?: null | string;
  lastName?: null | string;
};

export type VariantModel = {
  id: string;
  product: ProductModel;
  productId: string;
  name: string;
  additionalSpecs?: null | string;
};

export type GetDepartmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/departments";
};

export type GetDepartmentsResponses = {
  /**
   * OK
   */
  200: Array<DepartmentModel>;
};

export type GetDepartmentsResponse =
  GetDepartmentsResponses[keyof GetDepartmentsResponses];

export type PostDepartmentsData = {
  body: CreateOrUpdateDepartmentModel;
  path?: never;
  query?: never;
  url: "/departments";
};

export type PostDepartmentsResponses = {
  /**
   * Created
   */
  201: DepartmentModel;
};

export type PostDepartmentsResponse =
  PostDepartmentsResponses[keyof PostDepartmentsResponses];

export type DeleteDepartmentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type DeleteDepartmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteDepartmentsByIdError =
  DeleteDepartmentsByIdErrors[keyof DeleteDepartmentsByIdErrors];

export type DeleteDepartmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteDepartmentsByIdResponse =
  DeleteDepartmentsByIdResponses[keyof DeleteDepartmentsByIdResponses];

export type GetDepartmentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type GetDepartmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetDepartmentsByIdError =
  GetDepartmentsByIdErrors[keyof GetDepartmentsByIdErrors];

export type GetDepartmentsByIdResponses = {
  /**
   * OK
   */
  200: DepartmentModel;
};

export type GetDepartmentsByIdResponse =
  GetDepartmentsByIdResponses[keyof GetDepartmentsByIdResponses];

export type PutDepartmentsByIdData = {
  body: CreateOrUpdateDepartmentModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type PutDepartmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutDepartmentsByIdError =
  PutDepartmentsByIdErrors[keyof PutDepartmentsByIdErrors];

export type PutDepartmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutDepartmentsByIdResponse =
  PutDepartmentsByIdResponses[keyof PutDepartmentsByIdResponses];

export type GetDepartmentsByIdPersonsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/departments/{id}/persons";
};

export type GetDepartmentsByIdPersonsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetDepartmentsByIdPersonsError =
  GetDepartmentsByIdPersonsErrors[keyof GetDepartmentsByIdPersonsErrors];

export type GetDepartmentsByIdPersonsResponses = {
  /**
   * OK
   */
  200: Array<PersonModel>;
};

export type GetDepartmentsByIdPersonsResponse =
  GetDepartmentsByIdPersonsResponses[keyof GetDepartmentsByIdPersonsResponses];

export type GetAssignmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/assignments";
};

export type GetAssignmentsResponses = {
  /**
   * OK
   */
  200: Array<ItemAssignmentHistoryModel>;
};

export type GetAssignmentsResponse =
  GetAssignmentsResponses[keyof GetAssignmentsResponses];

export type PostAssignmentsData = {
  body: CreateOrUpdateItemAssignmentHistoryModel;
  path?: never;
  query?: never;
  url: "/assignments";
};

export type PostAssignmentsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostAssignmentsError =
  PostAssignmentsErrors[keyof PostAssignmentsErrors];

export type PostAssignmentsResponses = {
  /**
   * Created
   */
  201: ItemAssignmentHistoryModel;
};

export type PostAssignmentsResponse =
  PostAssignmentsResponses[keyof PostAssignmentsResponses];

export type DeleteAssignmentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/assignments/{id}";
};

export type DeleteAssignmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteAssignmentsByIdError =
  DeleteAssignmentsByIdErrors[keyof DeleteAssignmentsByIdErrors];

export type DeleteAssignmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAssignmentsByIdResponse =
  DeleteAssignmentsByIdResponses[keyof DeleteAssignmentsByIdResponses];

export type GetAssignmentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/assignments/{id}";
};

export type GetAssignmentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetAssignmentsByIdError =
  GetAssignmentsByIdErrors[keyof GetAssignmentsByIdErrors];

export type GetAssignmentsByIdResponses = {
  /**
   * OK
   */
  200: ItemAssignmentHistoryModel;
};

export type GetAssignmentsByIdResponse =
  GetAssignmentsByIdResponses[keyof GetAssignmentsByIdResponses];

export type PutAssignmentsByIdData = {
  body: CreateOrUpdateItemAssignmentHistoryModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/assignments/{id}";
};

export type PutAssignmentsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutAssignmentsByIdError =
  PutAssignmentsByIdErrors[keyof PutAssignmentsByIdErrors];

export type PutAssignmentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutAssignmentsByIdResponse =
  PutAssignmentsByIdResponses[keyof PutAssignmentsByIdResponses];

export type GetItemsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/items";
};

export type GetItemsResponses = {
  /**
   * OK
   */
  200: Array<ItemModel>;
};

export type GetItemsResponse = GetItemsResponses[keyof GetItemsResponses];

export type PostItemsData = {
  body: CreateOrUpdateItemModel;
  path?: never;
  query?: never;
  url: "/items";
};

export type PostItemsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostItemsError = PostItemsErrors[keyof PostItemsErrors];

export type PostItemsResponses = {
  /**
   * Created
   */
  201: ItemModel;
};

export type PostItemsResponse = PostItemsResponses[keyof PostItemsResponses];

export type DeleteItemsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type DeleteItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteItemsByIdError =
  DeleteItemsByIdErrors[keyof DeleteItemsByIdErrors];

export type DeleteItemsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteItemsByIdResponse =
  DeleteItemsByIdResponses[keyof DeleteItemsByIdResponses];

export type GetItemsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type GetItemsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetItemsByIdError = GetItemsByIdErrors[keyof GetItemsByIdErrors];

export type GetItemsByIdResponses = {
  /**
   * OK
   */
  200: ItemModel;
};

export type GetItemsByIdResponse =
  GetItemsByIdResponses[keyof GetItemsByIdResponses];

export type PutItemsByIdData = {
  body: CreateOrUpdateItemModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type PutItemsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutItemsByIdError = PutItemsByIdErrors[keyof PutItemsByIdErrors];

export type PutItemsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutItemsByIdResponse =
  PutItemsByIdResponses[keyof PutItemsByIdResponses];

export type GetItemsByIdAssignmentsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}/assignments";
};

export type GetItemsByIdAssignmentsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetItemsByIdAssignmentsError =
  GetItemsByIdAssignmentsErrors[keyof GetItemsByIdAssignmentsErrors];

export type GetItemsByIdAssignmentsResponses = {
  /**
   * OK
   */
  200: Array<ItemAssignmentHistoryModel>;
};

export type GetItemsByIdAssignmentsResponse =
  GetItemsByIdAssignmentsResponses[keyof GetItemsByIdAssignmentsResponses];

export type GetItemsByIdMaintenanceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/items/{id}/maintenance";
};

export type GetItemsByIdMaintenanceErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetItemsByIdMaintenanceError =
  GetItemsByIdMaintenanceErrors[keyof GetItemsByIdMaintenanceErrors];

export type GetItemsByIdMaintenanceResponses = {
  /**
   * OK
   */
  200: Array<MaintenanceModel>;
};

export type GetItemsByIdMaintenanceResponse =
  GetItemsByIdMaintenanceResponses[keyof GetItemsByIdMaintenanceResponses];

export type GetMaintenancesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/maintenances";
};

export type GetMaintenancesResponses = {
  /**
   * OK
   */
  200: Array<MaintenanceModel>;
};

export type GetMaintenancesResponse =
  GetMaintenancesResponses[keyof GetMaintenancesResponses];

export type PostMaintenancesData = {
  body: CreateOrUpdateMaintenanceModel;
  path?: never;
  query?: never;
  url: "/maintenances";
};

export type PostMaintenancesErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostMaintenancesError =
  PostMaintenancesErrors[keyof PostMaintenancesErrors];

export type PostMaintenancesResponses = {
  /**
   * Created
   */
  201: MaintenanceModel;
};

export type PostMaintenancesResponse =
  PostMaintenancesResponses[keyof PostMaintenancesResponses];

export type DeleteMaintenancesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenances/{id}";
};

export type DeleteMaintenancesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteMaintenancesByIdError =
  DeleteMaintenancesByIdErrors[keyof DeleteMaintenancesByIdErrors];

export type DeleteMaintenancesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteMaintenancesByIdResponse =
  DeleteMaintenancesByIdResponses[keyof DeleteMaintenancesByIdResponses];

export type GetMaintenancesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenances/{id}";
};

export type GetMaintenancesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetMaintenancesByIdError =
  GetMaintenancesByIdErrors[keyof GetMaintenancesByIdErrors];

export type GetMaintenancesByIdResponses = {
  /**
   * OK
   */
  200: MaintenanceModel;
};

export type GetMaintenancesByIdResponse =
  GetMaintenancesByIdResponses[keyof GetMaintenancesByIdResponses];

export type PutMaintenancesByIdData = {
  body: CreateOrUpdateMaintenanceModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenances/{id}";
};

export type PutMaintenancesByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutMaintenancesByIdError =
  PutMaintenancesByIdErrors[keyof PutMaintenancesByIdErrors];

export type PutMaintenancesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutMaintenancesByIdResponse =
  PutMaintenancesByIdResponses[keyof PutMaintenancesByIdResponses];

export type GetMaintenanceTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/maintenanceTypes";
};

export type GetMaintenanceTypesResponses = {
  /**
   * OK
   */
  200: Array<MaintenanceTypeModel>;
};

export type GetMaintenanceTypesResponse =
  GetMaintenanceTypesResponses[keyof GetMaintenanceTypesResponses];

export type PostMaintenanceTypesData = {
  body: CreateOrUpdateMaintenanceTypeModel;
  path?: never;
  query?: never;
  url: "/maintenanceTypes";
};

export type PostMaintenanceTypesResponses = {
  /**
   * Created
   */
  201: MaintenanceTypeModel;
};

export type PostMaintenanceTypesResponse =
  PostMaintenanceTypesResponses[keyof PostMaintenanceTypesResponses];

export type DeleteMaintenanceTypesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenanceTypes/{id}";
};

export type DeleteMaintenanceTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteMaintenanceTypesByIdError =
  DeleteMaintenanceTypesByIdErrors[keyof DeleteMaintenanceTypesByIdErrors];

export type DeleteMaintenanceTypesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteMaintenanceTypesByIdResponse =
  DeleteMaintenanceTypesByIdResponses[keyof DeleteMaintenanceTypesByIdResponses];

export type GetMaintenanceTypesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenanceTypes/{id}";
};

export type GetMaintenanceTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetMaintenanceTypesByIdError =
  GetMaintenanceTypesByIdErrors[keyof GetMaintenanceTypesByIdErrors];

export type GetMaintenanceTypesByIdResponses = {
  /**
   * OK
   */
  200: MaintenanceTypeModel;
};

export type GetMaintenanceTypesByIdResponse =
  GetMaintenanceTypesByIdResponses[keyof GetMaintenanceTypesByIdResponses];

export type PutMaintenanceTypesByIdData = {
  body: CreateOrUpdateMaintenanceTypeModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/maintenanceTypes/{id}";
};

export type PutMaintenanceTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutMaintenanceTypesByIdError =
  PutMaintenanceTypesByIdErrors[keyof PutMaintenanceTypesByIdErrors];

export type PutMaintenanceTypesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutMaintenanceTypesByIdResponse =
  PutMaintenanceTypesByIdResponses[keyof PutMaintenanceTypesByIdResponses];

export type GetOrdersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/orders";
};

export type GetOrdersResponses = {
  /**
   * OK
   */
  200: Array<OrderModel>;
};

export type GetOrdersResponse = GetOrdersResponses[keyof GetOrdersResponses];

export type PostOrdersData = {
  body: CreateOrUpdateOrderModel;
  path?: never;
  query?: never;
  url: "/orders";
};

export type PostOrdersResponses = {
  /**
   * Created
   */
  201: OrderModel;
};

export type PostOrdersResponse = PostOrdersResponses[keyof PostOrdersResponses];

export type DeleteOrdersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/orders/{id}";
};

export type DeleteOrdersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteOrdersByIdError =
  DeleteOrdersByIdErrors[keyof DeleteOrdersByIdErrors];

export type DeleteOrdersByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteOrdersByIdResponse =
  DeleteOrdersByIdResponses[keyof DeleteOrdersByIdResponses];

export type GetOrdersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/orders/{id}";
};

export type GetOrdersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetOrdersByIdError = GetOrdersByIdErrors[keyof GetOrdersByIdErrors];

export type GetOrdersByIdResponses = {
  /**
   * OK
   */
  200: OrderModel;
};

export type GetOrdersByIdResponse =
  GetOrdersByIdResponses[keyof GetOrdersByIdResponses];

export type PutOrdersByIdData = {
  body: CreateOrUpdateOrderModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/orders/{id}";
};

export type PutOrdersByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutOrdersByIdError = PutOrdersByIdErrors[keyof PutOrdersByIdErrors];

export type PutOrdersByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutOrdersByIdResponse =
  PutOrdersByIdResponses[keyof PutOrdersByIdResponses];

export type GetPersonsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/persons";
};

export type GetPersonsResponses = {
  /**
   * OK
   */
  200: Array<PersonModel>;
};

export type GetPersonsResponse = GetPersonsResponses[keyof GetPersonsResponses];

export type PostPersonsData = {
  body: CreateOrUpdatePersonModel;
  path?: never;
  query?: never;
  url: "/persons";
};

export type PostPersonsErrors = {
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostPersonsError = PostPersonsErrors[keyof PostPersonsErrors];

export type PostPersonsResponses = {
  /**
   * Created
   */
  201: PersonModel;
};

export type PostPersonsResponse =
  PostPersonsResponses[keyof PostPersonsResponses];

export type DeletePersonsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}";
};

export type DeletePersonsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeletePersonsByIdError =
  DeletePersonsByIdErrors[keyof DeletePersonsByIdErrors];

export type DeletePersonsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeletePersonsByIdResponse =
  DeletePersonsByIdResponses[keyof DeletePersonsByIdResponses];

export type GetPersonsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}";
};

export type GetPersonsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetPersonsByIdError =
  GetPersonsByIdErrors[keyof GetPersonsByIdErrors];

export type GetPersonsByIdResponses = {
  /**
   * OK
   */
  200: PersonModel;
};

export type GetPersonsByIdResponse =
  GetPersonsByIdResponses[keyof GetPersonsByIdResponses];

export type PutPersonsByIdData = {
  body: CreateOrUpdatePersonModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}";
};

export type PutPersonsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutPersonsByIdError =
  PutPersonsByIdErrors[keyof PutPersonsByIdErrors];

export type PutPersonsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutPersonsByIdResponse =
  PutPersonsByIdResponses[keyof PutPersonsByIdResponses];

export type GetPersonsByIdItemsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/persons/{id}/items";
};

export type GetPersonsByIdItemsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetPersonsByIdItemsError =
  GetPersonsByIdItemsErrors[keyof GetPersonsByIdItemsErrors];

export type GetPersonsByIdItemsResponses = {
  /**
   * OK
   */
  200: Array<ItemModel>;
};

export type GetPersonsByIdItemsResponse =
  GetPersonsByIdItemsResponses[keyof GetPersonsByIdItemsResponses];

export type GetProductsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/products";
};

export type GetProductsResponses = {
  /**
   * OK
   */
  200: Array<ProductModel>;
};

export type GetProductsResponse =
  GetProductsResponses[keyof GetProductsResponses];

export type PostProductsData = {
  body: CreateOrUpdateProductModel;
  path?: never;
  query?: never;
  url: "/products";
};

export type PostProductsErrors = {
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostProductsError = PostProductsErrors[keyof PostProductsErrors];

export type PostProductsResponses = {
  /**
   * Created
   */
  201: ProductModel;
};

export type PostProductsResponse =
  PostProductsResponses[keyof PostProductsResponses];

export type DeleteProductsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}";
};

export type DeleteProductsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteProductsByIdError =
  DeleteProductsByIdErrors[keyof DeleteProductsByIdErrors];

export type DeleteProductsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteProductsByIdResponse =
  DeleteProductsByIdResponses[keyof DeleteProductsByIdResponses];

export type GetProductsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}";
};

export type GetProductsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetProductsByIdError =
  GetProductsByIdErrors[keyof GetProductsByIdErrors];

export type GetProductsByIdResponses = {
  /**
   * OK
   */
  200: ProductModel;
};

export type GetProductsByIdResponse =
  GetProductsByIdResponses[keyof GetProductsByIdResponses];

export type PutProductsByIdData = {
  body: CreateOrUpdateProductModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}";
};

export type PutProductsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutProductsByIdError =
  PutProductsByIdErrors[keyof PutProductsByIdErrors];

export type PutProductsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutProductsByIdResponse =
  PutProductsByIdResponses[keyof PutProductsByIdResponses];

export type GetProductsByIdVariantsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/products/{id}/variants";
};

export type GetProductsByIdVariantsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetProductsByIdVariantsError =
  GetProductsByIdVariantsErrors[keyof GetProductsByIdVariantsErrors];

export type GetProductsByIdVariantsResponses = {
  /**
   * OK
   */
  200: Array<VariantModel>;
};

export type GetProductsByIdVariantsResponse =
  GetProductsByIdVariantsResponses[keyof GetProductsByIdVariantsResponses];

export type GetProductTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/productTypes";
};

export type GetProductTypesResponses = {
  /**
   * OK
   */
  200: Array<ProductTypeModel>;
};

export type GetProductTypesResponse =
  GetProductTypesResponses[keyof GetProductTypesResponses];

export type PostProductTypesData = {
  body: CreateOrUpdateProductTypeModel;
  path?: never;
  query?: never;
  url: "/productTypes";
};

export type PostProductTypesResponses = {
  /**
   * Created
   */
  201: ProductTypeModel;
};

export type PostProductTypesResponse =
  PostProductTypesResponses[keyof PostProductTypesResponses];

export type DeleteProductTypesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/productTypes/{id}";
};

export type DeleteProductTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteProductTypesByIdError =
  DeleteProductTypesByIdErrors[keyof DeleteProductTypesByIdErrors];

export type DeleteProductTypesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteProductTypesByIdResponse =
  DeleteProductTypesByIdResponses[keyof DeleteProductTypesByIdResponses];

export type GetProductTypesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/productTypes/{id}";
};

export type GetProductTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetProductTypesByIdError =
  GetProductTypesByIdErrors[keyof GetProductTypesByIdErrors];

export type GetProductTypesByIdResponses = {
  /**
   * OK
   */
  200: ProductTypeModel;
};

export type GetProductTypesByIdResponse =
  GetProductTypesByIdResponses[keyof GetProductTypesByIdResponses];

export type PutProductTypesByIdData = {
  body: CreateOrUpdateProductTypeModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/productTypes/{id}";
};

export type PutProductTypesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutProductTypesByIdError =
  PutProductTypesByIdErrors[keyof PutProductTypesByIdErrors];

export type PutProductTypesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutProductTypesByIdResponse =
  PutProductTypesByIdResponses[keyof PutProductTypesByIdResponses];

export type GetStorageLocationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/storageLocations";
};

export type GetStorageLocationsResponses = {
  /**
   * OK
   */
  200: Array<StorageLocationModel>;
};

export type GetStorageLocationsResponse =
  GetStorageLocationsResponses[keyof GetStorageLocationsResponses];

export type PostStorageLocationsData = {
  body: CreateOrUpdateStorageLocationModel;
  path?: never;
  query?: never;
  url: "/storageLocations";
};

export type PostStorageLocationsErrors = {
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostStorageLocationsError =
  PostStorageLocationsErrors[keyof PostStorageLocationsErrors];

export type PostStorageLocationsResponses = {
  /**
   * Created
   */
  201: StorageLocationModel;
};

export type PostStorageLocationsResponse =
  PostStorageLocationsResponses[keyof PostStorageLocationsResponses];

export type DeleteStorageLocationsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/storageLocations/{id}";
};

export type DeleteStorageLocationsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteStorageLocationsByIdError =
  DeleteStorageLocationsByIdErrors[keyof DeleteStorageLocationsByIdErrors];

export type DeleteStorageLocationsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteStorageLocationsByIdResponse =
  DeleteStorageLocationsByIdResponses[keyof DeleteStorageLocationsByIdResponses];

export type GetStorageLocationsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/storageLocations/{id}";
};

export type GetStorageLocationsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetStorageLocationsByIdError =
  GetStorageLocationsByIdErrors[keyof GetStorageLocationsByIdErrors];

export type GetStorageLocationsByIdResponses = {
  /**
   * OK
   */
  200: StorageLocationModel;
};

export type GetStorageLocationsByIdResponse =
  GetStorageLocationsByIdResponses[keyof GetStorageLocationsByIdResponses];

export type PutStorageLocationsByIdData = {
  body: CreateOrUpdateStorageLocationModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/storageLocations/{id}";
};

export type PutStorageLocationsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutStorageLocationsByIdError =
  PutStorageLocationsByIdErrors[keyof PutStorageLocationsByIdErrors];

export type PutStorageLocationsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutStorageLocationsByIdResponse =
  PutStorageLocationsByIdResponses[keyof PutStorageLocationsByIdResponses];

export type GetStorageLocationsByIdItemsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/storageLocations/{id}/items";
};

export type GetStorageLocationsByIdItemsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetStorageLocationsByIdItemsError =
  GetStorageLocationsByIdItemsErrors[keyof GetStorageLocationsByIdItemsErrors];

export type GetStorageLocationsByIdItemsResponses = {
  /**
   * OK
   */
  200: Array<ItemModel>;
};

export type GetStorageLocationsByIdItemsResponse =
  GetStorageLocationsByIdItemsResponses[keyof GetStorageLocationsByIdItemsResponses];

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users";
};

export type GetUsersResponses = {
  /**
   * OK
   */
  200: Array<UserModel>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type GetUsersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
  /**
   * OK
   */
  200: UserModel;
};

export type GetUsersByIdResponse =
  GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type GetVariantsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/variants";
};

export type GetVariantsResponses = {
  /**
   * OK
   */
  200: Array<VariantModel>;
};

export type GetVariantsResponse =
  GetVariantsResponses[keyof GetVariantsResponses];

export type PostVariantsData = {
  body: CreateOrUpdateVariantModel;
  path?: never;
  query?: never;
  url: "/variants";
};

export type PostVariantsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostVariantsError = PostVariantsErrors[keyof PostVariantsErrors];

export type PostVariantsResponses = {
  /**
   * Created
   */
  201: VariantModel;
};

export type PostVariantsResponse =
  PostVariantsResponses[keyof PostVariantsResponses];

export type DeleteVariantsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}";
};

export type DeleteVariantsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteVariantsByIdError =
  DeleteVariantsByIdErrors[keyof DeleteVariantsByIdErrors];

export type DeleteVariantsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteVariantsByIdResponse =
  DeleteVariantsByIdResponses[keyof DeleteVariantsByIdResponses];

export type GetVariantsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}";
};

export type GetVariantsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetVariantsByIdError =
  GetVariantsByIdErrors[keyof GetVariantsByIdErrors];

export type GetVariantsByIdResponses = {
  /**
   * OK
   */
  200: VariantModel;
};

export type GetVariantsByIdResponse =
  GetVariantsByIdResponses[keyof GetVariantsByIdResponses];

export type PutVariantsByIdData = {
  body: CreateOrUpdateVariantModel;
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}";
};

export type PutVariantsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PutVariantsByIdError =
  PutVariantsByIdErrors[keyof PutVariantsByIdErrors];

export type PutVariantsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PutVariantsByIdResponse =
  PutVariantsByIdResponses[keyof PutVariantsByIdResponses];

export type GetVariantsByIdItemsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/variants/{id}/items";
};

export type GetVariantsByIdItemsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetVariantsByIdItemsError =
  GetVariantsByIdItemsErrors[keyof GetVariantsByIdItemsErrors];

export type GetVariantsByIdItemsResponses = {
  /**
   * OK
   */
  200: Array<ItemModel>;
};

export type GetVariantsByIdItemsResponse =
  GetVariantsByIdItemsResponses[keyof GetVariantsByIdItemsResponses];
